// Package v1beta1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1beta1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y9i3LcNrYo+ivYvXeV7ZlWy3YyORlVpeYosp1oYlvakpzU2ZFvApHobozYYA8ASu6k",
	"XHX/4f7h/ZJTWAsgQRIg2Xo5D+5dNbGaeC4sLKz3+nWS5Kt1LpjQarL360QlS7ai8M99uj6W+RVPmTxd",
	"s8T8lDKVSL7WPBeTvWYDgl8vmCJUkH2h+EXGyH6h8xU1PchxRvU8lyvyeH//+AlZ274kycWcLwoJrWaT",
	"6WQt8zWTmjNYB13zdzJrT3+2ZIQLzaSgGdnfPyb7x4fk3clrM4LerNlkb6K05GIx+Tid0EIvc8l/gTmi",
	"wx3tF3r5nNQaEybSdc6Fjo6dZJwJfZh2jomNyOGLjiFOWSKZHjKMgpbtoaaTa8k1OxLZZrKnZcE+Ticp",
	"V+uMbt7SFWsP/W2xomJHMppSc1q2LRF0xcg8l0QvWXlQwZUzYTravc9pkWmceNqY6Icl00tmBuQKTqs8",
	"fq6IHcSb4CLPM0aFmcE1PIMvIdiYPiSfw7kxoXmCB+evm4liNdn7cULpevI+sA2V5GtEt/rwr7nSZmgL",
	"fmxGdE4k+3fBFBwB12wFXVuj2h+olHQDf+eXrBf7oFEf1n2cTswKuDSg/7EOo6m7MgG099bgIW4DAUtw",
	"VJDKL/7FEm32sH+h8qzQ7JjqZXsfJ2wtmTLUxBABatuSOc8YWVO9bF/vdXAcA4+yt2liYE5xnFwAWqqN",
	"0mw1I29zzYheUk2o2BD2gSvNxQKbXvMsIxeM5FdMmpuhGRAY9oGu1pnZ1+4VlbtZvtil6/UsyxdBSLdh",
	"sF73Y6NZI12vM4uOPhYCzVXmpP5d0DQDkCe50JQLJtv4OZ182DFdd66oNDdTmTHsGg7KoewP/12OWLYo",
	"B8aluxWZD0wAvaFZdjSf7P346+S/JJtP9ib/uVu9C7v2Udh9xTPmOn2cdrc9YRnV/ArRxDSuoav5sY1c",
	"jfW9FFffU4lIUkMZVn2gacpNW5od15q0rmL9nF6KKy5zsTK09IpKDsTvkm12rmhWGITjUk0JF2ZdLCVp",
	"YYYhshCar9iMmGO+ZBtCRUqwB6PJkqwKpQ22XTB9zZggz6DB8799RpIllTTRTCrvLrttRzDMgeE4l4E3",
	"wfxKVnS9NgvjwhDrFdXkfLLMlTYf90qEMn+dT8hjNlvMpuR88uXTL5/uffn0fPKkfhfs7+aGUm3e1cne",
	"5P85P0//umf+579C1N9fZoNXGIZSgeM2yNLkAMrr1jMWNPs4nYjgY3dWv5H4yrlDe/b//7//X/2oSJaL",
	"xZQoTaUm11wvCSUZM5AhuSSiWF0wOYUjtqAmIifXS66ZWtOE9VNtt68Amf11kgs2AH6HK7pgsVPou6OH",
	"IuMi3vv9x/fdmHnCVF7IhL3mK65V6DHA7ySDBiVD0aCK9cNO1kV7pIPjdziIQfUkl0zNyCvEeMkMdOGa",
	"XlDFUvM8+IdsNlDH86ez//W3EDKv2CqXm/bkb+B3Oz/gQb5GmkMKwfUtVvL8b1+sBr84Tah3ATzJhdKS",
	"cjEU6ll5hANva+Ps+xZ9qqkuVPjRxG/AwBHFxSKr31L73KfsiuOlcq/osWRrah/IU3NJ8Z8nhRD4r5dS",
	"5nIynbwTlyK/FpPpxLyWGdMsHf7I1nfgz9n66C2i9a1aVeuTW2brQ7Xu1idvI3VAf59nBdK+igDXwf2C",
	"zbkwQhrQv5RcQQ9SGIy92ADb1oUpYdL6TvB/FwwpquV9/HHNreEihIatWyhZklG+Os4znmy2QEjc+Emt",
	"d5PgwtpvS21xoq0I7Zu8EPoG/WC+aOf3H4Nn33yI68eHp9Ih6fhXzzauCTlbHUdbCOqhE6FT9EXLyQkz",
	"L+1kGkHqZX6NWLYwrN2SijQDVLfIeL1kiIX5tbmNtc1yRSRb5VcohzoiY+d738384LLxanYTuDu5bW9b",
	"1yxyleZMMpGw0EthPxm5CsnrOss3LCVHB4c75mgzToUm3GCgYXcMZZvTRJMLmlwa0HXOHbp3/np6GAt1",
	"WqxWVG4GvhpZ5gNRxV+MbxnN9HIzmU5esIWkKUuDr8Tb3F/L9k9FffnVpNEm3mqibQKvRL1B8LWoN2lu",
	"zEC90MsDUMC1aQVd8++ZVADvlvLv+NB+I6m9e4AR+BtLCdIExFK4WlYxYB/1uUF9PPwZOWXSdCRqmRcZ",
	"sNNXTBqGKskXgv9SjqYctmZUM6Ur9R8IYciLr+iGSGbGJYXwRoAmakbe5JIRLub5HllqvVZ7u7sLrmeX",
	"X6oZzw1RWxmmbrNreHrJLwqdS7WbsiuW7Sq+2KEyMRx+ogvJduma78BiBQB0tkr/UzruLHgjLR1zJLr7",
	"ZtvGXWqt1gS5XFBh9T3qpa+bCynjaq0Jlcxp4oBprM/brZzrelDM9byiPAMhO7KZLd6YQi9L+IWel7qE",
	"VWJwkOQUevliI+iKJ0ceKPaV4gtQDgTwvq8LofBPZUi8BIStQ7kSDQq99JTg5sFTAXEIHsKojuyfp0dv",
	"S/2YQRpoj+owK5XixfQXQXhqjmDOmXRagR/PJwuZF2t1PpmS88nT88l7Q/V/PJ8khdL5Cn/O5eJ88v7J",
	"dkpPf2aD3seSzfmH+qvees/PQO9sGpbyS20HwGiWGo1cLnasOqPzRpjpT4v5sOkVNBwy/Q7AJTy97tUT",
	"1gamJR7571aKCBfgQhr4rlH/WyFND9af5BkbiO31poR90JImWhGZGw5rLvNVEKNJoYDRqjD19jhuptwF",
	"dLXo3kbi9/AXrK38g9Fs9RNNEqYslrvPWyK0MiIg1bmsI9FeC4tOXUNAolwu9syMTlX32NH3R3uPnszI",
	"CcDR3lnHYJVTAXFW6ww0IA2asgPa+hRPwg1kJK680I0RFll+QTN4Jw3HtAGtepbVSdQN8Rj29lD4uw25",
	"jtDp1BMZkFYDEgO3UsdkAzncGEtbBN3sM+VmzhUXDiusYhbWY/fe8Zx1P0HTyZrJd8pwCx0vIjaJDqEM",
	"39W5iFNoERngY3llrR0RT8WQ10GC84AJ+gfoBtOQEbqh9DGGbN3dgjjX2YUkkhkGllB3PRvPiyEXYFEw",
	"eNmml0NeVNPTvEs7Q55WaKzWLOFznnS9dOWo9/3aDl7Rvb+97vINo11RFIpy/P7XSkpC82mYV647TBBV",
	"rNc56B3JRa6X5OjwxQFQeLQnBx0qRrHuTsW6Sy4CUtZ3XKSEwy2HltZUWILMPfInL0/PiJsAwYoQ9NCh",
	"AqYBBBdz50ph3yxWOQygFIBuIsUFGF6ss4KB84wcUCFyMHkV65Rqls7IoSAHdMWyA6rYvYPSQE/tGJCF",
	"gblimqZU0z5B8Ahg9IZpCkyZ1XYOFR1RhRoXF+2hesuxc/TdcCP2dt9yEIwBLzInIvvshhpv7P3f2JLb",
	"j+gsWgdyB7qJkU58EjphzhSpxHa3HU+877qXrpEdIgCl6yjGNJwsp5PLL1Ws8Xdfqkbj3CDq8yiFBAag",
	"2YWnUTnAsA7N5msm1JLPdbTPmolT06Bh2WoKDDUXtcGCQ2tFfWx+YM+9XSI76LnrjZPra988PCNtRF34",
	"nGZ+iH6moZjxxVrUzTTF105h9+7E2cbah8ugjY53J3u2Bh4sczZ7xqhCp4wbPL2uHqUqmWZZj4oCvCOt",
	"8wTCuSbb9MuQYTnJt+fXZKXrJTNYVa7LOVo6PLs/ecxi0VBVUmuf3Uc35MKFWlZH5cCvmHZaMeXUbL03",
	"r35G0DcMMMc5gtINbJAwByyiNtuWDsq30fJteTK4u9BxfE11EtAFw8/AKAnCMgZg54JcwM/KsC4Czb0B",
	"16bwplb0A18VK+vLR3JJ1kwmhjdewGbRggygRR6IWCcWmNNMNYwEHZejAtFZcWGmnew9KzdvGOiFYRrf",
	"g4I5Y4klvZ2cDb1g2alrbDoWoN0+W0qmlnmW9g3gr+tj7CBOLWQjB+I+16QPh54AJwTgBSPsA0sKzVID",
	"xfh5qeh8+/VxcUZeamEHseiIW4Z95OIQOzwLqPi1pJotev2PTvIsywt96po3Ub0cJ4TmB2bPc55QzU75",
	"QnCxOEH+O+D/GGta0xg5/h2tt8S++EnVt5ICDvZHKXPUC416IegRvV1OlFGlY9fNhsHud6Vtis4TVj11",
	"Nq/roaJNR2LxyVVSnWcz6OmLvzejquqPqqrqJm1txzBJ12uweOeFSAlFOxyaK1NycHoyJas8ZRl6MF0W",
	"F0wKppkiPAdg0jWfefyGml09m3UuoU1Y2Ic1R8vWKUtykQbDHKA/BmaVNOOKZjzlelPaEL2FmGnQ7QJ5",
	"7c+eT9qs93QCTi1dYWXDJalGvJkZmFCNyMWUk6kNeK2zloUxMGcGzut8XWTw08UGft0/PiQKboyBPbQH",
	"KdncyNWq0PQiY4HoMkSkIFd5BpKMYl98vsNEkqcsJccv31T//u7g9D+fPTXLmZE3jpNfMmJeplnJa3KW",
	"AUdPfXzoYliRKtSO5GKjWejiAAsrw/qJQ5EikqFPUIkT2AcJPpCqfxc043POUhCUgxe04AFi9+7wxQOc",
	"k7cIRRchef8d/E6sNdy6DcCbcMk2BHt5+7ciKleqqHP/26kCzJb7vc8fADANUuiwuYYc25G+iJt+hVB0",
	"vZb5Fc12UyY4zXbnlGeFRM1aUV5e2KUX/qcicCd8XoUmh1w8q6aRLAc4ZFuem1aAI7mRwUuYD7pdhryi",
	"+BzgGstv6FuPqmPvps3IdyK/FiTxGkpG9gF0LJ2SF0xw818DoVeU2/j+YZyKG7PXwdfbQhAHyoEGR6SW",
	"Xb6migWCUfWASNRyDDR2DHMUeT+NHUGFYCnTlGcY05cLRqghCtohZFJICTySBo8iy12ba3dSEl0fKLDD",
	"gFZHsepUDaNXAOND5nmW5deGxfuuIvRmdJ8bIu8Us8GyBtygi0wNJ1E684AmkYliFVDVUaXPJBUKgcdj",
	"amnTjmi+Yrjtcq267MtSZCMNkOytNSsRuV6iprW8HIZf3DFjhRk3ZchrJG8GKfNm2HaEIwkxMHJHRS/y",
	"QtsVl8sL+05dAHVMv2GCIVsT3v3McX6zRdkSaXAdGtdUwUOBHufFGqf12aAvPg+yQZJRFZTryOMLydn8",
	"CcEWFafl5nykBu10oDztRo3Iz3aUaQhtyk1UZ9hJH/pDt2r7nAJi5XNyJo1s+Ypmik2JjcDxdeLm+2Q6",
	"gQZejNGwkKLG6uxYjV/d0I2fy5n8XUaSVljVfoU53BeevN044j6ZTs6O33zPJLBVGHHkPiDZhz0bmt9u",
	"CipqfpGx5h+OSB1TqaDp6UYk8I/vDWtvWqC69VAcy3whmTKH/85IfDYIeM0S1/RNkWm+ztjRtWBSwbqu",
	"eMJeMCPscWVEKdNp2EG8FDLPshUT2rIQ3n5b3+rbjXIh3hDRNiUsoy1KIEdb1Jdzwta54jqXmyDoDcSj",
	"H1rn438sz+pVxph2pwB/hE4NT8M7O/zBP0H8Zeg5IprP+aLpmDHMQvMN14HuvTb98h3EzDk3yL5wg1m/",
	"1Xod6gYwWBfuVN7kwhx0Ox9H/c1dYbP+fDaVOicntlM/t+6PHgy87s4h094J7lLm4uWHtcGl4CtpvhNW",
	"NnARF+a5MmOnRQaKKr5ianYuzCZtC67Iz38h9v9/3iM75A0XRmDfIz//5WeyskLw052//X1Gdsi3eSFb",
	"n55/Zj69oBsDtDe50Mt6i2c7nz0zLYKfnj33Ov/A2GVz9C9m5+IUPX5ZSsxBUp2bReyYhnulnG4EDlTO",
	"WVdpMwwXZGmWXI7HrpjcwG9PzLw/7/y8R06oWFS9nu58+TMA7tlzsv/GnP2XZP8Ntp7+vEdAPekaP5s+",
	"e25bKw2M/7PneklWAEPss/vzHjnVbF0ta9f1wcU0e5yiU0N9L19WIDHv8pdel3PxEvNrGMiRpztfTp99",
	"sfP8M3ukQXbkAELckLAcinnepQFqckSgIEMtd0owVo44dxVcdCQQtC7he4NwgcgIsjEwj/Vg5hYTgwtv",
	"Lw5/r1sI18uN4gnNvPFGvf5oBByNgLsVAzJcQrF9bmDeex+9x61UL6G4/G3zYbHVBUvTrlDwRmoWyMpo",
	"O5VOL3muE8wIEQ4GF/EUk5Wo7LuU9eeCoekm4plmXXbmpMxzpsj1kidLUENBTzI45Qzk+ArQ97flLK4N",
	"cVJ6LK9SW5wehkvhZEkfp/GMLZVsapuUWUXQuay+rpslcHG43aOGKxN8mPPyADqthPQSBaddec/al6Ce",
	"wSL0BCts4JBqCfk2GqlsAklB6neK23e/E3f9pxn1O45Mg9ajluzrLjQg3SlRIvqQOFRRaIgB8sDTHlYq",
	"D4SXDTkLuCgykTLJ0ijPcGIbOC4hOm6f1r8+T+cmVZ5F2SH72eeKrGYHfk5yIVhilSDlYYec1ECyOHwR",
	"pk72Mzl84evIGjOEEQN7vvHeuQa+l4xpOYt7VRy9gyTLaB76qpbQMqECnnaF2nxwnqMZ/wX1qGXiUiZX",
	"XNBsWq4Z3fdMtylhOokdF02rxMMN1GzsauoBMH6UvpAfSstnd41MMnUoldZVA36m3oYmn8oFplvuf+P9",
	"pZxBv7BqH4cctiVvnDZtL419eFmUmaG1tRXTyzytXylfX/dOMNBOgTYu0bncnDBVW1+X1qtrxd7IXc3q",
	"s5ZQODSPo+R6c7BkyWWMIMXbNm9vnWRx14MkpgtZM2luBPos3PAN2Am+AZV41pwTV3QL0h/f/M1of3Sk",
	"HpX3FsCssM4lononlFNV+ArhUh+5DR6GNlDN1NXGX0O8Xbm6eJNq3W2wRg0IljmJoWjr7q4b6gaYBfL1",
	"6M3NkQYczLZlcSr0BvamWnQPc2Nal7Bqv498ZdjD1drtvTH4FfSsGNdhlrob3SqbthOPyPHber26DZxv",
	"fDHbixl8NaMPgKf5L/E7fD1vdBUb1yKypdjN6rnD7etbXbvXVOlTxkTs0XDfmw8FoJoyH7SPhTR6/7Lo",
	"RG07tOU/0OzKhHN7MeIib/g7daByA3/KBcQx6DWfs2STZOzbPL90iOMw4Gs2z6VvaNmfaya9v7HBCTPS",
	"vdei+mEbzKgtpTV1oE1zNdFh/AXGxvHW3AbOjcSezPW+A4GxqcutBr8rbqGx15sxCqFBYoTIL3UQglib",
	"I0BrqaUGdRNe/ZctSVJj1U2i0vhcW0Xge2hpPc3q5CnoiF99q3vd4+9j2odP72PvncQgdZm1vIzu8781",
	"9/npxCoFh52g47ruzu8+5LzwgmkoJ/ICPcPaen1UKfZb4rEdaJZqofpkXch1rhCBHe3tWkkwrTUYVrlY",
	"gO9Gx2WZm+8u9nhJNVpkG4zoUH/jBtw9SLQWNBTcJ0zl2VUHuF2sOjQPQxz3WCZPoIrkpjF5LIosI3xO",
	"RI6/QAIy86N59p0GLGD1faADdnsPHvBasiueF+rNNgdtz9j1zTbWAJ/e8MDBSJBnRdwt7Vubyj3JxTzj",
	"iQbGWtqN+QBADwHYDSTvdv+Cfb1gkXoPnSjXWFsc5Y5UOJDG/+oVxgM1K2jHyNFpqRqO6qNWQd/Ts9og",
	"mKEdrWpyWLUwHLdzUzdhlo9OB2/h+7oxwG0j/GabLy/4IhrCksK35ljoK0LUkj7/2xd79OlsNnsyFDT1",
	"STsABZdtydcHSyoWn4ayN9cQvPKCXXdQOcGuLV1DeldSN1sPYRhxc6ShYyLXJDybyAUbMlX84sZPqnRV",
	"3AqxS2ayT01nixb1cxr1dTiVU8rV5W36V5WLbjZCM6hiXUzKQe3qhoK2G8dVzZEQgV1H6qpawg9UWuHr",
	"QHLNE5oFijVsIyPWF+rXgmh/rSYPffUWFPrsFhn65vtll9+h5EkZpBd2PZuDj/mEio1146xrifxMIO+b",
	"9fYgRs/73Ao1ccF5UNjSLKdMfVKmq4cpiEtNYkS93Vza6D/364zsa5IxaqixYFVjV2PNprpJa1Wwfm2s",
	"fm/Cqup8X61lnhZgLp1qzuRXcwkFCFMvLZS9g/VNhvwE3HJwl1Crq5atxEv3YqGAKjxu94nRLdbkZCuk",
	"rqjhD/2ImDpIVJWqtgzbMHj5FU72bGp1P+slVew/vjpmIuUimtG2Aam73SMMPmyPdWTw9njJNs/Q5vxs",
	"esk2z/8D/3ge3tDHLqICl0Ktc4FBSp23olUGDbqhKAzbxIicUrr3kA+hkFpBcLL32ce2j0O9RdxJqASu",
	"YZWvmWTEZuSZF1m2sQBPQ15CLXeH2pRx4tvFfTaLMnf4fHpFYQYVhrpBasxojcKWYJCU5WjCC8HvN1hD",
	"0Nc+NL3qT7xFE82vKq8O686wrerIOasEA8jrOsit3RQgpGzgOqwYY6WySHXBfbO02gNuvfvrCamHw6Dh",
	"3x+stQBFfiOlte1HZ2FRjciERpyDkQqPsbCp6sothWoMWwK1vpkWtbUJ9+w6CsFRITK1ZSJlVYYB0ptP",
	"CSZmWrIs21F6k2FFBjcZrB9mpwvKhdIuojPbkCynKcMpYE0r+uE1Ewu9nOw9/9sXtZKtPz7d+Tvd+WV/",
	"53/2zs93fpqdw//9eH7+/j/Oz3fOz/9yfv6P9399/L+HtXvyj8fn57MfsWHo83/FU/11FX1DVeOwMn9e",
	"tJDtUaZvjtHFTp+SthdJ2FCjvMJtlngS23dFwQzOM/QBTXRBsyrw9ra01krUPsn1meUtKEzbnThwy2jb",
	"z3Dr0Rt+msPDy8tTwCyT4F7rfDYNJIORzTSkcrphSLn/4gwi2ZUTJXhVWHv1jXwPnLvE3diYyeO3R2cv",
	"99AOUEahcEVErolkupCilo7hyUCjtBGqFvnOv1QudvhC5NKK5mbxziR2IxPllm9U2af2Sm0r825tHmhh",
	"NhJ8Fyo0YICqfdeb5m5/7T3Z+t7jZOk7wXX8xltDzzaEN414uHjXvAaZOlmZhKmMf5T+XSrvJOBHtd7q",
	"5HzU6+CPb+w87t22JZXpNWRRFi7kzsgTuFdSszjevVO5XYNLYnAXbuUB0NzMV2CrMp1hD6UjiIINV+T0",
	"fT6OcyNPpUfzec2Faf+acg3BztavGiPhwWBwTAu1pRtBbUPe0lrfvNUGvtYVQLVPbT+W2ufaNgPfm44N",
	"tY8hYASaNeFTHWeNrA2LgDxypdDtbfByXLEP61xV7w2U5J2di5c0WULmoiSXEiT1FJNzVGIEXgvrW5DQ",
	"Nb3gGdeb2bnoj6XETdRuVZJnGdg7K9t4lD0zi4w6XZj3eB8qC1s/i+Al9M3dkTG8Fob/wWBeC6dWpGc1",
	"skGdUMjB13muyeGLbYbCUNUhT1grOvYjVAVAIojQDu/yqKSUp45SDlxe0wrvA7SEQnsV0/rxxelWS5Lo",
	"8b9fQ0swy6yooItKm2Q9JtSUcJFkRWq+QJFp+7tzqblgJM2vhZXiXP09jsqghq3ItjvFSPVexgo3U7Yu",
	"H/eb9v/YA7b0RsZBXNOdutH5z6NNz32Hz2Ntszd7HttDbOFIVwGs9KJbn+UvKKTyOir00dz+2/OevIlV",
	"pLZIb4rAV3/WYOeGG2f9a8vw4YuaPWyZU6y6ACcwHJYCDVy4OUNvhqoOAtj/OyXwCpNjj92AbEllYbtf",
	"W2/RPrmQjF6aG925k4sNOffXdT5pu4RWyKWaPO1vYPF2Td0L17mmWcQ4aD55Qb2hmQZmr7LU77cEHSu9",
	"dEGnGUgGoJoGkLV5/o0NB6kRV5e9WWG2TsQy/Y1lkgk+4ElVUNMOAG83V5eYOLNNHtbROsQpl2Du2pTF",
	"iJ3+2/preGN272UdLm37Hs9KFjDr10VqwxMbKsxGi3rhBXbFMlt1Pb9mqVmWbY1kUmIyJsIBT9c2I1Mb",
	"DFBI+etNXEmBJsBLtgHm3YaFEehmQFz6NlXzX8Bya3oMT2v9+Mf9nf+hO7883fn7+x93yn//tDt7/5cn",
	"//A+DtA3g3r8nSirzkeqf2AZDo/quDPy6tW7S50WgDkWfKCB76jiAV/3e6ZvFB+Zk0K05y3Pcav5gzxc",
	"nlwyuV8gem9hTsWO1l7RqElqjvno4JBItuDmNIJu7IVeDslXcZTwfdf043Sypkpd5zJi+3FfCdi6Lxku",
	"xS5j01hm7eUoxw2m4I0lvT2zyW6FtYl3TdUjzbg9etN5uw0S8KIrH6RDpDIZtsOZMkMFBrTrnBioZ0yz",
	"GQGCVpaQLYUUl2QYfF0pgWRx/MrGmjFpc4CiCEdRLV0IrmekyklV/ggJYffIzwrTOylM5z0lP6/wB8zY",
	"ZH5Y4g+QmwrwxyML/9j78dnO39+fn6d/efKP8/P0R7VahmnAS5HkRgAbElHNbFt8kyAgHog41bQRKlGr",
	"BZxRLowECkmzBycPxKmObWf399d2kI9+DsGD0hLRyIpettixuv6+21SNeWo7NBExMGYI+VoJDtuwbTXp",
	"KEtjUysbbMQFdBrLxgCYMRnVnzAZVetCbZeXqt39bivQRPKhhoS7aNMqqXVYu1MSCs/aSyqSFU/rQV1i",
	"1Y4E79de1itHnZZUkQvGBHEDhJNcoZdcl2DZo6Ded9n7cSRQfa/X2caRlmimv9bh2X1udUKeXDxI9Isf",
	"dVvm6pm078Q9b4vbnv1+JFQAeBOqbaIw//Svqaod/LCsA67H15v++pm27QBR1xt16m9pQM74viO4gctL",
	"APDlAc2CuBYOfw02q0fCtpqMLMEnj4kNnskgR4Q24zgGyv5R60yFGZZ+GgA+yhydk8uGSH1abR8pF/YG",
	"bmCBKBwViTsKVTXyC7QozJjuvyuBR7zuVzg8L+h0ApaPk75UeWfwHHWmywOUtdnAZv9SuSCPc2uA7wgY",
	"uFNuxdWZcC5nUPnZY2C4Kp3UlkwQc4e8B4SrEHsV4XDMeQ5DtohFMtJwu1dw0KNUsb83YqY8p8m+YkA+",
	"LrcrAs22rvPTrhnDbkHz76xyT1t90XG6tkkXg7nMr60CzJBguPVYpYa8yvhiqcmBIcl55iOrl7mnrdGs",
	"VH5ba2JAB/tx6itgCr7jXqHwsb87ee1O591hdQvB4YEUCp3f19K9Yv99QgyKAPeRcXGJCdZhPvd2djiH",
	"3FTFFNM0NeBVTRCFwSCUcLrsHrQwzeo1uuwb39Bl+0iDFZRvgBo49I53JXfCeTwPoKFXtuMF1bRapn/N",
	"QSsJpJ+6pZvxyZxnqIs+e30avvi4mEu26VzEd2yz1eSXbNM3d/OyR6DSXuKggx9OEgZQBpeQ1VyL/IaH",
	"7u3LIFUuuY6CvGq775rGoe9zKeXIpFZiM3aBQ0HYyAmbVxiIR5pKpkpPnd6Nk8eOqV3mShvZdm+dSz0g",
	"rL4DQOVigydvuN/AMV+hMOrpmK3PB7vCQAKqSZ5A1ECZvhwdFAPEPBxL2RTfodIhmDEQFkiCJV8sgF8D",
	"OcJMjqYVlFeAN4K4VzbnH9Bqwjhonsxwe+QxmD3A2cn8oJ54M9ivtND5CsooujCnMKc3CsZ3LRinVTaH",
	"zlfQjOgyP0BAyBWkKEGt7zDd8AmbM8kE5pIaReI7FYkjFfz28d5ViX0bAmgzr7CB49pW27tDa0C81p5a",
	"5lJPyYomSy5YtU57/EB/6pllGlX5kBx55kvnxnOApVq9Cl4HthhrmarTfXhXxl3Uf2k1dHl2Gr/4Y7ZD",
	"VCM/N3ocHL9rJVw4OH7XTNFwcPzurXnaq0ZvIINFqy/+3OyOvzZGeMHVZau/+bHZ2/zW6OvFxtXjAbwP",
	"rTAC71szQcULriyr4idTDQQUNPz7mz+XuaG8D41RDyDHgm55g9rf236gZYegB2h5nlvV0XOycQMbIpnM",
	"unOAdRSYM78ciiv726F9pM6ouiwn9n88ZnJFBcTkencgUlTP/XwoaP2DpfZp1aS6aO0CetXy/Hp61S32",
	"fz3VVLZ/LZdaG8A6gzR//5rqZPmCqzUm+Gp8tVBjmYN7q6s/rl8i8MBccO2d2KCqgy3YVZ+ChQjNj1ws",
	"WgSqVqSw+WPZGiMJTpjSuYzkUsKeg7iCU2xaqkK6nCI9BvIIa4siPZkSS2t8Sl6SGkeH3vfblLo1u3Wm",
	"JVA+1U5Q7n9qGeco2+4lwwpw7ztlPWDLZk2rSsNplXXG8vObNUhdtZxYGNS/XtvkCJ3UoVNP252lsYew",
	"bDFyMyFhLItYTxhsJOdY50WMjBjv0TGqRxmGDlt1CY+71UJ71tigTwMGrPcIj2oJxIDRsGV4FEecBwxj",
	"m1bjBF6maGHRZsvwKO2nbMCArU7V2F3PWtSxPNrFH7f2hnRjSrBxe6zeddWaedKdi6p/C16ifvK5j9OB",
	"tWajgw+Kgo9c/2G9u0ndTcZoErX+qrcx5NymZxQLh5aUDaJHf+debO0bouOKb9N1u013Us9tOkeI+dZD",
	"3GoRYXL98f1WWSGBB4n4qbhPDd+UK9CcjA4pn9whpTyIYV4ooEIePU/+sJ4nnqAVFLDKVaDKDK4Z5Ac0",
	"EmVbWdaw7LjO/QaCLefpMZiU84b2/IpnTuUS2zN8RAeGOQ/VL0m6+kOgA9HsgyaP35292vkSDBMY9lDZ",
	"pqpJIN7RThNyPzDtXNxDv1XZC+MIRjKZ7ccLJJqvZUnESGBbJNs7z9gjhTFsUy8UxppsICLGJdoWxYpJ",
	"npDDFzPyAsNEgfCeT2Se6/NJ+JbkKeuces2k1YES03ZG/k9eAPHAxWDahJW56nO64hmnkuSJppnzZcgY",
	"haiWX5jMXVLOp198/jkcH0U3q4SvbAcsmxjq8/nzp08M9dIFT3cV0wvzH82Tyw25sIE9pKzLNCOHc8gw",
	"VUJsilkT6puBK2D2qUjqAcwsL1w3t1DRtPwILcgiffcHZbNd2R/fuRitKCoeObOAX3cpKbVzNom2l8Ro",
	"WNxQbWhP2ef/fFKOXfvZSTfv7Qq3i/b1qUsvY+Zfxb7G+xeQVZ8dU/B/+bUdE1sSi0h0LPCBgStv8wH4",
	"9mDmp7sd2bYxtGgMLapEqe3CibDL3YYQwZhhAaz8VBfAsEzJeJM/uQBWHcQgAQxp9iiA/VEFsH7tTiua",
	"+QIq9ARZO/gE3Gk910+V9+Bhqip1GFNCRsG5VaAHhcQywQO2aiaKgS0PTG5j88kfM5kYKhUrD2SbGRbc",
	"tnNS2g0mmxdZ38aqlrfZnGartaGZnRESvsh9Vu/g3KK5smhkKLr1eAbP/jyIP5qvWHpU6L5NQjsY6DZ7",
	"vHEOpOGzdFW2asJ4ai9jCLWmZRoiDxNKXPcAN4gstPXGfwi64JlDQ4Thk+D0TRCg7wz7qfq9w7ubBN8h",
	"pGu4ZSDu8qZAlpBbArwP0GH7xsNDu2FID756pvnbaL4cH9gI0jJuxYaIGaxmkEuZuQytQfje3el2TA0l",
	"cUTKtj3gCgrbH3bdkPfwh2wN/w96nywXdP83qWFgfXjoOn+PEHilayKpZotA/gA7hhGDoEXpBVU5gUF2",
	"6q/v/fWpPzm3fm+aOx9wjMHoznab7QI7WxxEw0CCkZFf9/EklmGrSrUgWcEK4w2AdSZoqzQz4a12xErD",
	"Vnrjo+1Wh9VcOak1hpiiquxYp4RZq1HmIWHkktmvjWqo7dSfjWST96Yg8wprtTL+hrVZzdydbr9RxO7E",
	"6Buj8uDaNNB6ShgYTmiWbQivpA3vaizpFQPDDoSm4RsJ+eYEXbBaYBgXhJLrZczQuF30cXnity/skrYS",
	"DW9TDLwkVYNUXHVqtWW48zdMMMmTE7bOS2NNV4bGdSCGv895CYd2vmqFjIihj9c5eFtvoPyrZk8gbzt6",
	"Ow2rL2yGtm2Ce+U6UImt9TovuD4x2wmnSbCeWBiy+Q3X9RpkBGMKt8nu6nK6upLTfOEoUOXsFeRMK+j0",
	"P6/VUKXqMsztAh0/YVe8K1UEfjWLLlyxw971tgoNlotvzTqN5amdTsQgnr9RqK9/NTYXpj35CO58W1wc",
	"Ci1zQ70gL3LwxYw0rMwAkDOU+99JoczDjT3J/vEheXx8dHpGdv3CNbu/opb4J55+3IVBnngVM4/2C718",
	"7uO1VSofYtJ//OOUJZJhOsSvqeIJgQh18/3dyWtAxDbixgMI6ntoMokLrpfFRZA5LCmATXI9cXpruuYz",
	"7DdL8tVkGpjUA9IFVZCeoG5eD48Fe8a+5s8puSg0SaggF4xgRQqwglStyEuhmVxLrpjV5fdjUZTwfJvn",
	"l/uJs9RXxvBGRYJ5Z7ky4IhdQduVPcZ6ltULRtgHlhQak5wMesbM2jqfMs1XLI8pKX/TKWDJI/WongH2",
	"0epRPQOswf1Hy0e3zwL7MZQZfJhbdoUdJ4WYfHwPDgf1HwNpWa++p/I2+XVeVrWOyRWVHEI8L9lmB81e",
	"a8olFBf5F+ooXBroQhgYB7Psy0JEHeFWBtB1DPUrl1CxIVQuihWwnUgOlaYipTLFqpVEbYSmHwzy8LLU",
	"MZ67IivrGe5mUmTN16BYWUC6xanBKA5vwwbL47pFkEKkTBJqiMmS7CToW/YhrNe9zuXlCx5xDTIfMcW7",
	"S9aO24UUv5gBvRDCGRHtQge8k4WIkpTq2u5tg2tlt2Oql0frXu+ZWp+XH4x0gGVee9flNW5byAVh5WeP",
	"uDGDf1BSJSdaFswcXcnDhmmezQHP0uCphbbcuk95xDOvjLx+rJ4QMz+4kVENXoksy6/R4QxYOLMFRTVX",
	"1l0Ofi2XPtxsXfPsChDkOCtJrZ9TyVOiDyYB/VGJliWoQcxKMJzjlmAO1RmYGqgGcUTrdZVveouE8Ac1",
	"Vtss8tuzs2MsvmMoQUAGpLNEBt4uzIFNnEepzHNNDvaD+DMwHbxNmYGmosC6BqWBV5d8jdzG90yWVSQC",
	"6VQu+dpKSVbiIFdeh3ACWZ2pQcA4e32KaX6cH+ugpZvRL9lm+OiXbDN8cMPvxoyXLgf/raG/RRL+rrkG",
	"1JqvbkC3KGqY2YGyqMCVDJNGDVU4DpIR86uTP1GJ8UghEbF19nTuJbF1ntjNEq+wFMUMXlb83bXkWjNx",
	"a1lWtmVZJ4pSZTPuiIR0SLlYFDu0eVl6lRuJCEhlkq8MyZ9rm7a5EjsOUYRANoaRfxcMSrRIumIa/LWK",
	"ZEmo2iPnk11DEXd1vuv8fv4Brb+C1kGn7S55uTy+hxeRHUbG6PoNFUnL2pPQyY1ULb3w9jtRQAHWwrnn",
	"JKFZZt7NJMsFqjiCmAT5EbBKUgSnzHiIb8gK5iLDgn6uq2F/0WnGKoGqowYBXyqygvxYBsEdZiIDDHIS",
	"vF121Y7fvNi4A7budsSchWGqYSVMWT4a8kQtWbZGWqYxgZTdUVmaVut16a+2lRJu6p9rCGMOV3Thpx5p",
	"UsNhfuPeAN/nWbFitWHa9aL4Kui/dOLTU1CqHBwSaAtBDFLzOU08sdurkb6myWW4ANN0AiJKgNbkUhOb",
	"RmC4T6MPq1wGvRsHl6j2xjop+zRPE2EVTAAePs03eSF04BhaAMA2qD2sIL0y3Q076kV1RDRT5TF2Bu+a",
	"RjhVlRQDJunriZ1gOxGouIGisDgusqwyelX6rsP521wfo5WlpeVyhW3raq1Hfp9HM/KDkSgV0/BtP7um",
	"G/UIo18QjlyRdQGGQPMKb0Az0uj11nypdQKpgGaS0XRD2AdwuxWR+sk452Ta3AyMOjDSxMCnHMf80RjL",
	"/GTHcyANY5bI4TjrZdvgaD7eFdYMvBe1ZcaiA1/UsmdZFgZ9vo8ODndAU8ap0G3qEzAs1HCsd1MeSsKO",
	"XPq3bmrYvzC0xLnaVPZ5WdGNeZLKFJNMeh1FjpUwrK+DIQFuMNDXZLl5GRWxJpZcrlSbMCu/2t4QLsrt",
	"N3hyUHf74Z8jLPcdyMTmIhD8p8ay3Dd5MarYqu4MyXZBA4k+NB4izPTvE7UrhvuCqLM28RmsQHFxJs3H",
	"8X6Z4yjgQllUHtY7KJDFJWSaYVLm8k0sdaGZHVoQm5zJ5QF0as055Vkhw3xQLvmCC5qVqVUHBc9LpuXm",
	"wL3X9eW8rXlIIzHVVF1WFXVMb15TWA3yVa5BobnyvtONpgh5+INuJ9q5hzNfu0l+K6d/TZU7eHLB5rlk",
	"1jNqReUlajrXFWCsV+AtUcRb6BB8+ee1HmBKDrUaYEf+5w9nvhQHkt0/f/juNJROPuXh1//lhzXafVwT",
	"kmSUr2yYmFMQ/fOHs1AMdjHAKl2j5r1VVblSRSgmu1wmNvAXeYs14mBBNP7X9aV6F9MfGCCTx/88PXpL",
	"fmAX5Du2IadMP6livUByz2VVMnxdXGQ8KYvZ2lODRUONBaoLGYmVu6ld/l/Xuj9pn5Xe3W5DKPzdl6pb",
	"vms08FLGUvJdccGkYJqp3aM1E6dLPtflc1vXYQbjLqNHUIY8VjOAr0DYfQgS+60zugm7kn/byNOLbUmp",
	"BAbqF+cRDMxNx7Qm/GlZtOwaP5RV4bgi332pKlBwRewgYZ1+LhdU8F8AUvvKoMxqAH01KH8U7onyEkze",
	"/zA16hj4sHDodvmlCnshX9DkrQoPf/L1/gFAWa1pgqCuUjqEb4PMM7bd/k/qPewYMS2eE8qdKk/nECW6",
	"RvXFQVYozaQZEteNBl8ByTL5L9Yr134DpR7ai8BuvSNZxqgy7+o6yzdoAr9eMsn8cZV1inRQqdJY4oQ2",
	"f8YcUuknOtuh6YqLnfPi6dPPkrIX/MkG5M2v4cDUXbkovrUOIEgxyiuJfkjd0sJdcerTiYLZhrr0eYQD",
	"O/7WMrkUQt/QdFOrP4ib88wzVvMWnHXYYVTwCg4AGBgfBS97/1C/wewsAVGw2rB/Zr0u3LZ3hbKhiwSO",
	"7uEUBpUsnXKluUi0rZ81tSSF0WRJDONlnha0imrkic8nl2zzFfBO55PZuTBE/ANdrTOGNZtLd6Gv1jJP",
	"i8RW1JFswXPxVaF2GFV65xmEZzL51QVNLpkAiWM4n1d34Q/tDor/u4gAm6cBfkPrW34F3jw2CUuVbYDg",
	"TVdFBh9WVCfL11hYDLMi6GRZeaug99j+2xcsnZGXq7Xe7IoiyxqzK+xmOMulTZPcCBVojNr3LL1ptjf3",
	"vVrprYqprejabPzXS7aZwhl/RBevcDG0Nsq56P1gcgbzxePvXIiEdYnZCL1kmifVcVTuJ74TmMFcPI4r",
	"KnleqDLSAJahZmS/Mviu6AZfRLCn5Zi4+tcq6GJK3MI+hlOQcVEEiNEb1Fga/OFe+RXzNyUZX/FSI16F",
	"SwN6lyZw9CnkZcXfWt06JkE3AYm0AEL0ivLM8Hd+9Rao+ED/XbAyY4ez6+kchZNSe+rqolrFqJdVgmKQ",
	"BIROcIVkAQINjWB8hZZEwT5od1fKlVTgPkAwgYXSvLSKK7D2w1hmWTYxhfXbZw5kdqd1VwSzb+drZFgf",
	"AwK9pIJQMmfXziMTz3RNlTJXz15aOHEXGIaWz9LhABgtlHthn+5oG4VweIp8auYgVZMR51xC6XjImsem",
	"pBAZU4ps8gLXI1nCeAlK63EClalEXTcS8W1YUS64WBxqtoooM5pZDS6UOVihLXLZdQLg8Qk3BMqA3zof",
	"2GJD7qDdVkDyLXs6ZHHa+NQSNEiPBg6VjrKBUaiJ5+U+3KIUKQRUmAQ8RUCaYRzQMzbXpBBweURK8hXX",
	"niupYpIb7hilvNpCvcBn8ti+3hcsoYVihMNnCA5aFgJcLvPqK4DAVpnKqLKNnlT7kcyCDjGwuSfcSOlh",
	"eqOduNQveZaCTEcFuXo2e/Y3kuaohWDamwOx3Mitwhyj2UTp59LEG7OzvzCl+Qr8Bv6Ct43/YsOrkjzL",
	"UOqfESywVuYMMvNKBpQyNja6DwA1kKWrrjU5Dcn80HozGs9Zm8UPuoudwckZtLxkG5962icfbCGg/wrr",
	"GcFzMlZXq3TnrIqfAwGBV7ZR6uDQcDdvcw3/ffnBPE6T6eRFztTbXMPfQcEWNWSRfVnezGrRdI4Tb6ML",
	"a/CLBoTept+3wa66mERkYCo/3OGOCM3DNawKF4fY9Vmbs8MqN87P4E0uuM4DdrUGA4XN+hURvh+Y7dQv",
	"4/qjvw+57w/J5+3vBBz3B/s/vKUrlpIr9IIAEaGt+ArYta3huWXXvrVPQ9yXAVWkNVV0QEPSblRLfRbS",
	"V7f221VnwwYURXYWi8+agsIz0imohp9O5Dz5X1988Tx69Pi53bOdpV9vl58/PnB3x9jm+/oF9/8xjgLd",
	"CB3QpHs6X2E17cPVvFiuEV/VqMLXDlprXFO4d9QnPUw7x7RZ2Q5fdAyBmqwhw8Q0GtPJteSaHYlsg8rh",
	"36ZWunl4fYpp3qQWnbHyAQLTYfXxgGvtPsjezzmT5HHhtKuNb2WxXSRFkWqWv3mFem7aPI9l9ri1Elwl",
	"+Zp15GC0cMdmKFC2C3X36nngBPruNL4YvXfZCOhczPO+4Vy7YSOa63SQUb6qXZMfJ2tQF0uW/lRGC7xv",
	"XhywAPph3WXoANonrTRXLshJa6ChFASgZGANQyi2QJOA1fD/eB5Yw/nkPXwxXH3m/lDFxfnk/ZNbcJdN",
	"K0CTInsHWT8Hj8I2KOXtTAhHhy8Oeh6hRovGE3T44mDwA9TzSJihbv1EeIP83h+IGmh7n4cu0m5GssT7",
	"3clrh/hlYHeSGE5VzRZ5vsjYLMlXv1dSztPk0xFyA+VbkvEHIpT//OHMPga/cQJpsfreqF+VUqhN98pv",
	"5u7VNfA0y8iaSVDfpmEtPCoVrTJRQQ+rBsb64NgW3TIDrLoQOWauvo2RomoMWigbSubVvm8BJLHVg8/4",
	"iilNVxGjLGQFMGPZPM3XVNmtpDXlVko12zGNw0k9sarwtnNZDWKKZYqHz7dgwqvu0KrRDOrhpFTP1rJU",
	"09ItmlSjOK1iypTBXpuqixzn6yKDKu8O3litnpwwmu7kItsMzC+b3dZG9QYtVDb5NrhEoS0IdWUQiocJ",
	"O5wpxN4lNJMkVLOF4U4YeQxkDX5FteGT0qYxuXHAnE3GHnxorgULWiu9LOFUk/wasnhgfR74fWoo3Dkk",
	"vd5FKmVNshE7Qs0SEgypt3Yjv1R3KRspzzjzSHnZ4a1lpZZ0flgca7OIfBAGNfcKP/tQQxs8ZmW/u6zs",
	"w3C6PJu089hrCmdM0O7e8zZGJNzwIwFMqPNDhhE9Ojh0ESMcvRy79H9pnlyaaxZJoQZfYeq2Gs7wYtuV",
	"yvSH69jm1mxgeNuOIbRbDLGERwkfHFrb4AwODr34Gxeh046caTzpEJL6pqwb5ULXzLPQClnDGtpVsSXE",
	"LZxoj5xDJ6RtRLpnhTxeF1n2ZGo//2BkHL8NCD3YCCj5ulDLJz6w7ErKzkGw3UH+h7zC6E4dlm32EV1i",
	"zNYj4k11/BuyzJU2d2lKXv33i7dTkktyeExomkoDUHDdzp3r4TqX2jG5/y7oZsbzaRVxJVm6pBp+W23K",
	"X5N8tfe3p0+fTsmzvz+fPfviy9mz2TP7y497e8/ew7/D8hPsjAUydbXOH2KcoTWcX4J1/YE05zVk8M/P",
	"DGUjhMMuovebDGPrwPFWKJk95I6Eg6Vvc4/OItSsobgovaRBmzUq0ft1JAk6zx6YBzbPjjMqWBwAJXht",
	"L6CYMs/I2vT7PbmPB/zpb6WMuSc9+1rm5paAZ9srnunQ/IdzP2IDHg3bTbl8BVxZZwEnZ4GbUsqkcx9q",
	"OAxW7q7O9Qf4bfLokm0eGer7qHSCfAQ+KTCraXjJNhBUjUAFN69yOW411HpbkseSLahMwYvI2fufVM5I",
	"1mfHRsni2ShLu3bM8skcQGIo6By8W7TBSZuAiYpIWpO7VU6tmVAGj6Iaqj+tr/zvz0rSpbYKPlyelqrt",
	"tzMWPhtLGP4pSxj61yKYp72zllnfRQt79Ddb1GsT+l/HEoWfvkRh6zwGOdPVyO1YsPCPWrCwRT46L3tb",
	"CPRtR+273i+LkFIWARlELfNrl8RdhmHFPuD1DAl5L+03cvii1JE3FjhAg3xMdbI8QfyBJCHuvmyRPK43",
	"eavZpGWefRaXplgme51hnBYWzIbSMRHn3nDq1X0ChszjHKhZma0q7BocXipeXZ0TmkJ4hF3UrIV8+bor",
	"PX6TcHSVa6y+OYd5S0asSFSjI149R2wV3OBxGaUbApJXlh0eHDBV2ZTe5VEpkotOM0HVMk6FA6Nanv98",
	"smD6fGL+YZ5Q/BfaAvHfSLPw31BeD/+J5jv891+smhKMpOUMT7bj7d0GYzGpllqXy7YFRXAFUKhEtVdT",
	"Pl1PhqRCsguY+iANIVV1qmEOpYR6GUHkRWvj2oDEBHJXVe3iw/qDVVN4DgODn1kPPXsN+97KQjApTV5p",
	"VfTCFr9/2HQvHQsJC+43S7QKuo1rqso3fbtaXN6sYWhmVPOrSEraE7+8vrRNMbA5nBgwRqXbfV04jDN6",
	"v821NdZSYTPgAUU07Z32Jr9i0ktlW8bITpRMdrlI2YfZv9Swx6+mYA7tu/zqSLTDkUae0HrdDatVn4Dt",
	"IogFJx1YUCsV40H+G659jIAUbpgy1c8NOsofo6Zg1BTsVpfIRYaosvTawH7hcl49wkekUJx/48OPeP17",
	"XclQfrPm6vGOf1Idg2wcxyDex6P4o4Lhj6pgaFCdjkveyshVD9avsxbDXGaalQR7y8r42eL7Gp+q5eC2",
	"vqvMxx4wRephNltsVxSzDr1bFqWsD3bbypTbFYd0Qa77GZP6pMhYSKjxdtBmuZcNG3i9fiykUTdjh43r",
	"Rcz/9YXDU8cV8xXy5V5+I3rFJF0YCdFqOPILmw/D5oSEiblYzMgrOM+97opj/bXEuuqInZ+nf42VDptO",
	"1h1qmjNMsem0L/nc7ggj4yVfLAxRDUESXYMxA9YVk1z3l971z/vUdgp6v5QjesdU20fdR6EXuWqTtT18",
	"7NcWzjih5wcqBfqBHEgOeT4m08mhmOcDE5FH11INHG3izRhtg0vxNv1d8ME9Kd9Q88QQ9sGI+ym54hS2",
	"vX986G/6wOAv+FuwU74wy3R61OnkpZB5lq2Y0NVvWGV2YksBT2pSYLWy041IJtPJWat69n6hl85BKSJU",
	"1kLirU466s95cPwuSsDWRSi+fjp5wdVl1GWTq8twL8w9EM1kEM1M0HYk9VMGDPYljeym7xnrWleP82oE",
	"EuYxjCZAaB9gmIc49f1GkQBic4w8iCtuqXtEQhkpXEQPNCLStJqRI5faCX9dQyImSwm4clreLVjg5msW",
	"4IQVXa0zLhaQRvmKZh2PzwXT14wJt38CXc26H+A9KYtSdtSjjB311D+KwI67iDVQhyjdMl/rSqOa9z9k",
	"6bKpnzDVuy0aUKkZc6zdBB4zlhairWA0cI8KplHB1CZm5sptq2Lyet61kqka+sAm8IrbQzAbXG92d2ym",
	"MHVMWiQuVI0rUqM7iAGzYHCaOWiuv6UqYBcwvzrGElOGQeOwSHI/JpwA1OKZ+nsBBq0UxDYUhvpsD7Au",
	"U44HymntCGvL68MOp4QcqfknViXazhuRbM1HAS8wKhP/uMrExgvTyfY1FIrapmN+rJ6UTB1mzOzUjsVL",
	"G6O1dh6saMxFq27ioWlZtsAaZ1WH6tprygX6+If4TfTrF7lBHdebmzv9kiZLm1q7PhRGWLsBzIJ9prf7",
	"rj5sDVRN5YLpE3bFw/T2zIsVl7ZVANLbFS5tTNrhyRTgUrrx7wZ6Wr//LTW19GaktENTO504heUBvLix",
	"TJklw0KWhpEpHTXMOiLZ3N3A33SkGCgH9zIIBMYekhj0BgrnT+RKU5s8yIEJdn0UjvaHG8quMfs8eczL",
	"qm0XGQaRiCID1yUXwxUI32FXPC9UxwSuyS1msc/cK86ytIMzgNy0Nu3CNZPl81iRgIq2lKhexg7BDsqc",
	"EFZiwP/MXCyW+1tbTWMQ3p3WixpfWt9XELli6RXbhCXSckDxpZNXB8T0NaRBpFSmEMLUWw4JU1h40ZBl",
	"lfEqTKtNom5aA8gluAxBPFodudxZaPPbxR/Z8kJFpLTQSZ5leaFRX43VAMJmoJLdWObXwGZAW1v8Al0P",
	"JY7Vl1zga6qT5alNqhKj1vVGbe2w0pJqttgMVw03RuwAhl9Gtoaq/mdnD7ObJmv81fIM4DUa8BvH0FKk",
	"emd8xfKiN+WU04GiTNw6pk7pIXy4GEwrC9jX10W6YP2LaLaHyu6QiuBsKZla5lk6wCXUWazCHnq42lN3",
	"ssGb4c4dtRU5tzWLEDAWKS33VD8Z/07WUSF0M0/VsiqRvkUCiIOaad+s7PT0W6IlFWqdy1BJWcmvqGbf",
	"sc0xVWq9lFTFDJPld9Rlq+Vx2bfGHpiG17lMJw8d519bUm8eCLtzANDl4C2EEMd3WNgumkH5x9zjE3FP",
	"hfDN9hvunq4sflc5/K5C8NWuQkQuxuFbrp6jKUEXUli1AaSZoFlmOZQ0F4+0a4GVMbyMT6OS6X6VTEmZ",
	"JaZ2dsViwSDjHDgJ28NJqhwx3BV4mZKnhM9dbYSmWPHZ86BKd9Qy3amWKVL9dYgHTyVSIxxdNElEyUFV",
	"2FVoRZMlFyw61fVy05jAHLQVR84nr7D47PnErsdWFOGqKqrDVmu9sUVAoIZIXUdQleLZJyewTJJkVGLq",
	"NOfrbjcLaHxRGMrDsBpJfsWk5CkjEdOB6iZxLoKuBB45gppGe+R8copMzfmE5NLf6b2jjWHvd6hIdyxI",
	"e0l+SNloN27JRIkBFdIFHwQIyEj3E82vmAERiwv7S75Y7mRmU8TsllDTCc8Ukxz6IX8wIKwiy2mKrj1c",
	"lD9jMeDJdOIGgQYpq/25olCuhQobNTg3zCZ+sgVxBrodtXe57xbS/nTirbj99bDaQ/vjK7eryIRuY+3P",
	"L+o7bzd4U4NFaNUedNqf3zl4VWf+EtKh9Jw55kype0rC4c95Vjtwl0OnzKazIwthc25mXFzCJ/yH94Vm",
	"nCo4aYUt8B9eCzMzT1CqdDNwgUriSZm9E34GTptjltcLyFnmsGQ62Q5RPNC8LPcV/XZSLrbd5LXbeuxT",
	"V+d9C532lzcOXrFPXcOeOpC2P72ogNz+eFiBvf3xG+8gAgjmHU3769c03OtdeXwB2Js3xkfn1zlNe5DZ",
	"3OsBqKx0cWGQNacpbEfkemeeF0BkL2i6o5i21xQMsUBh5cJD35vSp3ILp7iC5s+v3YqaH97m+pVdYPPT",
	"1zQ9Ldfb/PjSrr/5+xu3n9aHBt6VHwL05Z3gupI3mlkPS8rUK32FX6hmWtvggxVnqVxeMIMA9ehCyOt1",
	"+q2TfFPKVviK0g+vmVjo5WTv+dPPv4ymEdtmU00S/BGxbpsh6mgPmpmLsn/oClzjEz6FrUOV1SptU/WM",
	"l+CQhRDuNS4B8MXndSc5uvPL052/77z/a9Dr2kwUXg1cPzC3lfHXSi3Tmc1FfT550oj89D72i8UCIjT9",
	"Wetn5AN7WkNJD4ohpqnps9veW71B3VXPTwNMnFJ+FJ9Hj7vR4w56NC7Pdk53zc5363fXGD0c4RloVA/z",
	"bDQYVWef3j8rdCSDHAuaT8HopvVHddMKkaW+u9+K/qy9/dZuFWcBwJAYKcFvPpHrZa6qAdx9n0OgWt6v",
	"RcLxh2y2pL1VBdFOiyEaHV0MzS0jMxFOd+PrY7F6X3dUFaHaC28sgXtNFTrqeJlZhlQY2cYxp1W4J3gO",
	"2zlflRuwuDeD8+Ur9j+5aCQdf51jeF1jDQYmv+SCeVmJlQ2xgdkO99/uu2RW+ycv93dfHx3snx0evZ3a",
	"lLHmxzoPjNXDzUnnkuQJowLfENezzEdsGq+p1DwpMiqJ4uYkuF5y6yVFJaNTkOaslED2V0zyhO6+Zdc/",
	"/Z9cXk7Jy8Lg3+4xldwFOxWCri74osgLRT7bSZZU0kQbqun2qqB6tSrW61xqlpLH55Nv3pxhJqh3ZwdW",
	"MmmRp7P8kgkvy1qocKf165BlvGCoGtpPPI32t/S7Oo1Qnu4POzmS15QtmNhhH7SkO5oukLDkcjXZ86b6",
	"GLUu7ddylZdWpVoK85/g54WkmJqm2zVq4NLylE3zlbnwa70p1/cTGqJDblvH3x28xPW5Nne5lnLixqJg",
	"0z+F/YPscUGTtmsQ6mt/AmRo1vwDgIZ1R/3L9ZaExAe1dj8VkkfX6BqRdyeH5LGjV50nTfi8VhS/ntTe",
	"YveTuzoDfxeNI6hDMuC8Cp/trcOyF16Hu0Xb2tCNdUKS6ugJwNe7WgYMVpu+8Qp5ODL1yECQFUCShpUz",
	"e2mabRauchI7IlcWAaubQKNwlkxQV8a6w1egAPHOP3XqDGsDeZ8iKTvXXDL1Ew/pfzBXuGlhPXrNu8KF",
	"C0INB0/xNAqgwxcH5PCFhfLjf/5w9mRGjvE5xbTu6BQJ7WwxEyZ4WmFVwD7ceWtKuuBdnrB7u/kSIYAI",
	"hibl+5pRGYxsD7n3oLfcabJkqU2L0XRNrERgZVs5spUbvighaX4trEUPeAzk39TUUi8QtPjKfS2rwGj0",
	"0AsI570OcwcyF/WS/UpTqb+RNGEvvGQbQz3/tMetdQqjrl1L6NGT4BpC9/2dYvJQzPOOK2+wzDWL3/nI",
	"bX3ZfU3DBbVeFVkGiuLeAqQBocIstZYy9+4SRgeKb7YZE9emrLoZ9lsoLkK+PSjrd/F6wXvjqY/qp3IV",
	"0yt9w7UvnoZLQkaEGjfoezNznhUr9iYcPAk/N3IgYeLSK+g2NFIJx4FYJeuYUlXeAvpnOXcYHK+0qpsS",
	"dplOdsWCiw+7ZjmzdE/m/fUcwlE0kPklKSTXm1OozgQrvwA650pa4V+vnMD4zx/OJlXlJ/u1mh/SSiJm",
	"x+r+vHsXzgddq4HoxQ8Q8oauQY/XyHBdVTGdOeQ0b9rk3wWDWCLEarMUwyJUd2DNv2OWtTBSqBXtNU3g",
	"3KEA7GRvohld/e+yAsiM59WIZhev4AuxxYPIGaMr67Bua2Dt7e7WerfKWf5YH+L941C3J1bVhghtvYaT",
	"jErMU7qigi7YCuTROepWQHpm6YKVXu7mddBLxiW5zuWleVHU7FyAV0PCLKG0O9tf02TJyPPZ09Zmrq+v",
	"ZxQ+z3K52LV91e7rw4OXb09f7jyfPZ0t9SpDuq8BVxtA2j8+nEyrizy5enbBNH0G+LJmgq75ZG/y2ezp",
	"7JkN/AJ03KVrvnv1bNfw6btJ6fi6CGmYvmG6WbqmVf+q9KAyCApiovU7hZzL8CTAvM+fPnWoYWss20ga",
	"03f3X9ZJDQnukArMzhX3YwsTjr4zIPj82Zd3Nl9pPmjNBcXBRF7RMpbC5M///gCTn+U5eUPFhlhNAxo4",
	"UAb4cVI/uMl78612+I1s0FEMAH1/b85pyBNVTWmfuTCGfMP0sTf5PWJKI5d2AIid2bThLJ8+e4CzfCec",
	"4Gwx6E+JvtPJ3+7w8ONTHzq7FRpMCDrAbHV7DHa79y54derscZmzmRzL/IMrDmzVI86qVp1CrGIYZurR",
	"krMrTMbua37Dl80t4T6vWUtYCGF4Y7Xj3RrvVuRuXdGMp9Z3KXi3vrcNDA/buCmliqJ9E1wvYIckXTHN",
	"pAIjVputDo1qLp9bWskeLxlNgWV3PJ+v/3S8PQ3UqMDscPd0Ibsww+wEtoE38CEm/ZqmDhMf7tqf2bjZ",
	"aq/jvf9t3/tf3TNn7tLH3VInuc57zWjsA+ZGCj20vp1NbfHWPj7ef2OrrT5p20CsESzLr1HVAIYnq28I",
	"058za+PpJD5vvawjHUxAoSoSBOqIkgD5MJz4egu0I/TQIwDS13m6uTOMqdlCzZH7Q33Yub6+3jE8wU4h",
	"MxsWeuOxPza3+/EeSWzdIBKlP6Ve9I6Jbe/0NZq7xS10+BMXCkFk8tPT1hPt1BHfNPbbqr4LsC+8Euyu",
	"oUF5UESViX2KTHuOTeiljSWI0YPKXiEYwQywKpQmK6qtP0et0SP0QyjYI8zD4ZSJZfoPEH/dScY0Y26Q",
	"zkd/2g7EK4slYxZOLXlSF7oxlJOlLsYW08sxLrH6sZqRF+i7AcSNXTG50UtbMyy0UOh16qUFeaDVYo6T",
	"qSOSXCxs/F0uDYgvGXn01aMpefSV+V8qUvLoP756VLmEX7LNMywV/Wx6yTbP/wP/eG6dMEI7hRlvtlOD",
	"SSv6ga+KFRFlrj+HeOUmLabUEQTQ0AYOQBkjZdUoMUSrdSd8XsdyqIuEg7r+Fn9XFGAryAWrSncTqryL",
	"AylfVXGhINWBxlsUxQy+Amf5Ck69kcH3ysb6hCOmwLHqvj8uH9sSX59+9gCzvsrlBU9TJj458/oQuz21",
	"FoF3otQDth7NdZmM/eM0wpIeQGVDI5UGn8f264gdaqne74cLq00xiFN6do9zh6CWjtf43q/x04e4xge5",
	"mGcc7c8j4WgSjg87VSnSSZ3fjjHiu7+CPIzkJmM66P9ift+C8GCHBuHp1Yr5KTGDExmuENcYkU5vJpU+",
	"uJbMMRV/GsLw+QNM+TbXBOOTR8oQoAxxE/zgW/0N0/dypReYJui3fp/7GI3xVo+3+sEFBaqTgOca1OHf",
	"4mZD+3u527DAO73dQ6WXHZj6r1t6dJg+n0jlO5S+jDLMH4uojWLTpyejRYA5wqiALajoCVtnNLkfsacq",
	"7/LghPQ+1UAPTT1HxdNItEei/WfSdSVVXVWFdVWdr0a3BTpaj7XPHB3tONqmR9v0aJsebdOD6GSUioyG",
	"6tFQ/cne4OhjOsBqPeBFjVmwu2qj34ccE5/vgW3bPQsZ5Y3R0D0SnoYk0MHwDxILBtjDU2sP90kasReU",
	"VKQpZBPvImVbaYr6qeloLR+1GaNd7Q7IS1BJIBlNUQAvpY+k4263LOkPTAjuzMYOmbb/XbBDzGwCHNCn",
	"kYRGWjHSit+eDNRpkL+RDAR9H5hcjGb7+6VPo3g2moNGifAeyXARZNnAPt/g2g4Gc23Wvv/ApPh3Yfm/",
	"pcbsk1LjUWE3vgjjizDqCLfXEe7S9VrmVxQKLwefnH1owAikAhSbLgmgzfijA1q0w76b/M6eHZ0TWl/w",
	"+OyMQsBI8keS/0cm+RUV92g/5mOlCeSu3ZVMFZh1OWzjPoHvZRLXC6pYSnKBXkqV4xAV6W5uvYHKX0N+",
	"xGY0LG+j7snEjaPjTJ+IZtaXEE81M5LL0bPl3ilJ7b5P3gPxuKCJKyMLY6AkjpkuHVmxV95RiI9NstP8",
	"3qQwPV6oeEf6XE4rUjH6l47+paN/6R/EvzSAIxd5njEqyDyjC4MntjYSyUW2gdWsVlRu6jXt1Iz8YHYC",
	"oMoJiGouaz+CBSBpaxvgUHDz7WB+DmAsbAYAz68Fk48Qm2p4/6iCUbPAGVSReWQHNkM9IlzBimJw89qG",
	"sMzC4559U5C+jp63I3/yifmTIW62DZYh5lOLze5Vunhob1l/1lHTPrrG/ukoQ0jyCIgcW2R86qcm2LKk",
	"JltpohuDjw6ro6p1dELb9tLHEzv1X95vmL6zm/s7yeIUZxLGazte2wfk4rsdRXuvLjS8s8s7+nveIQEZ",
	"BYzRrjvKNHdFJ7tSM/WTSeuzeWeE8nfhjbmN+uXhCOOo6hkp8UiJ/yzapd2UJfnKljqN+keW1fQrcxVq",
	"gby+bY1T9fEO9U7VoL8L6u5DYWSBR8I7Cu6fkAzWiV2cJmZUacWw7GB3RWyqNDEtieYrpjRdrSPEq0Op",
	"95oqfcr6iwIOU+5F1zVHH8bfh+KvhEkHm/p5+1ze5lAY3yxiJDUjqfmUpKakIXEyI5lImcRSl51kxjW0",
	"rFeQlpzYNndpKAhN7tysbDnSO6QqQQ80oGSXIr8W5UK+Z7LG/jVckaDxSb3t5Ldqxhip2CipjnSz7oFt",
	"iWKcbiqcvI9qYjND4bYxsdqdjYbW0dA6MlG/FUPr1tfZM7ve2YUeja+j5mmkZCMlu40pdGtCVjOM3hkp",
	"G82jI+kaSdcoA/5GZUAr4HkSIBMyz7IVEzrJxZwvOoW/qnEtKC4k870smx7guFvQVjowMxiG7c4hsQDh",
	"ShX1HLQzcjgntiZOOi2DeQ38MOBvyZJLwvuSwti4QBWeBOL/INaSK5JQxcqQRO60fDaeswmRGTkUhGYZ",
	"yfWSSeiLi/Sg7E+EYZ2w8gtG2Gqto8GWiZKfTDHXOviR4I+86p+E/FY3t0rDEqS1w0pwVVdpYOmtVocx",
	"JcKYEmFMiTCW3Nry5R5LbY0B/7/Ft7Qv9l90PJmxPACtHveUEqA9zwNnB4gsYPQeHxMF/JkpSk1PEuDQ",
	"O/n3LTIJbEebsFeINm2loY5POeYaGKX6UY37u6JU8UQH29GWmnb2XgjL78RDZxBHNBKYUW34aUSdzgQJ",
	"21156HTPl3704rkfwjNKYSM7NbJT90BfuxIrbEderS/RPRPY34Vv0Q3VXJ+Eto7atZGuj3R9VOi1FXo3",
	"KGwVeDHaD4XtdQ8Pxe+udFVrC2U5r0/9YLiF9CsdRxI+KiL+9AQ1WD4qTlm3jzG8vXbzZu79o45zJC0j",
	"afl0Os5bkYGwxvM+CMGo9xz1niMFHOXjP4Le81YkN6YFvQ+iO+pCR+ZvZP7+2HJlIFjxyiwoKjueMC05",
	"u2KK0DJAArvMzkU4YAYH7AuS+dPEYZzmUpNcpkxCWKUtkghxEWZDLuVhPQbmkRnjEXks2LUh03MulY4u",
	"DgavLSrFoSBKVSWT6YSJYmWwhsJf8OP76U1jSPD88dzMEbkgkL74orupV/mHjq66V7WFObYx/mSMP/l0",
	"b5bBwMA7hS+G9yjNM8b6IjlfmTZ90ZuvcKAxYnOM2BwjNv+4RawPbX6IWLVqt2mgK7GV0NTmo1WnOMin",
	"Kw4NZGt8qsen+pM91XBThpSGrj/DsYhQaHVPUaA49gNHfnqTjv5oY7Tnn40o1Ph3y623+PfdX+G/H3c1",
	"W60zqg2bqHgu4ow9MCWuNSmbhzj7M9vq+6pRry48vxbIUxleoDVNRPM990jXDXPDj/LFKF+M8sWYEcZQ",
	"3wbdGpn8kcn/bb7n7Vd7+AM/IIdDanM4tN7hSN6Gxr259XN/f6990+o+cOYxOcRo2h5N23WyFBQSJKMp",
	"csgle9BLQ75heiQgD0lAmtAeKclISX6PDM7gXFS9ilBs6BShW/nt1Yce00yN93+8/3fBSUCip96L+w3T",
	"d3Rr7zC+6c9hAh3Jxkg2Pq3xszNhVC/pgHZ3RDzGmKi7ox2jVnWMgxpNwXdEIrtyPvVSSBvgdEc08ncR",
	"wrSFv8qDkcTRNWYkwSMJ/oN74wxKFgLa9Speta5nd2Q6LCDfLCj1XsXkUUIdJdQ/sYTarOA7XF69q7s8",
	"Sq2j1DoSsZGI3UCGlCgabsmM+ALlXRGxUawceaCRfPy+jPvtTBfoWT4o00XKleYi0aUHOPYtEzhURKgi",
	"E5s1i6XEeI0zD6BDZhTrlF1SH2kXVi5C5quYAe+Si7STGLlEEC9sVfPpEAf5Oc9swEJzLbnINhiyUAZi",
	"E72kfljCgl8xge1LT/t7ceO/g1WiB3vfKu/cBb9CN1zvg2TWuJlozD7Q1TrDHrjal/gL3HhrNN6b2B+r",
	"AABzczJ3DcDTH5PYXHGZixUT+qu1zNMi0eiaJ9mC5+KrQu0wqvTOM7MBzuRXFzS5ZCLFGtDDCAxcvtHN",
	"fnSz/2QPFeB9+6Gy18F7oXK5oIL/AqvbLiVTreeMkCND8ZCGqPpHJHyGqBSKSbKkitAkYcpQnXAOjaPa",
	"qv6seZ3uU5PoQ3ikVCOlenBKVT3ckFonb9x4R8j839v0rN7LI2uSrXPFdS4568npc+JabvoS+5z4Y47p",
	"fcbw2zH8dgy/HUAbKwozPrTjQ/vJRILySdwMybETeBZjiXaqpveUbceb4IFT7jRnHp2Lxrw7f0pqUeO6",
	"a8x1hOneJoxtEK3B1jVas5WJLTDJGNU2Gr5Gw9dNyEFHaNugy/wN03d+k38nLnzdLMV4lcer/MByQHe4",
	"2aDrbF3Y7vhCj358d0xURhFljH8YpaK7pJ2dcWiDSKf1Hbxz4vm78B/cVrHzsARzVCSNVHqk0n8a3ZW1",
	"/W5E0msxxqanG5H024yrtqPReDQaj0bj0Wg8kGGoCMdoNh7Nxp/wMa0exmGG48DrGDcdV43vzXjsTfHg",
	"5uPm3CPfPxqQ/6R0o8GG++x2jA/fzog8iO44M3KN7mypcAlMNJqSR33AaH+6GWHoNCYPutRgTr6HG/27",
	"MSl3sxnjpR4v9YNLCX1m5UEX29pU7+Fqj8blOycvowAzGi5GmeluqWiPgXkQES1NzPdARn8nZuZtVUAP",
	"TTxHpdNIs0ea/efRc9kKVTEzsxF+lZ3XK8DVEnqrumL3Rr8GFNMabTIPjXMOf95DXzS34jNeyGyyN9md",
	"mKfUtm4i15HDIswtZcgkE9puYeYVZql9mLTtxN5AuSD7hV4ey/yKp0zWvSK88da2Qe9oB0xqPjdzs1O+",
	"EFws7CkEh06q1gpby/K96Z4Hc1IFB8UiNt0jGABiO0IT7Sp61wawv/eu5KWQeZatmNBdO2Vlq0E7NOuz",
	"mam4WBB2ZRDQH8780Lu0enZCvz/mQ9tmCTbdFE1krhRJ+XzOJBPh0TGJzTaj+1lNgkPW0kn07TuWGsKO",
	"5bkZ9Y8Ucxkqx/JekQE7ThiHDQdeCTuioxEf33/8vwEAAP//ly7l2NcCAwA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
