// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/core/v1beta1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H1rc9s4suhfwdGeqtgzEv1IZu6Ot6b2epzH+ExeazveqjvO7kAkJOGYBDgAKEebk/Pbb3UDIEGRlCXF",
	"cZIdfkkskng1Gv1G9/tBLLNcCiaMHhy9H+h4xjKKfx5PJiw2LHmaMmbgAU0SbrgUNH2tZM6U4UwPjiY0",
	"1Ww4SJiOFc/h/eBo8EowMoF2RCpiZu5HyrQmdDpVbEoNIzfczEjC5jxmhIqE8IxOGYllIYwmE6kIJSeX",
	"T6LBcJAH470fUDexx9gUH9VHdy8IF8TMuK5mUs1iqmSRE98TGS9wlm64iVQZNYOjARfm+0eD4cAscmZ/",
	"silTgw/DwYSLhItpy+CvmRolfMq0If4jXOltk4GBuWEZdvmfik0GR4M/7VW7s+e2Zu+ySAVTdMxTbhbP",
	"oOmpYRlMyk2TKkUXOEkY4SXNWHOWuKkkY4Ym1NBI0IwNCctys0DId2xZVMFCG8XFtBwFvmuOcqEKRm5m",
	"zC1dyRuiWK6YhgW5rddESEPkjbDbQO24wUhjKVNGxeDDh+FAsd8LrlgyOPo1WF04h2EDPYLNelt2Ksf/",
	"zWID0z/O+SVTGie8PP/j16fuHUnYhAumETJz+4wlxO4JkRO3QL84Ch3AYyqIHSoi50xBQ6JnskgTEksx",
	"Z8oQxWI5FfxfZW+aGInDpNQAFgHWKUFTMqdpwYZ4VDK6IIpBv6QQQQ/4iY7IC6kY4WIij8jMmFwf7e1N",
	"uYmu/6wjLgGpskJws9iLpTCKjwsjld5L2Jyle5pPR1TFM25YbArF9mjORzhZAYvSUZb8STEtCxUzDdvE",
	"RJHBfswPaJrP6AFuB5/OTGxSGK18/nYZeYaDdyNoPZpTBRiooZtqPy6rDquHT33Xp/Iy6PjdaCpHDdQ8",
	"oYamcnor8WLvaJaneExogA4d6xgOrrlIBkdl98OBP0jQg8ADN2DJlI1onmuYiM5ZjOjFdZ7ShT2TgyfJ",
	"lJHjPE95jAijEceXiF0NPVfRhQCRP/gpLiP0LxzorCaUWCBZhKnwFh4B6p09Ob8gfpctbls0Ds5vhdGA",
	"jVxMmHIUTskMe2EiySUXBn/EKWfCEF2MM27gqPxeMG0A2SNyQgUQgTEjRZ5Qw5KInApyQjOWnlDNPjk+",
	"A+LoEYBMt5K4cHtXbcH8YMwMPfinzJmgOf/nK4TZC2ZoiASrenAodQ6fQhNDTaHXbWQ/XqaTAQY5tAgW",
	"5GbVRhhdr8hcNuP+QcuQ3lNBaIXsxLAsBxJn8YWS2LaKyKkhuZJznjDgERNapAao5YRPC2WbWjJHzIwa",
	"ElMBiBMX2sgMiSAyHJiuQ+baoDLkMF/NUfsYpAx2YwtMhGYWG+8erY6V4RMabypcHgtCXUui2IQpJmIW",
	"kYsZIzAamXCWIugBvAmHphkX1IBECbyz0JbUCP57wSrZjJW9apJy3YIgolWUepXbeZNZkVExUowmdJzi",
	"yEDrCbRyQhWggxsDOadnO4O/nbz6+yF5zPU1OQUpuG2/7YO1N80D9wKafRgOCsVbBBwPxzdnpwgJWRgv",
	"3pDfC5ryCWfKwtY/LkFOdgydgiRrxd1dxHY4aywh1CBOp4U9dTxj9QX/XtAFkG7Fkhk1e2rG0tFYShOP",
	"fo/lzSHgEhfPmZia2eDooAGNJVzEt3aJa6LchQNmBzisBlBHnoi8WBdzyKmI0wLol10TajajccHThCki",
	"C5MXfoyaCAXsi3LB1GA48HCgGQfNQEv4W9BYioSO7M95llzDfzM4e4reDIaDacx821HC9fWo6vJtCP9w",
	"pDWEsg4IngS9dHzyN7eMjtfHuLqOl6e4yq6WDhYrP7q0EOp6i4DreHmG8Ox4+QzBvGrJcJYr8LytY+EJ",
	"NWwq1cJiIHI40NsqPjVoYanYAnUKzyoJ6Ish/uiFBm49rHX1dtMd9mOd+95a3h2HAywtzrPqcdpyxE5q",
	"jBxJdZ2RA+MAqoM0BBZIUpDjyA4tpQG9i4RczplSPEmA21dUC7+OiONNI9vYCQyTIk1BccpTGjPsvP5+",
	"B6TQjKkpS3ab5N/KIN3MyqiiKQq1yS07TMwvqdJDkktl9JDMZVpkTA9LOUAPCTNxtFsjmu8Hrh38+fzV",
	"s38+f3L55DnaJSYS6Bz2Bpv5w/4P+0fwD+5Ngx7ahZwjz9hsOf91/uolsQ2tRgxSTBxsOMmpohkzoBbA",
	"HpkZ4wrWzRMEQSDJVPMBltnGWR8zQ3nKEpLIuMi8Wj0kObIgOk5B7SAZVdeJvBGOoLbISh9W84THLE/l",
	"AvrfXs6t+qhJvB6bY5JUHzSOcCCVIjtFw0VEjusfUa1lzEE7Cr/HozOjmghZGlS4JtrwNIWd0TxhCg5T",
	"MAPoOpgPSJwiXYQDoGmuNALhTsLRgCdcJHzOk4Km1XiCxFQzDZK3YjgUGvW4JoUGDFlabjC2O/lZqQW4",
	"pgC3SkOQ4u6l9oBEdpjIpKpN29kTGXkQNH0AnyBFHOI7FPbQHFTXO6Rt6laHq7a/w11Y2oCInDkZx1pD",
	"g+5q82rVDuLK9LFkkwNd3DV3E40rPK5LaZUNo3sErx92joJqoFsx1+GSY6kU07kUCZoBakOLKRfvWoed",
	"USFY2jGkfTkkfEKowD2hCFouDBOJPTpjRoyi8bWDawCBkqE2RrWzZsmFbB/Ybaw367avF7CWcuEXW8dj",
	"T/p/adUmn3AzY4pQ8rgc6OmSnbSarO+qHa8vltB0aepr0s/PpPTOu0y1oYZSR2tHYh0i+I1sX+ZtCm5c",
	"WvxC7K+m9XZdTvOc6zvhNtCPBTgoHrDy1s/03dHN0kdRn93zW4dfy7nRzpZbfBu9ffMLsG/Cplub0mbG",
	"IYsKtx8WxZyKsdlJCVoiUEEsRG0DfYo1siCVpxoReY0bH1sRB9g6UgvsiSXEmmKb5yhjWtNpC50tmbf7",
	"grB3eUqtyHwzW1hc4rUxQM66Qc4hSSIJF9owmtQZ4wU2g7nX2kbkjWYEueYoTwsdNm5hEKgBeZG3w54V",
	"MomgRR2AO4EWBVLkbgsbxwndSm89IG9Bi4+jnCvp5WehklvRxp4i/hEpInYMSJmmryaDo18/whn1ftm2",
	"sY66YErSM2apFFO7lec84ylVQLPQmpSjbUWQX4oxU4IZ5yVeR6lYgpmfVBMsb5eP+AsHSqTxdf+Td1WT",
	"J+9AB9CkAoTVc/3ydCxzLqatJoplb8jWBAha14IJ6p6tJotqoUne2LzCgG2NM4jule+h1i15jJNIiBQx",
	"+0vTuq+tAX/OCKPxrPK4cJGwHHQpYdJFRC4WOVvhUvGOlHL7f33vgRuaoNE5UToFciUzZmas0MGfuOmb",
	"0snSw/QBHQqntvlBk3jGgUV2zb5LIy6qh9YwuUnz0ExqNcxQ3FlfSC5bQSdhfMEycvy8wj+lZ/JGWEOO",
	"xRHYOC6m7dSxZo97o9I2RieugSKwdy54pdaktdOZzFjeKkkBDfJvyZuz561qO8mVxECbtr553KYzQldS",
	"EaQbb85OW/VGaInjeXBxQd6ctg7inNaqJSbMvYHR8mKccg3KfNtwO7DdVCwwbo7RDHdnt3U4PZPKPA7H",
	"aVADMlacTYgUbJRyAap++bpt9PZhijyXynRvsfugorQI03C7EX5TZlDYmLE0j+7Av+n9mo5wtRHDOeUp",
	"orr/xpkjT7iIuRDUcJLJhKVWdnYirqWXueIZVQsCzGpI9DXPtY0r0AZ7dIYm9wZDtDKWcGqqwZbJnmuC",
	"Bnrby2A4mFBtgL9VZNd5GhxpPBroGT387vsj+pAlP3wXUzbeP5xM2Pd/jpPkh0ny50eP9r///s/7lP3w",
	"MPn+4cN4fPD9o8PDZH+f/Zn+n/jw8Ifvvhs/+j55FIj9enA0OIwePYr2B8MBLgCmdBg9ehjtw1xKGws8",
	"+y7aR3EhnP3tk567/huDPsRBayPgd1vQ9kDarlPzdudwxTUDnLlF4Gr3EiPLk5P6wXU8DwRdz0tCz5y0",
	"cYgqu6EKZpMoPkfOF3LBGUuzwRDYYJIygy+zXGr8HsTEjT15MNNX54PGmp5WE1l689jPa+l5h6cXXv1s",
	"Z7309G/lIho9+TUtD41LrG9AoHutJ/R2M9iGxFsidMNF6d5YockLRoHIGypsTc1hlZhxN0weDbZPGQXl",
	"Rq8Pm8f1dk0h2tmWJ/YL4g4RGvCs/ZQSQ9WUGW8zRrlPU8P1ZFGJmR5i1tQe+KCQtxk+TllkKUNIPtrF",
	"6fer40AaagDN0b3mhVWMBzLShZbXwlUi8gtbaLuEjBoQce3nXKD3KSoJRkReiXRBrtmCJUGkB1WM0JLF",
	"LK9+yXP7KSi6jxGx5NYSagBXCL+DZQJXD5XNaP5rRxTD24a5aANUO8ej24JiIMoBD66YsrM1iIoBDyvX",
	"MkgonhUX+VTRhCFLRvwB1nVGhZUYN5mXbdSc3DnL5kwRBa8BjUqxoYxP8HNIuGKxSRc2VNvO30oRgAf/",
	"GmmjQHiztg0UiGbSTPi7ZV34qtjff8h+PIj2o32CP+KD6KHdSceZG1JNeU62mt+aQgyw+BF6hdvFmQFO",
	"eTAcHEQHVmpYi317vGhSxvmmlL4Txc5ZRoXhcYlgHHRVDGQjOyyaRkNyEB1GD4fkENYwUvHB7pKrtXQk",
	"qYSh0YyKpITtVNF8Vt9Gf/yWJI95afApmU2N6q1h1zgOnVpLtuuJTFN544/JslDrnPF++64E0CshE+uv",
	"D3AF14Mr9LNE0pbSMfyJB1Rq1zS6Em+CY2i/TJwhYbyoZOgde8h3vey8kxWp4Tk+kepKlGeX7Ojg1O0G",
	"oXMdrDyMGboSLgaoFszjlfHoSqww5WxvR+60Id+7/Xhj23FvN/6j2Y23t1Y6SyW8GbfaKkOKFJUoiSSh",
	"FHesNp3KmKbpYpRRQacsucXnck9GrO1sQvdmDvpclqDPaQRaEah3Xt6E2QKTsW0YmIfrLZRCOmPf1vir",
	"XURrCKgdvE1tDPpjy7tZdbgWuV4mDyd+3FutHcEMW6nCnJ3gBdufFudszhQ3i01hau/nygkcAcNFbMjJ",
	"5ZMyOE6qKRX8X3bLxwsy49MZAy3RjdYCU8UNj2naFitc2HDJaiT3LQ655lVdmME6ff/Mp7NN+k3lzTrd",
	"Ppc3m/QKAniRrdPxC/xyk76FFGwtKMN+omtMSIxakNwqDDzLQaveObk8Pyc6Bla7v7vm4Eaatj2+gMdL",
	"Q9NYSa0b6LTmQIW4FvJGbLZQ1wioViFwZUkNZW8dd9noiKsdVsjt8LDcYIs/bk+qSbedWWuWuftj68N3",
	"y1vwLUd4aC+nW+l+Ht483+pEvyyysWV1fvAbVC6WqYS/Og8SqO/to477NgPDu4+hBduMmcqbjyQU24xq",
	"+/ooKrLNsNDTx1GPYNRlrMZjTQ1JGQWdSbAl9C3nIe6c0GwDC9fZl0FrnI34J5d5obHAS9QFUWJy2Rm8",
	"RbjFdjwEFqKY1iwh1FJ1p1JeDYwq2NUAqO7VAMnW1SD0msBrdJKlmq3p/WhbwIXtpu3VU9v18sr1xhGH",
	"3ZbzhMUpVT67Rc2CU4YePqHxzN1bxZVUFyF8l932d6dnOIS3tuxKYd/IKm8N3Xjvww1rZ+MtPPZ6h2Ik",
	"ZyrjxrDEpqPACBEg1VJooyh+ayQ6w2iaypsqM0WDV0zzInJi+ZaeDI+lTePZ32cMo+ZhQXXAce33CCc6",
	"o3NGKHn2+g1xc0ED8/U8i5gAySf5zHP75fIFcTPBmUkdZTJhHxEMpl/IhFkfequR/tU5sdo6hnzCYLdP",
	"VRUialfiLFBqmWvOiyyjanGGF0A02/DAeSmIaNuNC5xyrgV3g+rurHFZa1wKXtUO7kOjOctfYLLhwuR4",
	"DOjkk+CUty3cjS3FhD2Er86tj6rdUgFvHqPXqmsSPuPQJ5pBu43wzJv94PVfCE1v6EKT7r3uMC3gu42y",
	"Hvndd/2uZTTz47RxPbxK0zbj9Q/Y6vkNb0HuOpraMDq74W3prbyow4Ot10SONVPzSowvb/NsKk/Uh1/D",
	"SWGTSdXFKxRKNOFozQd25GIDHaJilq9oJew/CWW4l9Qf7eeic6Efcyy6Mfdjz4TzrzUWt417reYsw7ew",
	"A9QYpqDLf+zs/8+vB6Mf3l5dJd/sXl1FK3/v/PVotLPz16Pg2f/AP7/S0b+OR/9v9PbX/dEP/m/8HHpY",
	"+/vdb3Z3/4qNvt0J33xrO6o9wm//szWFQls6qtD73AbXyvlcClLGw7TFU4zw3Y3IeU5jNtIsp8reDmYq",
	"00MrlKFQKP2NDkB5zIOy47pz/cb+D+YfDMmPQ/K/Q/KPXedm9PJrW3jDoGty9V3+1X1mP/jff7z9BoD5",
	"9lsH1bff7pR/7f51Z1RBOhrhk6urbxvPyCfodPebDbZ0G7O0s0ejd00xUygRCOsxTVPn0U+keGD8FxLF",
	"RXs+79DRGDsxcmmGxRTINEvIzxcXr/0U4NtKobDyxZDsEz7B2+G6yW4eHrZqzr3L8U5djh0X0I4bGYma",
	"Tp/K+WHhiASiK0JbMarbvUsZBZ2TdQ5V3ncrB7CXsnEOV4OnlKeFYleDUmg9dROyKMC1y01pUANF01Ht",
	"Zl8ZhxWRY3KG0ySgdQNbwsRjiMZusYjG4wLOl88+WUURtDPj8pS3HmQHywp45JVgRE6OyNXgvIhjprU3",
	"cpQr/eRoo3MWj6hIRtXFxc3vO7uFOzJRYsBw5WW9mjiyaW6vMjqsJk3unFw+2fXmsoiEI3AXhTJN5dg6",
	"hjClpko0yZVMirhK7+rd1yxZNmXHVAim/gJfLYgNlDHEMEGFGdnUpME9ogt4Hi/s/Utgtj76peU2PXrC",
	"2TugMkoW0xm5mfF4Vo3ze8EUt7fRl+h5MudaqsVpC6G8ZCIBodZ9EkpgNvddeRrakPn29LmdDoKxO8Un",
	"l08i8rRMVRIs0l5pdRLvwV+QW9QBwY1PzSYaZtJQcyGqEMLGXjlFxyUlsePbrkOr7egGTnBzGFQ1Qp/S",
	"zUymWxl8t+axc9a2jYCqy8IzLG10uH/4aHRw+PBRu7s/nmt9HkvV5su7PD8nY6qZ88410aFc5iSV1FTd",
	"281oRNQ2KN5MKlOqVo7w1Q5TtwXjdgPKjr1yrMibs+e7FauuY9k2JpKs8A7MZWPJuv1rXbRpQy/DfC/l",
	"ecSP3YaegRBFzZC8vHy8azektPSvaWe5W8Ho2B7Oy1s3LeXiuj1AxiUoBgROMEeTJjmdsoi8BokKExi7",
	"ZZNzFheojudSGZriqfXvHMA400Mr3t5wjeHaLy8ft4fUuGCZ5Ni0BcY68LuvMOvgEsBL7AdBbgQftLL7",
	"wMW6tN3QPrXJmr2dAQMlQ6/FSeWH+dn6YV54P8xz9MO8tH6YNw0/TDAF3MPNjGK2yVppTJAgBQu9lY1j",
	"nvGNeTkgiPcfOwIsBR7wDIUfOI16SKh2GoZlMUj+RzqWuUuJ0KTydfaNYZhentelN8X61oKoHxjbUgAu",
	"KkaMs7yhlpkDm7NxoxvmnF+KY1jFOv1dIVzh18V6Nkt7X6qKwaIB4CD0LKrl33HW+zukoe3E8plP199U",
	"xei7k27m/LNz/y4zaXcyaJqWoFuPU2f03etVFPG5TSBPWwnjbaNuSSH/LlXo4W4ZpSzLUJY9uDvCuQ3t",
	"u6U+QAfibanWwEnwlMkZpn2GwFA2GQaGc4Ad94KSswz5q/nIiDFRLV5p+pK0iJdt0j2e+VKyt/nRyqmv",
	"QQa/QtF3wpU254yJthP697I2hmdC+PmSL6cdSisP6BbycLdcfcYm+lbhPXBAlXTfMYQ1SH/HbfCKqt+T",
	"AN7LvC2OCUfLvZEQaVh9i79c8Tc8CDWiX2H2elR/i/tCr+mUC3TJ+ItCzW6DiPmdmuDbZt3Y/eQXjKop",
	"r5xquf25ixjYUob7fPLbc95B8b6cGzy1SZ86dN0QBc9K24qRhAry6hwQ60aq61RSX3Jr7O7PgK7VKUms",
	"W3SrxtzZO7oUpxAyg5zaCxMoFOyU+Y/HKdWGKJrwAmtGrRthvo2RKfp0zLONEA3qna+x6/nm9TF+CuFX",
	"i34Ayu0kcoS2zdFdFfpyktodehfXUj9LalLfeRf/8TntcV1UkqlRSx03JW/0yqp2a1PKeu29tYlke+BJ",
	"C0Z9JbLPdvp0zexQcym0V937eEV7PTF+zVmsFNM+njttoLxvCsh71eMDFtqi0q/JVe9eqCO12nifQ1a7",
	"WzHtc90YbxPcvjaZbTkMdDNEsxbluqXbFUcdL5YPKcPaJgDWIsVIHFvLRPp4fn/ZFRBhd6s7mOXVy+Xb",
	"K5Xbtj6Du7meibcy73jI1Tc3n8ubux7w1kud7i7nHQ97y33PWnnae7vqOV+O3agsxG75vKRc2y789iug",
	"9bV/ybc/24wc7dUPapRiTONrhgV4qKkCYRCkLoqmfs9KGz5Z2ORzizWvWl1Urf6GrRqz/ahA7id4kb7N",
	"3+dtsJVQfWfaytIF25UpVVqu0n+MZN4dDb6eVyOcRxsidecU2PoWUdnFT1S35dhbJ6VnZ5/2clJbMsc1",
	"riSUvfhUJLrUXDBuSDBCdQ5Ch0/U0MzewDU5fn1K/NZFK4GIEGhsOzwlZUoGEIwKDNgLcjdVabJxtDCK",
	"zybswmt9sD1owkmS0GeECevgYDYPAajSF4oKbYHJu0rBoMqNZmMXIufmasq2LLGhMgA0F0KJxiRU4TZR",
	"XTriVDGlCylDR325BFeFAWDkt46OZWHcjMvptUqEXvN6xoQLymxffVSWQJ+WX1blmSpogE4HUhWomQkp",
	"8rVjxrpjZncwJcsusV9UOY39mA/0Witdr0RwJ952FA0uAz9b0GjNMNDbhrwlmraEw9DGjEzIhSrYkOCN",
	"3SF5U92X9lzMXfO1V3pXaJftWVPrs3N9LT31XS89LkdatepbcsmWmMbD2PJgdcd5ruScAbG/eP3ikmFs",
	"c4K10csXj5mwz55i3bzmpxiLzG3q4doPT+ReU6Xx0/OFiPGPM0YTYPGXNOX4GyhXYU7FayWnypbcf5Mn",
	"eFChXc5i/+kLl/Pt1Y1gSpc3sB+zWGYZ18DBbCM0cz1mqaGvFcup2yX/9dLjJ0LJNM2YMD9Lea3X3N+q",
	"1ZkN7g/A1nhXh9oJENUJVoQ551OYcrOLzm/KLen8otyrzi/q0zljudTcSLVo3UHYuM4XjW0OX5Zb/pyO",
	"WQq/XtA8x2lYFLCXzdzm4o82ZLDbFqCEfRAihn3yadDDPm4gScvRLLX/1jR7WB+iSn/m+YRlDnohzIwZ",
	"HgfGFryMP6NzFgZvpFw7K/ucKi4LXd64cBd5yHFlC8nowl73RrXdUb33VbmKIfET+9CamspwUbTQmBd0",
	"gYVVmSHc0tZCM4W/KUl5xo0vT1hFZNuChz4qz97yr8oilQwSmazCu8QY0YcQCi5joF7ir3DInP5eWKN4",
	"ZqdUaJcoQGt8Ye84uds33uocXNQByFuDKkpnaIAzEqapOJtbCUawd9YAIidBet4S3CcWTK4qpRSaawNy",
	"H/YF03J3fXJpD5AHmVtpPQMerDueUTG1/loEgZlRrFbJbkjGRQHgwj3NqdYssSDxO+7EeJf5oYyBRKeE",
	"TVVv63a4rXWgvOFpClO0HpSYph5SDtLOZIAWaO9EGZJCoLF2IQs7H8VixktQGnnNhKvBKQhTCpZjmXvH",
	"VaDMlrKy6TmLtkJSFzWM0sVYw8YKU6+miYC3wZj+4oU9PkH0C35T+oPs5SDmn1pk8RkHExuPixZqhKpm",
	"KYuNVBoLdC7jebkOP6kyE4svX+u68UBP2cSQQmhXFVXaNBgkKdDkqZniNPW3CmoTxX3M8pQZRnaYLec4",
	"ZjEtNHOXFWDp8awQ19CTrN76WxXGS+v40W61HpeUQ0iLgctrsgvh+mNW4m/TSaxgjjg+P4gOviOJ9Hf/",
	"gjEslpc1N2ERZR2xZbyBlX3DtOEZ8otv7Gnj/3L5ZWKZwv7hJE7wlp4meiaL1FakVQwpZVffNtmJth4L",
	"+wNd0usadW4VaoOiSs1CalWdIb7MQGiakhxOP16ybGUi9kxwnw4XWjgqhvTbfRsrRk1bqgshpE28uDK7",
	"+i351KuPrfazKGmhy6/RrC0N83GagjY0y9vpQqlwOtM/6Fd2Kcn6GmXCUrbNWO4AYPNNxpuuUCaPiaVu",
	"cUldao6PQGcPFM2yAqvGFCpoe4jIa5kXKTXVnTJb1j0iIIdhUu517dyYwnllcn36zifX//7hutn1nXvn",
	"mi28ZINVzcMi7p6xuwgmy/RdXQz4uWNjPuCppc+74c3mBlKJtQrZ2u+hg2BZh9+1rUveiLbogePQL0UN",
	"kTfCVYHwz0G2I1dodduDsa8G3WXHq0K8l11Va4+Fl4ocUG2ZWh8aoQPR44HL0B4kfkcKKYJ1r5FOdUUi",
	"oCYBa+QAisiVDWC5GtTEQcwXBETOJfidc8wMZmKguyrPRlIbxXzIjEuLD53lNL5e7k64eg0ja2ypz4Lr",
	"elCvV499eI3rcE2t0K7+1LW1v177Hlqg9ZqaeOa0MoBX6U/dILuL7CBT1dVoI4E3AF6FK6RJMihrMeBf",
	"mZwjnaqHEgWho9TM2pAcq/hj6AZTBD5qL7UMx7rD1YCCpjNHSuXTvkcNM5LMB24abRaiRiJb7YJHzuMZ",
	"yyy0xowqpo4LuxL766knff/194vBcIA2LujIvq3WMjMGIwylmrZFIcFK3rw5fVzSjzB1bXj+WRBQ+ILm",
	"zvxZ+77i7xEgF/raBZa0YwpUZ0vBYCb/RA3YLz3nvzBY+wf4fiLLUiE26AsEmnRwNDCMZv93kvLpzMQm",
	"jbiseoRFPMU3qNoomZILRjOsqZc6GOijvb1a6wZl/7Xexdudtma7zrtvub/Ngo257ajhcxYeUjnx8WVy",
	"goUCqvtQVqjmVQyijq7Elbjw1nZP2nbmBzTNZ/Rgt7Lg44ORNjaez4tMVp5SDDQM5O9GOqXMXuRKecyc",
	"98nB7Din8YyRQ0xQUgfTzc1NRPF1JNV0z7XVe89PT568PH8yOoz2o5nJUkRfbjD7yRL4j1+f1kpc+YUg",
	"Jlo6MjgaPIz2owN3OBDR91xmwJKkTJnpKAAQpk8P/adhVYCSmgDmY7PjNA0b4tiKZswwpdHz08KaXN6Y",
	"8kOArQ3hd5qGLlITJNWwrCrU+93ZqnoICu6Y5a8eeE33gdNVfKCoYnM0ntQVwY5DVlpCHGmgLYLuh2Gb",
	"AGc1RWtSgC9jU+lvqCw6Bd3L4VY+48oVy8Camlh6AksfzplamJlztbZNFFudu1Hvcba2gsbQJ21HddNl",
	"BgIQXzPy4McHQ/LgR/gXTuyD//jxQZmIaHDNFgc/4r4dDK/Z4vA/7I/Dq8Fu10pxxO1WCqiU0Xc8K7Ka",
	"3m4xr1xkaE2oLAUXleUGpX6rpnYjWq054ZM6mrN3XBvb6ZJJJqMLq42DtmkFfZvttMJ7LoB2VkYQhFAn",
	"ZvCMmxqcGll1HEwGRwf7+/tY98n+3G9RZLFWn10UkpbD/X3PaXzezTxPuS0xtvffzmFVDb5mnTKMpkNe",
	"tiRH/gK079EdDlp6rRpj/UQT4gU0HPTgHgZ9I2hhZqjaJHbUh/cw6lOpxjxJGMYuPDr84R6GvJCSvKBi",
	"4UGsYejv7mW1507seCNK+d9qOHSqa8WiP4Ck78UDYAchX/0wLBnteky2Hs/Z5Kqe534Gdtpz056b9tz0",
	"35Kb9py056RfBCfNZdsduBO01BPaYJJNHmk/9eXnrHWIafOTTBZ3fWjsWivzk1EF+9A4qwefZtg2ACUD",
	"e6kKR64BwqeQqMMqbnxSFyrel1tzBBNzZHksk8Wf9rz5Ca3SuJ2P0b3hJ9kYLKm9Xh7IUc7bR3nGTOcQ",
	"0+rdHfRfhY11jXLug9a2HCuQ5069FaY+Vrr8xcds0Jm1mnaCT9Xfb72s+jhdYFRtX2055oeeSX1qJrV/",
	"H0zqRIpJyq2xvmeLtyiYdeVy773768PephZdG4Xjn61UO9ey5C77SduYdpXLmyVTNqJ5rr0wje6bSh2s",
	"cfKK0W6mb32EMvzFqal3r45+jJLWGxR7DnNHHObRPQz5UhryVBYi6VnMVpoXnBJrDOlkFye3aBVfHr94",
	"+0nVRJs3sgUvqqUiVKtQIBlE2d27etk13RYVs6bxtauYSeOTlRoMbkKEISLVRm6hu7VPZlp//wlnUleB",
	"2mejmt98shn1CtK/I/u6d53sK1GM9pq+t2X1aO89nIwPluEBiWpLMIax83XWd5uu9PgWevcVKEsdM6rx",
	"qKh9fPxvY877ieT6bgTrxfl/S3r45VGnVgPMM7wHtwlRebZKbukpyr1RlFsk5J6s9GTlflR1auJZW342",
	"E882UtWxxb89acH7DbDSO6Ux69oLRjj0t5vhycp7IGu5nXuq11O9Xrn8SDpbmLbMWmi22YjOnt1m6umF",
	"uC/cIFveOPviKO9nMAH39L6n970xsWFM3EtYnspFBjPrDL945mKYg6P2uGrm0ufnVBkeFylVJeF3TGOV",
	"YSDop2cv9xYf8jXePeyj8r+akJTqUPfBKb3Z6QtkjyHTqzPJjT1sK8L6H6+IHt+YuwFlt3Pq/Vj9ye9F",
	"8T4QbjOn3Qo69azrCspWRGpqKxB8JX6xnkT1kbN/yMjZtdxxK4hG6Ia7C7LRO7t6UtaTsl7a+iqIZ5uP",
	"DZO5r6cYnq26tLoV9bTZIr8OV9YXRx7v+b57T5B7gtwT5Hu/amzdXVUloE6VWZcldjZTnlvTAWzlxep1",
	"556+9brz16k7b0Y9Qi36C6QfvQrdU7Seov2xFdrNCNrZ7RmSvg6S9vWrtT3J6pXMXsm8DyVzqVz76jRW",
	"CdeGi9h0FXlvVNmwxY0nExZj6TEsEhGU9W7mvbpcmk5fxOAPmsj4KYLWSKKlMkv14T2AcVvHnQGI0PKn",
	"RW3YxGachpe+lHpVgCd4FM+1Po+lwopDxTjlesaSY2MLsZ8mLdV4mis4h4lLlTBV1n52c+6uHpMw1TFf",
	"6DssFoS/8OE6c+kDUL/sANSQ7C2eKVnk3dGn0WcRkKLPIyFFn0FEij6j+BBZ+eHgnuSz0yxPsaQTS8hO",
	"nchOGDWFYr5wKRMgYCS2FifXjiDsRp9V3olqAk9t/k2xZ1nSaZF+9uI503vvkcZ/2ONZ7up0tUpEZ0g1",
	"Sc7UCIthIcvEv7AQ7xhLuSqa8MJfMzm5fFLV/lOt9vgaITi1E1hDBa33THZgPHefZAgvR4f7h49GB4cP",
	"H+1GvrR+0EATbYCyW0ZADvf3neQmCMtyz3FBjfaiXFWeaydc6K6tbSykFZ5AxMCaqBxAUIikQx22TLW/",
	"UrLBes+c7OcQbeQQTckblPicqI11MMmYTWD5dDpVbOoL/lohkCXkmi1gf37Db38jO7WmdgJDEiCU+/JH",
	"rNq+ly0s9v+2G5FXpTTpqtqS3378bUh++xH//Q/411YENSNtFtATF7+RPfKbkAb+urGlji3tcPUfP6lY",
	"WTujDnRbSZP+XNji9DoU1BpvEFwvodNeiuylyE8mRTrm0YuQvQj5xYuQdyvEuVqkwYWobotWw5CF5NpV",
	"9OZimvrSpgFTLSu9+0qwDSnOEvsNbVlIXcMis17MsL31t3J7Y1pvTOvFoF4M2kgM6u1on1kIul9fYy94",
	"fTGC154usoyqxW0GNCtFWG5BXBtnMKtLYDfczGRhyIQ50xK0nBRpiuYvIJRrCmOLczezL14i+3eVUD4l",
	"+e/e7zM3ZM8Pen7Q84NPzw/Q0rmlHu5s1SxxrMC6WMYL98ftOjiap+9KBcfOeg2818B7DbzXwHsNvA9n",
	"6cWuXuz6KsSuu9PCreC1pRLekMY+Wge/L5GsV8E3PzGdu91r4D0r6FnB/bGCNYl/eGdjdMMTG1Bo72kA",
	"NfOM4faQxYqq349w2dOVPtzlj3TGPwwHth8rKxUqHRwN9mjO9+YHA+DpruPlg/7Kn1oN81m+pYoq/FJ2",
	"+aYoFPQBgmF98YqBhKNRimmSE0uHeG2g+tI/vP3w/wMAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../v1beta1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
