// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/core/v1beta1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9+3fbNtLov4LVfufEbiX5kbS39Z6eva7zqL/mtbbjPefW2S1EQhI+kwALgHLUfN6/",
	"/Z4ZACQokrKk2I7T8pfEIkEMMBjMC4OZj71IppkUTBjdO/jY09GUpRT/PByPWWRY/DxhzMADGsfccClo",
	"8lbJjCnDme4djGmiWb8XMx0pnsH73kHvjWBkDN8RqYiZuh8J05rQyUSxCTWMXHEzJTGb8YgRKmLCUzph",
	"JJK5MJqMpSKUHJ0/G/b6vSyA97FH3cCe4qf4qArdvSBcEDPluhxJOYqJknlGfE9kNMdROnBjqVJqegc9",
	"Lsy3T3r9nplnzP5kE6Z61/3emIuYi0kD8LdMDWI+YdoQ3whnetNgADA3LMUu/0uxce+g99edcnV23NLs",
	"nOeJYIqOeMLN/AV8emxYCoNyw6RK0TkOEiC8pimrjxIXlaTM0JgaOhQ0ZX3C0szMEfMtSzYscaGN4mJS",
	"QIF2dShnKmfkasrc1JW8IoplimmYkFt6TYQ0RF4JuwzUwg0gjaRMGBW96+t+T7Hfcq5Y3Dv4JZhdOIZ+",
	"jTyCxXpfdCpH/8MiA8M/zPg5UxoHvDj+w7fH7h2J2ZgLphEzM/uMxcSuCZFjN0E/OQodwGMqiAU1JKdM",
	"wYdET2WexCSSYsaUIYpFciL470VvmhiJYBJqgIqA6pSgCZnRJGd93CopnRPFoF+Si6AHbKKH5JVUjHAx",
	"lgdkakymD3Z2JtwML7/TQy6BqNJccDPfiaQwio9yI5XeidmMJTuaTwZURVNuWGRyxXZoxgc4WAGT0sM0",
	"/qtiWuYqYhqWiYk8hfWY7dEkm9I9XA4+mZrIJACteP5+kXj6vQ8D+HowowooUEM35Xqclx2WD5/7ro/l",
	"edDxh8FEDmqkeUQNTeTkRubFPtA0S3Cb0IAcWubR711yEfcOiu77Pb+RoAeBG67H4gkb0CzTMBCdsQjJ",
	"i+ssoXO7J3vP4gkjh1mW8AgJRiONLzC7Cnku4wsBIV/7IS4S9M8c+KwmlFgkWYIp6RYeAemdPDs9I36V",
	"LW1bMg72b0nRQI1cjJlyHE7JFHthIs4kFwZ/RAlnwhCdj1JuYKv8ljNtgNiH5IgKYAIjRvIspobFQ3Is",
	"yBFNWXJENbtzegbC0QNAmW5kceHyLluC2d6IGbr3b5kxQTP+7zeIs1fM0JAIlvXgSOoUmsInhppcr/qR",
	"bbzIJwMKcmQRTMiNqokxul5RuKwn/YMvQ35PBaElsRPD0gxYnKUXSiL71ZAcG5IpOeMxAxkxpnligFuO",
	"+SRX9lPL5oiZUkMiKoBwolwbmSITRIEDw3XEXAEqQwnzxWy1TyHKYDU2oET4zFLj7ZPVoTJ8TKN1lctD",
	"Qaj7kig2ZoqJiA3J2ZQRgEbGnCWIekBvzOHTlAtqQKME2Zlry2oE/y1npW7Gil41SbhuIBDRqEq9yey4",
	"yTRPqRgoRmM6ShAy8HoCXzmlCsjBwUDJ6cVO7x9Hb/65T55yfUmOQQtuWm/7YOVF88g9g8+u+71c8QYF",
	"x+Px3ckxYkLmxqs35LecJnzMmbK49Y8LlJMtQyegyVp1dxupHfYaiwk1SNNJbncdT1l1wr/ldA6sW7F4",
	"Ss2OmrJkMJLSRIPfInm1D7TExUsmJmbaO9irYWOBFvGtneKKJHfmkNmCDmsBVIlnSF6tSjnkWERJDvzL",
	"zgktm8Eo50nMFJG5yXIPo6JCgfiiXDDV6/c8HmjKwTLQEv4WNJIipgP7c5bGl/DfFPaeole9fm8SMf/t",
	"IOb6clB2+T7EfwhpBaWsBYNHQS8tTf7hptHy+hBn1/LyGGfZ9qXDxdJG5xZDbW8RcS0vTxCfLS9fIJqX",
	"TRn2come91UqPKKGTaSaWwpECQd2Wymneg0iFb9Am8KLSgL2Ykg/eq5BWvcrXb1fd4U9rFPfW8O7wxDA",
	"wuS8qB4lDVvsqCLIkVVXBTkIDuA6yENggiQBPY5s0UIb0NvIyOWMKcXjGKR9ybWw9ZA42TSwHzuFYZwn",
	"CRhOWUIjhp1X32+BFpoyNWHxdp39Wx2kXVgZlddVoSa9ZYuJ2TlVuk8yqYzuk5lM8pTpfqEH6D5hJhpu",
	"V5jmx577Dv58+ebFv18+O3/2Ev0SYwl8DnuDxfx+9/vdA/gH16bGD+1ETlFmrDed/z5985rYD61FDFpM",
	"FCw4yaiiKTNgFsAamSnjCubNY0RBoMmU4wGR2SRZnzJDecJiEssoT71Z3ScZiiA6SsDsIClVl7G8Eo6h",
	"NuhK18tlwlOWJXIO/W+u55Z9VDReT80RicsGtS0caKUoTtFxMSSH1UZUaxlxsI7C9rh1plQTIQuHCtdE",
	"G54ksDKax0zBZgpGAF0H4wGNUyTzEAC65gonEK4kbA14wkXMZzzOaVLCEySimmnQvBVDUOjU45rkGihk",
	"YboBbLfz08IKcJ8C3koLQYrb19oDFtniIpOqMmznT2TkUfDpI2iCHLGP71DZQ3dQ1e6Q9lM3O5y1/R2u",
	"wsICDMmJ03GsNzTorjKuRusgKl0fCz45sMXd526gUWDphUpC6cJoB+DNw1YgaAW6CXMdzjiSSjGdSQES",
	"QFYgiwkXHxqhTqkQLGmBaF/2CR8TKnBFKCKWC8NEbDfOiBGjaHTpsBrMH7HZBNQbeLCdTNu+r4nsOzcA",
	"Z21uy1Bbry6xYzcOLXYtWNy7Sb9usvU4/BMVHrAqDfmhvV+V877k+la4L/RjkQ6KOMy+sZm+PT5S+Oyr",
	"o3u5FPyqvv5mSmtw9Xfuvgfg7oM1ty6W9XwllhRu3iuKOY17vY0SfIlIBS0JlW88YqtwBqk84xiSt7jw",
	"kZX4IOWQYWBPLCbWM1nfRinTmk4axGkhy1wLwj5kCbUa5NV0bmmJV2CA2nGFkkOSWBIutGE0rjoSzvAz",
	"GHvl2yF5pxlBMTLIklyHH9fW2xkEXgNsce+Eoj34oorArcCoAKWqqsH3ygHdyHM9Im8gi09jnEvZ5Wdh",
	"knq4AW/sOOKfkSNix0CUSfJm3Dv45RPOZj4umvqraM+mYD0jlkgxsUt5ylOeUAU8C50rGboaBPk5HzEl",
	"mHGHpqso2Qs484Oqo+X94hZ/5VCJPL56HONPbsmzD6AUa1Iiwpp9fno6khkXk0aLffFwYGMGBF9Xztar",
	"Bz11EdXAk7zvdYk/1/oqkNxLV3ylW/IUBxETKSL2t7qzW1t/9owRRqNpeQDBRcwyMC6ESeZDcjbP2JIT",
	"Bn+uUCz/Lx89ckOPLPrqCx95pmTKzJTlOvgTF31dPlkcuFyjf/3Yfr5XZ55R4KBcse/Cp3nd9z7NdYZW",
	"8RpiFxV1Z3UlufgKOgmP2xeJ46clxzV6Kq+E9WtYGoGF42LSzB0r7ql3KmkSdOISOAL74GI5Kp80djqV",
	"KcsaNSngQf4teXfystGOJZmSGHfS1DePmsxG6Eoqgnzj3clxo+kIXyI8jy4uyLvjRiDuDFc1hEi5NwAt",
	"y0cJ11P40QBuC5abijmGkTGa4upsN4LTU6nM0xBOjRuQkeJsTKRgg4QLRoLXTdCbweRZJpVpX2LXoOS0",
	"iNNwuRF/E2ZQ2ZiyJBvewnGfP+ZzjKuJGc4oT5DUfRvnnTviIuJCUMNJKmOWWN3ZqbiWX2aKp1TNCQir",
	"PtGXPNP2mF0b7NF5XtwbjFhKWcypKYEtsj33CfqrbS+9fm9MtQH5VrJd53dxrPGgp6d0/5tvD+hjFn//",
	"TUTZaHd/PGbffhfF8ffj+LsnT3a//fa7Xcq+fxx/+/hxNNr79sn+fry7y76j/yfa3//+m29GT76NnwRq",
	"v+4d9PaHT54Md3v9Hk4AhrQ/fPJ4uAtjKdws8Oyb4S6qC+Hobx70zPVfA/oYgVYgYLsNeHugbVe5efNZ",
	"aSk1A5q5QeFqPjRFkSfH1Y3rZB4oul6WhAdV0oblqfSKKhhNrPgMJV8oBacsSXt9EINxwgy+TDOpsT2o",
	"iWsfbMFI35z2anN6Xg5k4c1TP66F5y0Hn/DqJzvqhaf/KCZR68nPaRE0TrG6AIHttZrS2y5gaxpvQdC1",
	"Ezv3xipNXjEKVN7QYKtbDsvUjFsR8tVt16yGflweTlBTn2mGpzReycOwEiNdhHIl6mFIfmZzbVW+lBpQ",
	"DW1zLvAQY1hstCF5I5I5uWRzFgcBA1QxQgvWXCin3g1TPQC8C07oQw0sm7IMDtAV4m9vkTFUIy5Tmv3S",
	"chj+vuZm0auT7ymSfIN9AyoQyK5SmDkbXZSCq1+eUIJk9yIszyaKxgxF2RAl+iXPTqiwmtY647If1Qd3",
	"ytIZU0TBayCjQtwWx9x+DDFXLDLJ3Eb82vFb6Qt08PtAGwVKj/UJoCIxlWbMPyzakBf57u5j9sPecHe4",
	"S/BHtDd8bFfSSbSaNlDsk43Gt6LwB9E4wMPFZjWgh0Pu9Xt7wz0rbVcSe54u6hxlti6HbCWxU5ZSYXhU",
	"EBgHGw/jocgWG06GfbI33B8+7pN9mMNARXvbCyd2xRmMihk6m6iIC9xOFM2m1WX0229BYs8KR0nBpCtc",
	"bwV/wGF4HrTg8x3LJJFXfpssKoPuTNcv34UAfiVkbI99A1rB+eAM/SiRtSV0BH/iBpXafTq8EO+CbWhb",
	"xs4AH81L3XPLbvJtr3NupXlieIZPpLoQxd4lWzrYddtBBFaLCAxDTy6ECyWpxIR4I3Z4IZa4QDb3v7b6",
	"Xu/d77q2z7Xzt/7Z/K2be/mchw/ejBp9fCFHGhYkiSyhUHesFZrIiCbJfJBSQScsvuGs4p6cP5v5Uu7N",
	"jfK5PCif03myJN7rtLhQsQEl47dhfBfON1cK+Yx9W5GvdhKNkYQWeJO5FfTHFlez7HAldr3IHo483Bu9",
	"BMEIG7nCjB3hPc0f56dsxhQ383Vxaq95yjFsAcNFZMjR+bMixkqqCRX8d7vkozmZ8smUaUO0g9aAU8UN",
	"j2jSFHKa26i7EpJriyBXvPEJI1il75/4ZLpOv4m8WqXbl/JqnV5BAc/TVTp+hS3X6VtIwVbCMqwnHikJ",
	"iaf9kluDgacZWNVbR+enp0RHIGp3t1cEbqRpWuMzeLwAmkZKal0jpxUB5eJSyCux3kTdR8C1coEziysk",
	"eyPcRWcdzrZfErejw2KBLf24NSkH3bRn7X3Y29+2Pgq0uEzdsIX79o6z1e5n4QXmjXb06zwdWVHngV+h",
	"cbHIJfwNbNBAfW+ftN03AQzvPoUXbAIzkVefyCg2gWr7+iQusglY6OnTuEcAdZGqcVtTQxJGwWYSbIF8",
	"i3GIW2c0m+DCdfYweE0lU8FpnqZUzU8w4lezNfmOZ1dE225cZIDzAbqI+dszm9PGg1e8mhfcf0O70wes",
	"23g4cjgC1dAnPSgivl2EvmLChuO/ObXO5GaTAt48Rfdy2yB8hok7GkGzMX/i7XN4/TdCkys616R9rVts",
	"AHy3VpYLv/qu35WsWw+niTwx+0XTiFf3Gy4fX/8G4q6SqY0TsQvelM7E8yQeLL0mcqSZmpXytrgfse7G",
	"r4JfwZtok4dU+SByD1DfoyRHZuSCXxyhYlaX4VLc3wlnuJer3s37onWin7It2in3U/eEc4TXJreJH7zi",
	"1ca3sALUGKagy39t7f7vL3uD799fXMRfbV9cDJf+3vr7wWBr6+8HwbP/hX9+oYPfDwf/b/D+l93B9/5v",
	"bA49rNx++6vt7b/jR19vhW++th1VHmHb/2q8MtuUfiQ8JmrCa3lKhDdLFOXCeJw2HOkgfreH5DSjERto",
	"llFlb4Mxleq+jUtDdUX6kGUgebz3vuW6c/1G/g/mH/TJD33ynz7517Y7D/DZeJrOIXttg6uu8i+umW3w",
	"n3+9/wqQ+f5rh9X3X28Vf23/fWtQYno4wCcXF1/XnpE76HT7qzWWdBP/kXMcoRtcMZMrdxMUWVVEk8Qd",
	"vcVSPDK+hTTozcP9eYsnApGMm4gxnwCbZjH56ezsrR8CtC1PpK1+0Se7hI/xNqCui5vH+40qbnc2cKtn",
	"Ay03LA5rGSjq3tnSS2nxiAyiLQRRMaqb3cApjaZcsFZQxYWOAoC9hodjuOg9pzzJFbvoFUrrsRuQJQGu",
	"XS4yg4ePaONVrq4UARNDckhOcJgkSqgCsYSJZpCM3WSRjEc57C+fbaw87msWxsUub9zIDpcl8sgbwYgc",
	"H5CL3mkeRUzrix6RKpzpnZONzlg0oCIelDdz1r/U5ybu2ERBAf2lt1Eq6si6uVyKMI6KNrl1dP5s29u1",
	"QxJC4O64eJLIkfXgYgo1Fbu9fqZybfh4/jdYozmxx9WGGCaoMAObZy6Igj+D59Hc3h4CSerPoAPTySfr",
	"w/Mo9gFYiJL5ZEqupjyalnB+y5niLG5g1vGMa6nmxw1c8JyJGDRW1yRUr2wio4LUmyj15lyIrW66kdui",
	"R+fPhuR5ce88mKS9kOXU2b2/oSioIoIbn2dH1JwVoVlCVC6EjYBwVoy7YW7h265D38ngCrZnHQzaEaFn",
	"92oqk43cLhsL0BlrWkagw0XNGKY22N/dfzLY23/8pPnQLZppfRpJ1eRRPz89JSOqmfOR18mhmOY4kdSU",
	"3dvFqMW11djZVCpT2E2Oq1U2Yrt74mbvyJa9MKfIu5OX26UcrlLZJv6PNPfHCIuekFX71zpvMnVeh5f3",
	"i/2Ijd2CnoCGRE2fvD5/um0XpPC3rehEuV2t59BuzvMbFy3h4rL5mNplmwQCjjHhhiYZnbAheQvqEmaj",
	"dNMmpyzK0dbOpDI0wV3r3zmEcab7Vne94hqDJl+fP20+2HZH1vGhaQpPc+h3rTCF1ALCC+oHLW0ADRpl",
	"eXDQsbDc8H1iM296JwKGK4WRykelN/Qn6w195b2hL9Eb+tp6Q9/VvKFriF3LU4Kx3ihmMe/r2rIW1tgf",
	"xDgeKgXu0RSVE9hQuk+odhaAlRLIwQc6kpm7k1tn1FXpjfFMXt/WQ/IMLFPvpA6OzwG23cRclLIUR3lF",
	"rTwGSWUDsNbMAbxwILhM+vlgdZzhlyU91ktDXJhywaQB4aC3zMvp33IW4ltkg8387oVPn1w3leiHo3b5",
	"+pM7R1mUs25n0CQpULeasE3ph7fLmNpLm9CXNvK2m6BuyOT+KVV4VNQApUiTXaSh/ry874Z8zS2Et6HZ",
	"ATvBcybnOPYZm0L1oh84tgF33Os6znPj74aiLMXEgXg34CEZAq+bFHTc84VybhP0FENfgQ1+gdrrmCtt",
	"ThkTTTv0n0Wuci+EsPnCWUszlpZu0A1U2nbV+ISN9Y36d3BAVPB9JxBWYP0t1xFLrn5POnSntjYcHDhe",
	"7p14yMOqS3ynXDyk5QrfLolzNca9Qez8WzrhAk89fNB8vdsgenSrors2+Ri27zzYvhzy0qEWK5i5Q/kN",
	"1bDPp4K95C1M6+FEs1cGfezIdU0SPCk8HEYSKsibUyCsK6kuE0l9FZORiyUHc6lVGVi1jklFPrMPdCEU",
	"IOTnGbXBwyjXt4qUkqOEakMUjXmOZThWjbbcxNUzvDv518SIetXOV1j1bP2U4z+G+KsEGADzdUo1Ytum",
	"PS1rpzhl6xYP8FayIAtuUl15F2LxOb1ibVySqUFDaRwlr/TSQkErc8pqOaOVmWRzbEcDRX0h6stmJnHF",
	"c1Bx7DcXMvp0W3k1TXzFUSzVtD5dOq1hf6+LyHs1xQMR2mCVryhVb1+pI5VyQ59DV7tdNe1z3Z5sUty+",
	"NJ1tMdJyPUKzTuGqs9rVmxvNFzcpw3TxgNY8wWAXmx4eb7OHF7+AELY3uo9UXENajOQuD0+rI7idq0p4",
	"Q+mWQS6/xfRSXt02wBsvOLl7TbcM9oa7T5WKf/d27Wm2GB5ROnnd9HnBuTad+M3Xoapzf8g3oW4x+vgZ",
	"XtNsOgTzjslSTb01/X/h+tbSC/sNFzU/RddtD2FezdUfjqNpadpvrG6c6LPo4keqmzIfrZJorbVPm3at",
	"KcXWCnH0RS/+orsubAGMhxGMUJ2BGPfXgOt3g7kmh2+PiV+64VIkIgZqyw5PSXHhF1SNHKPMgswgZfJS",
	"hBaGntl0MHhLCpYHnSJxHB6kYDokUGTrmwCM0zNFhbbI5GlLukM0YtGX6vIHuLGa4lsW2xAQQJqL+0P3",
	"DBpF6xgDLcGVmDCAFPGOPom1y40NOPJLR0cyN27ExfAadSxvy7xgwkUSNs9+WNRpnRQtyxoSJTbASgI9",
	"BQy3mOTZyrFQ7YGeW3jhf5vYFmWmSQ/zkV5ppqvVMWyl25bKhkW0YgMZrRi7eBPIG0JACzz0bSDFmJyp",
	"nPXJc5QV5F15G88bcvC+1+9hg2X2WnMuu+roXF8LT33XC48LSMtmfUOGv4LSeBgQHczuMMuUnGFFibO3",
	"r84ZBuTGWMC1ePGUCfvsORb3qTfFAFpuE0JWfngm95YqjU1P5yLCP85pgvUoToBj5eZYvFVyomw94HdZ",
	"jBsU2mcs8k1fuUxCb64EU7rn7yw+ZZFMU65BcsFHqy3MM6FkkqRMmBMbSh7Mt/auOt0j4IZjTLB/yicA",
	"s95Fa5sCl60tCiS3tqgO54RlUnMj1bwR9YDx1he19QlfFmtlrzC5VcAfTatmVyNYO/sgXEH7ZNV1bCD7",
	"wlZtTJCEGbHLxDWeB1vGq+fCTJnhUeAawByAUzpjYbRAwrXzCc+o4jLXRQi+u9lBDkvLPaVz7MAamY6j",
	"fCwTdPeJH9h1Y1IRw0XesH9f0TlWVmOGcMu3cs0U/qYk4Sk3vj5RGcVrKx75MDBbdbosBFEIHxRgCi+X",
	"YggZYiiIzsdSND6mX2b0t5wVBaxHOA4syoPuZC+t/XUM7yMNbm4A5q37DzUfdBcZCcNUnM2sdiDYB2uu",
	"y3GQWLFA95FFkytLJYXm2oBOhX3BsNzlj0xaGvcoczOt5i6CeUdTKib2dBFRYKYUy1WxK5JykQO6cE0z",
	"qjWLLUr8ivvq4rZkaRF0hy50m5zXZip3S+tQecWTBIZo/f0RTTymHKadgYv+Uu/y75NcoGtxLnM7HsUi",
	"xgtUGnnJhCvCJQhTCqZjBWfL3ZDUFu+widXyptIZZxWK0vlIw8IKUy2nhYi30X8+WN9unyDcAtsUpxf2",
	"tgjzTy2x+FxRsY3hRH8qYlWzhEVGKo0VuhbpvJiHH1Rxh97Xr3PdeKQnbGzApHVl0WTKjWExiXN00Gmm",
	"OE18JHploLiOaZYww8gW40jpIxbRXDMX4A5Tj6a5uISeZPnWR+Ibrwljo+1yPoo51FkKXJyTnQjXnzIT",
	"f71KYglTpPHZ3nDvGxJLfxksgGGpvCi7BZMoKqcs0g3M7CumDU+R1X9ldxv/nblcSjKB9cNBHOG1raKE",
	"PsBVDDllW9+24Je2/nX7Aw9QV3VB3KgwBmUk6qVjysoKfFGA0CQhGex+vHXXKETsnuA+kSF84bgY8m/X",
	"NlKMmqbcB0JIQ4skU215cW/IhFs2tpbFvOCFLuFCvbgkjMdp4drQNGvmC4Ux5xzVYLvYqcSrW2sxS9gm",
	"sNwGwM/XgTdZYqgdEsvdooK7VNz0gT0cGHFuU8RMY9JQtOuH5K3M8oSa8h6Sres6JCeMxphOdVWvLCbf",
	"XJoWmX7waZG/fbxqXmR3GHHJ5l6zqZVj94LdxdtYoe8ygcPPLRuhAE8tf94Or7rWiKq58vbZQsFF2x46",
	"CKa1/03TvOSVaDrrPgxPUagh8kq4vNf+Oeh25AI9WjsA+6LXXncUpGRFzjcAFF4rcki1tfn8Qb4OVI9H",
	"LrdukLIXOaQI5r1CIrxFBvaWmmjqTAEYX3GetUYCC9my8crbn0YCtwNMheYijbFytc32in+lcoY7rxrK",
	"EUTfUTNtWjYsTItH50wRaNRcMREItaVeIqpOznkllU9BO6w5HWTWc8No8ifUkuppd3iPRXMttkaMKqYO",
	"czsT++u538z//c+zXr+HHhHoyL4t5zI1BiO8pJo0RYHATN69O35a7IgwjV5I0SwI6HpFM+csq7QvJdYQ",
	"CB3POgWWpWFq3vN7Ekbybx6UkKQZ/5nB3K/7tjCxT1tug25ARCe9g55hNP2/44RPpiYyyZDLskeYxHN8",
	"g8q6kgk5YzTFujiJw4E+2NmpfF3jVb9Uu3i/1fTZtjtdtfLMZuRkUUKBamdgjwk6Yb5or4vvkWNMWlxe",
	"KSnKHPsYMD28EBfizPtm/Wbdmu3RJJvSve3S34sPBtrYeCqvBFgNQTHQmVFiGenMDHsXJuERc2cVDmeH",
	"GY2mjOxjDoYqmq6uroYUXw+lmuy4b/XOy+OjZ69Pnw32h7vDqUkTJF9uMMHDAvoP3x5XylT4iSAlWj7S",
	"O+g9Hu4O99zmQELfcWkrC5YyYaYlGXGYyjU8vwozFBfcBCgfPztMkvBDhO3LT+M5QQOzdakxioaAWxsF",
	"7XRnnScmyBtgmW9oybq9VfYQJP83i60eedvtkdO+faCeYjN0B1RNm5ZNVtj2jjXQBtXtut+kkljbxxrJ",
	"0DIypUWC5o8zOb1maTUOrlzibqyLhWmwsXzRjKm5mbqqYE0Dxa9OHdR7HK3N5t33CWTRgHLJTwDFl4w8",
	"+uFRnzz6Af6FHfvoLz88KnKt9C7ZfO8HXLe9/iWb7//F/ti/6G23zRQhbjZTIKWUfuBpnlYsUUt5xSRD",
	"+7i0fc9KXwTqsdbwaie0yueEj6tkzj5wbWynC06GlM6tfVmtya8DuucCeGdp1iOGWimDp9xU8FRLHOJw",
	"0jvY293dxRoU9udug2mG9XbspJC17O/ueknjC7mX9bJ3/scdb5TAV6w1gtFMKMsWTLufgfc9uUWgxRlH",
	"DdaPNCZeQUOge/cA9J2guZmish5bqI/vAepzqUY8jhmedD/Z//4eQJ5JSV5RMfco1gD6m3uZ7alTO96J",
	"wk9pdXY60ZWCj9f93oeBVw9AHIRy9bpfCNrVhGw1nq4uVb3M/QzitJOmnTTtpOkfUpp2krSTpA9Ckmay",
	"6Q7SEfqeCa0JybqMtE19KRzrHWLa/Cjj+W1vGjvX0v1kVM6ua3t1727ANiEo7tlLLQi5ggh/C7+Kq6jW",
	"pKpUBKW2YWCOLY9kPP/rjnc/oZ8Vl/MpOuyPyuLcVWBx5fUiIMc5b4bygplWEJPy3S30XwYZtUE59SFO",
	"G8IK9Llj74WpwkoWW3zKAp1Yr2kr+lT1/cbTqsJpQ6NqarUhzOtOSN21kNq9DyF1JMU44dZZ34nFGwzM",
	"qnG589H9db2zrkfXxpX4Z0vNzpU8uYsnf01Cu0xXzOIJG9As016ZxuOb0hysSPJS0K5nb32CMfzgzNTb",
	"N0c/xUjrHIqdhLklCfPkHkC+loY8l7mIOxGzkeUFu8Q6Q1rFxdENVsXDkxfv79RMtKn3GuiinCpitQxu",
	"kUHc2L2bl23DbTAxKxZfs4kZ15ostWBwEYYYIlIu5Aa2W/NgJtX3dziSqgnUPBpVb3NnI+oMpD+i+Lp3",
	"m+wLMYx26mdvi+bRzkfYGddW4AGLakrwhNHgVdF3k6309AZ+9wUYSy0jqsioYTN8/G9tyXtHen07gXXq",
	"/B+SHz487tTogHmBN7vWYSovluktHUe5N45yg4bcsZWOrdyPqU5NNG3Kj2Wi6VqmOn7xh2cteL8BZnqr",
	"PGZVf8EAQX+9Hp0svQey0rFzx/U6rtcZl5/IZ3PTlIcJ3TZr8dmTm1w9nRL3wB2yxY2zB8d5P4MLuOP3",
	"Hb/vnIk1Z+JOzLJEzlMYWWv4xQsXwxxstaflZy59eUaV4VGeUFUwfic0ljkGgn468fIAfATlenRxBZ3H",
	"4AFytpBfVfnb2ocjSyKyny4J/F2bMYEuZsfUHUF0O7/ToroYpvXOW5bwqRdttwc2YlITm7z7C1FXOhbV",
	"BT3+KYMeVzpJWcI0whOU22Ab3TlFx8o6VtZpW18E82w6HsGk0KsZhifL7htuxD1zBP5lnEI8OPZ4z1eV",
	"O4bcMeSOId/7LVF7UlGW/Gg1mXVRS2M947nxJvdGBxCd7dzxt852/jJt5/W4R2hFP0D+0ZnQHUfrONqf",
	"26Bdj6Gd3Jzc5stgaV++WduxrM7I7IzM+zAyFyodL89AFHNtuIhMW33kWoEEW8V0PGYR1kHC/P5B/d56",
	"yqLzheF0+ef/pDlonyNqjSRaKrNQCNojGJd11JrRFb78cV4BG9tkwfDS10wua6cEj6KZ1qeRVLA8WT5K",
	"uJ6y+NDYisvHcUMhlfoMTmHgUsVMFUVe3ZjbC3/ETLWMF/oO67zgL3y4yli6jL4PO51VpSL4CyXzrD36",
	"dPhZFKTh59GQhp9BRRp+RvVhaPWHvXvSz47TLMFqPCwmW1UmO2YUS5a7KopMgIIR28KAXDuGsD38rPrO",
	"sKLwVMZfV3sWNZ0G7WcnmjG98xF5/PUOTzNXYqlRIzpBrkkypgZYxwhFJv6FVUFHWFdS0Zjn/obA0fmz",
	"shCZavTHVxjBsR3ACiZotWeyBfDcVYA+vBzs7+4/GeztP36yPfQ1tIMPNNEGOLsVBGR/d9dpboKwNPMS",
	"F8xor8qVlZW2wolu20KrQlrlCYu4U1uscQymQIs5bIXqZ8sW+SVqgidO93OENnCEpuQVanxO1caifGTE",
	"xjB9OpkoNvHVR60SyGJyyeawPr9i21/JVuVTO4A+CQjKtfwBC03vpHNL/b9uD8mbQpt0JTbJrz/82ie/",
	"/oD//gX+teUJzUCbOfTExa9kh/wqpIG/rmzdVcs7cHvfsVpZ2aMOdRtpk35f2ErZOlTUam8QXa+h006L",
	"7LTIO9MinfDoVMhOhXzwKuTtKnGujGRwIardo1VzZCG7duWFuZgkviplIFSLstO+iGdNi7PMfk1fFnLX",
	"sD6oVzNsb7d+pNDvnGmdM61zpnVq0B9aDer8aJ9ZCbrfs8ZO8XowiteOztOUqvlNDjSrRVhpQdw3zmFW",
	"1cCuuJnK3JAxc64l+HKcJwm6v4BRrqiMzU/dyB68RvZH1VDukv23r/eJA9nJg04edPLg7uUBejo3tMOd",
	"r5rFThTYI5bR3P1xsw2O7unbMsGxs84C7yzwzgLvLPDOAu/CWTq1q1O7vgi16/ascKt4bWiE17SxT7bB",
	"70sl60zw9XdM62p3FngnCjpRcH+iYEXmH97ZGFzx2AYU2nsawM28YLg5ZLHk6vejXHZ8pQt3+TPt8et+",
	"z/ZjdaVcJb2D3g7N+M5srwcy3XW8uNHf+F2rYTyLt1TRhF9IDF5XhYI+QDGsTl4x0HA0ajF1dmL5EK8A",
	"qk79+v31/w8AAP//8roxTzohAQA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../v1beta1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
