worker_processes auto;
error_log /dev/stdout info;
pid /run/nginx.pid;

set $base_domain bkeith-thinkpadp1gen7.rht.csb;
set $api_host flightctl-api
set $api_port 3443

include /etc/nginx/vars.conf

stream {
  ssl_preread on;

  ssl_protocols TLSv1.3;
  ssl_ecdh_curve auto;
  ssl_prefer_server_ciphers off;
  ssl_stapling on;
  ssl_stapling_verify on;

  upstream flightctl-services {
    server 127.0.0.1:443;
  }

  upstream agent-api {
    server $agent_api_host:$agent_api_port;
  }

  upstream telemetry {
    server $telemetry_host:$telemetry_port;
  }

  map $ssl_preread_server_name $upstream {
    default flightctl-services;
    agent-api.$base_domain agent-api;
    telemetry.$base_domain telemetry;
  }

  listen [::]:443 ssl http2;
}

http {
  access_log /dev/stdout;

  ssl_protocols TLSv1.3;
  ssl_ecdh_curve auto;
  ssl_prefer_server_ciphers off;
  ssl_stapling on;
  ssl_stapling_verify on;

  listen 127.0.0.1:443 ssl http2;

  server {
    server_name api.$base_domain;
    proxy_pass http://$api_host:$api_port;
  }

  server {
    server_name $base_domain ui.$base_domain;
    proxy_pass http://$ui_host:$ui_port;
  }
}
