// Package v1beta1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package v1beta1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/core/v1beta1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H2Lctw2luiv4HK2yvaku/WyHVu3tmZlSbY1th6RZGedyHeMJtHdiEiAAUBJ7ayr9h/u/cL9kls4AEiQ",
	"BPuldpKZ8m7VxGqAwAFwcHDe57co5lnOGWFKRru/RTKekAzDP2MuyD9utoZE4a1/8JwwnNN/7A0lTwtF",
	"zrCa6E4JkbGguaKcRbvROckFkXoshBnCti8a0ZSgHKvJIOpFueA5EYoSmCQPjnM5IdXXugtSHGEzDmdI",
	"TQiSU6lINkAnXBGkJlghzKaI3FGpKBubrrc0TdGQIH5DxK2gShGmISB3OMtTEu1GGzdYbKR8vIHzfJDy",
	"cdSL1DTXLVIJysbRly/lL3z4C4lV9KXXsTE5fU+EBPiby9k7O7JtKCEjyoiEJdyY30iCzK4jPkJqQiUS",
	"bhuxHkD/jBky8w/QBRH6QyQnvEgTFHN2Q4RCgsR8zOjncjSp90xPk2JFpEKUKSIYTtENTgvSQ5glKMNT",
	"JIgeFxXMGwG6yAE65oIgykZ8F02UyuXuxsaYqsH1MzmgfCPmWVYwqqYbMWdK0GGhuJAbCbkh6Yak4z4W",
	"8YQqEqtCkA2c0z4Ay/Si5CBL/iKI5IWIiYRTYUUW7f4c2Y2NetEopeOJilWqJ6t+jj42T6kX3fX15/0b",
	"LBjONGb9HFUH8r78tPrtpRv7iIeaD7NcTfVEd/0x7zdwohMD8kvoGMJmPYQ5X4Jwnqc0hrP1Fw4XUZKo",
	"F/1a4CQlKtITMYUpIyLqRROSZlEvuskW3gCAZ78c1v7wQzl62aOaxP702sxl/3qfRR9nrNotRo9DmNIb",
	"gNP0dBTt/vxb9G+CjKLd6C8bFZ3ZsAi6ERzwJU2JG+lLb4UBzkmKFb0xJEqPIMivBRUk0ZsC9OZj61Iv",
	"srwDIvUoFwqrwCHbVpTSEYmncUqQ1B3RiAugheEzFwVj5gCl4nlOksXPNgTWeTlcR4cLN8sC6z1kN++x",
	"MFS6RrNJ1YCThOq+OD2rdWndmPpmHbIbKjjLCFPoBguKhylB12TaB8KDckyF7CHK9OGQBCWFHgaJgima",
	"kQHSF+qaTIGEmS8IjicoK6TS5H5I1C0hDG1Bh+0nOyieYIFjRQRQmsbZL0Hiy705yvCYHNAxkSpA7hmi",
	"uh0JMiKCsJhoQHrodkIYumb8lvUQVVKTbo3lKIFxEGUo5TFOkVRc4DFpP5ZJx4T79YEsmTEwNEdFD8lg",
	"PEBygrefPN3Fw3gwGDwaoNNMP4+JgRFeDfjIgSZRwQDyQRTCT0sj+/Ka5n2eG4zo5xzenGhXiYJ86UUA",
	"UBv6o+ZeSUSVvjAEC6nh1+AIwhKi75d3kZDMSTwIvtn+lTfTflzhlM+4COy2/hVlOM81TlKmb3iGFbqK",
	"Jlwq3bhbUm3911VktryHrqJnm882d59tXkWP6nyI/V0fOFb6mY52o/9zdZV8t6v/59/aS1wAdsFvaELE",
	"CyxJCGOyjDNUoZehU2la2189qWyjIWaMG9bkPjRgTwypElhMUUYUTrDCyBt4gN5JkpRMSzpFwykgArAa",
	"PEV5ihlxO1vjFG65uE45TgAlH1mMFphJfVD6zFpLRFhZBENAYCKNQDg5ZenUIG8Ad3D12i/9QjlOwexJ",
	"7VG5x8PZ9VR9+dhb4q0CBtTboZ6+jxmXwGESptIpkkS509Cv1oZUWCiUkBsaE7R3diQH6JzgpM9ZOt1F",
	"MZyqpsv6u4QKEitznHqW6f9GuhuyDO/c644SktIbaLLsLR4TptpH9qUX6deyQ7bwRtW9yqdj63/++//W",
	"HwyUcjbuIbPGW6omCKOU6EuKuECsyIZEGGba3nrEOLrVbK/McUwGobsrCAz3ijAisAqKDPu80KiPKIsF",
	"0e8kSdye26+9DTfPn0bdJn+JQJqA/iT5MxxLuRv6Zo+JaFFrd69WoteW5l3kJDbvpd7SjDKsuNA/WKpt",
	"pFvDFi9zwywr7c1YY9GXG8p+VR8MePxlxtGMen0IJzwsM4oVCeoD3SwHyfsaHF/KR2N6AtewPNgvvYgz",
	"siqRCxzBSkJCYMUrjRM8x5VGap7kSoM0DmERNv/cCuFvaUaNDqip0zHtKIUO9pFoSbF1FiHOiwBNO3tn",
	"BtHkRIMlB+ilYZ40jRIUmP0h1g8/Z61nus4ybQ6+fxKirRnJuJi2Jz+G3+38QMcdn4oKRtU9INl+8jS7",
	"l+KodRSzTiHmTCqBKVv0KNLyXO/DUTSwZKXlaXakkGEdiWkDVReSlI3T+jNmlX7myfMF6DNBcmzlkAv9",
	"zJl/VoLwoRBcRL3onZFfop7mffOUKJLAJ0Yetv/SnywtgBvQfUBajR5krbagzG6aHOythmoxrSZ/dQE4",
	"3HLDTbD+BU7ynSSirRcQBduTYYarkAT2zsmmRnsLP7c4TqfZHBIt8aNCsxxa5qdSczOaaYER9GjYKFJh",
	"GH2nKQMtcPkky4DKDT2kI/f3MCWPBuiAjHCRqlJhaqHCqmJkNCRST/dwDEybFkgE5+oRoiMASTNBdERJ",
	"MlNAjnajd3YnFpabV7lp73laZA15oikCGD00Bv43QTfwhV468JltjVX9qMOs9TtGfy0I8g/aH9eeUIBi",
	"BTjkOMU0O+Mpjaf3pV1mN85rQzbZTlhQgOf87T7MCmg2zOw11nSlp/1YSwTrGgwg6xzx40KMQ+DLFkkw",
	"xx8gCm+pUVT5F9N21ghBFcnkes49qi4QFgJPo3vcqPMmWiaGdMADrUlO1Ou4ZxN+61GTCWZJCrfP3o9S",
	"7cZvWVNFASJcxm8MbXEPn53v4wqqIbMWQ/Znv8RroQonLXLQceWtAjDE/DjdoKXQCclTPiUJOt0/6mvM",
	"SCnWUipoErlA+rUd4VihIY6v9X7OnDtECnx4VhFF5UWRZVhMF+R56oo32c3vvCY4VZNp1IsOyFjgBB7z",
	"No9zwn1Yludp6uBXk3Z28aDp7BNgZ+odgmxNvUtzYV1HsY8VTvn4SJHsnIxm6Agackvts5UIUH1mQ1Ab",
	"GNaYZWH8CgzdqX8d4VSSls7VU7ODRd1CgjS97SGccjY2wpG1T4zouBBdMp75NszwuYGBFyh5KT2Npmc5",
	"Fpr6B+lAPMGMkTRoVqlEtjzBiiDbF91OaDwpzf1ArhRHuTnqsnNBpCG0+AbTVDN/QQA0kOFF+YyNv3N6",
	"t0gaXs5Np1MAusEpTZwXgNmkuBDCKFnBk6E0f/izzadg7mTsWiogFsc0fcwjfWXIBR3rJ+mc/FqEjU9d",
	"XSs3Bv3QCfsj2BmQpGNGEhRX36KR4BmsdX8vYHKoeVeswBSUn3/pRdeUJe11vKEs0biJkdlVa1ksF+Ge",
	"kfPDi0vkPBeM8GI201tv5aWR4SmibOTEnHKRhCXA5pvTTanmCmQxBA2L3SotjwzQfqmnNWicDNARQ/s4",
	"I+k+luSr+2iAgaSvt0wOwvoWY7xZ6VxOYeOOicJ6KGkJ2vIktwsFLYMcyZLXWePYZsy2/rpENYtp3h7Z",
	"Nd7/GpYa7hoK/yhwnhPN/vCCJQiDJNuPBdF4g/Yvznso4wlJjVbruhgSwYgiElEO+IJzOvCupBzcbA1m",
	"gtC+qOQup+bBuCAxZ0lQlQXfG7t+6eEExJCqaanU8gDR0xgrqzEc7GxHbTtCLyJ3SuBZFslSqmhhcV1A",
	"aLkr6IERVub+kFKrUCkK3B4D/dL7nPO8SLFntdk7O0ISiILee+ivV4410cmyQjWeowoxRBfh1S/SEEvy",
	"9HGfsJgnJEFnh8fVv9/sX/xla1ODM0DHWMUT63YGVvOSHFOSJvqVwT4+zKLphvDVjmQ4VSREG4DKi5Og",
	"VHDEEoNk1rDkcMJ8YyxqQI1/LXAKmhV4fvW8GWVvCRurSbS7FZi1oAHq/u7o4Hc4NQ8Iicchufcd/F6q",
	"i+C5ISAJX5MpMl95u2GffyplUX8ua0LyXHR26rfZwtnvsDENYulwu4Yqa6COHaJthXM418whTjcSwihO",
	"N0aYpoUwdvCivN+wdM+0KzsOA9FR5X0acJjwuoavsR2yzRX1qt1EXHPt5UEsdAE1Baalo0bLaci2GdGz",
	"Mt3aUxmgN1oaQ7HXURC0B1tHkh46IIzq/+odeolpaoBaXXVTQhRU2dQY3Gpdi2NL23K4Nn+LmrPNSgq5",
	"gN/dfcfp0BXeV5/ZJUuvZj5dSExfTcXJUsq6of34ZQnMcXh5P4QpxynRJA84TN1nYGNgb1wWFXanaHkF",
	"laNU5C4hCtPUGBo5Iwjrd6t0MLTCqnUecs7r+mU4L7mEuXsa9k/Tv1aER0tkBUgoaMTTlN9qWexNxa7o",
	"KX2xBb2TxPrq6NMCVUei+WH77MbGHZuwIgvYS7FUlwIzaXaUdvkQ6X6Vz00Fqyq/JYmR9/TO2YdFQ8K4",
	"mhBRo99asOvrscISlpRBx8nXRYYZEgQn8D7YfoiaV07vkTs/POSFshCX4AX5Fj6EVz2Z5ZukVz9wMs1g",
	"XPas9DzVbtxiafzFwJZe5GZan5l/+jjIzAuCZVht8nAoKBk9QqZHJS+4OR/IhVZ6H5nQTdUhA9qheyFc",
	"KldWHezyhGi+7r62Iz1AQT5Cl6IgPfQSVIPoXeXR67TLuj3qRdDB0ycvpj5uQGfHavzqhm78XM40d+kd",
	"IRY2vKJCPOorSbwlOvYl6kWXZ8fviQDZwqicXYNhbGAjNFfT7hrHREo6TEnzD0f4zrCQxq1gymL4xznB",
	"yTTqRe+1nKv/1oSsUEf6WRoLIjW6vMsTbN0E9CPluh4XqaJ5Sk5vGRES4LuhMTkgMc8yKiXl1oHgZUqI",
	"OiCpwr43guvd+PmQCZ6mGWHqNefXi9oIqq8sr+1tW6utvmud7Lo3RGef8kg6e5Rn1dmjDs45ybmkiotp",
	"8AT1wXU2tI7ZbyyP/C0eklT/dWzcDh0KwDG5w4U/Qshgjs1DCfODjxjml6+DHubnFpLMuJ8jOm4aV+7B",
	"a76iKjDmSpxgxSlckFgQtS7ecl3wvVYqD401a7PbTof/2sIMeBx9k4h83GiKDzkXIf9NP1xlfb4VEBoT",
	"0DQJ34VxHQ6HQV/DxTmmvHADHXOmqX1pNS3vSn0XM9NtfiRnZQLiyH40X+Hljx70Nloh2rG9vBmUQ3B2",
	"eJfrJyYcdiA4Q6Ts4GKbNI+toUiKFMxgNCNycMX0dtgeVKJPf0X2/z/toj46pqxQRO6iT3/9hDKrf97s",
	"P3k+QH30mhei1bS9o5sO8FRv7zFnalLvsdXf2dI9gk1b297HPxJy3Rz96eCKXRS5viUkQfrIseIaiL7u",
	"uFuqyDGbWtOfDS7Sw1CGJhrkcjxyQ8QUfnuk5/3U/7SLzjEbV19t9p99go3b2kZ7xxpLnqG9Y9O792kX",
	"gQeU67zV29q2vaUChdrWtpqgDPbQfLPxaRddKJJXYG24bwwwzS8ujBttfS3Pqi3RIsIz75Mrdmh8mvXO",
	"oc3+s97W0/72jj3SwcJBaPuFVDwz/MMRG/FZFpmmbAcGKxMjn6AYBnJBavZUgnA0dezeIJQZDAXtNIjB",
	"dceaxegIsEeVTFzJX0s4X5xhKlDMC6Ykehg7N90NxRVOH1m7eA4cGERtmpi2ATojop/rT/MJlkRfNC3M",
	"NQByfKNGBaZQTgSSiuQ98E3F+u8Y/M4IFmpIsBqgSttjxVCJYizEtHKubYBoQQ9ot0uP47Z1AcKj9I38",
	"hcNpeMoCCPK1mRsEQTgVmj1GioiMMpwuqCbQEvY7YxgPkGtaGTdAJdBc0q2gftib3f3FVTMwyqxlF8Yj",
	"trVssOt0zNi12JYOvHL0NnB8XBybc8ISwuKplk4M63lORith9cyxfBeQWvzYiLIxEbmgrPIIAWplfI6c",
	"6454IBG5s3krknKmEA767PNJZ+BfzYOnPpUNjNYtY6oQF+j15eWZ62Xfev39oyAJ8lYUntpfsoWg3A4X",
	"CW5A0NOD7KbQxeu9no3V1h8BREOeTHvozTOJJIgzpbbV+h2E4fMuyp5aRKPpwxtP9NOWoId0QAbOA9Me",
	"Rgn8LZbOR+XRoleobddpHuOKSL0GXA6jsJyyeCI4o5/Nffa2yejJ2/hKiXWnNa9OD8U4VwWEUbbijkNo",
	"fU5GIb6eiL5p75co7J+ZZiLgRK37m56hB7rY0tnYRpAaEO4pG8ymKav7YBs+YumDtAvzHNDyyVRSyGlQ",
	"OdW6GK66g1lX4hnjN2YHj+quTykekhR2bpQSiL50ruFlIHI0erqdjIaPR0+S7TgZDp/v7Dzfebo9fDLa",
	"ejbajsn202fJ90+ePn4+TOJnm5ubO6NNsvl4+/k2/p6MnsU7sGnf3OK+ucUtfiWdwvCe9g470AoObx+X",
	"u+atqLS2h/aa8i6QbEiSJMQ0/jghakJEKJLefeTccoacq9hEHXhIMOQ8JRiuFK3SxMi5iU9kOxKukCCQ",
	"giMOFSZ3TCNtjGznjXGZXxzPNarulzPZlpwHBO8/VHisGR4z4qOBl/aFL5oXBv2oe5QzO3Yeu66CjHru",
	"374EKsjogbQNa9NO+el5Akoq/SyCAHWP2wDf6ymn1RMXdrFqmGl9FnR+GBxOph2cbCljeNGOxg9ei1Nm",
	"9xeOtoMMEXKWJOP6IGch7oo+Dphy1xQXSiUSBYRH2ZjQoxEapphd94JpLwrm4kNBnIUx7Q8mCqsZy7n2",
	"0M1eJOnnAEYc3uUmsZWRQhN+y1KOE6R7B5OwOB6OMnR0uA8B69IKC1fR9uMngx10TF9cRT10FW2hV/qf",
	"j7SIn+WFnsZtQ5G5YCNHwO2FBf2Cnl2ih1oeZQp9h5hxQfzOxeU96qFCGq+CVGGU42kFdD2sQtOSUZGm",
	"5eheT3B+uKX6id4bQm4R+JZx27ncDCorKCGH2rQJNYw3KzXV/V69cOT6l153UGNlfrddysi55oGuOcZx",
	"BpcdjGwzdsjy2vcqj4XyXewtn4ml9YbXQ7dC+j5pOrjrP4FAs0ZcaCAars4SUKtknEl2fT2gcYtxnCsI",
	"SbUUD1/NcWR2gGCHG8mS+7+PczykKS0ZpsXFJv9TzbYbVbn1+LXCYpnXp34GXB7zZDWu7BQ+LXdgqbWC",
	"mNmFXvuef1rlFWPXYUTn9kIcZ9SZzPXcsU4ucKtr3Hmuz/V5Pi69csnTYB5Kr7mpvIjtzzFnjMTWT6a8",
	"F+3NkMYMdHQQfr1tMzo68L2wGjOE75D58tiTkhqkocTacpYyTZzlajTc1nH+32t5I2PM/DBAyqiiONWP",
	"hfIzsVpFc6+EWXH3WQ8R1ZlZsJ7OqnZhG6vqeRu45Pn63huhZDYuYx5YNJxmCSV1n4/Sk7t1sAqLMVH3",
	"Yn+rmS5hsLDvqZnnHov3Bm+/t2UUhbmAJqtdcxMyoiY8qV9T3yPsHSPg5QL+XrHiYnpOZA3oWQ5RsyD2",
	"Rp7VrT7rvK1piB3LUfhzIou01D97af0sUwe53xBWimS5qlhRp0IEkNvYNMJpOsTx9XmHz+aFr3T0J7Xj",
	"lvORNIWQfSOwYguUyf3t8ZNFmpbcI+RfsR1vsXRjGabRHLhukkUcE5KQZID2U4KFL9IyctcGxS3drNnk",
	"/wureubw+HZ+4FVr7Psb+qKn2faeZth7GtxL+uJRnS0Gtt2yuYwrNCUKdTG7S76dDdeurke06oYmup+f",
	"1riTI5MM53LCVyMwdcAu3FDLru9IC6CCqun+hMTXXcvr7ttS/Ne4COq+QLH+BOVE6PfIRFauyKz2g8xq",
	"ZbRuzmkgWjeP2r0ja2RSO4ef49K8xLZX5N0llXjHpPP/8H17S5/QZQh+aAHVTLP6+DB09yuh6+5Swb3g",
	"Xnd6jVshrAvDWy9nIyu1mSUhTFE1XTPOgRZ1WfmuujIg21UrmSPZ6d7lrga9CaTCWV5zKagGv4EvK/l+",
	"MReC9d1Um8fNHKbTVag8W/uJrJcCtMFemAZ0snSem3d5kcJ0YKU737h/vXB71xWeQyzadGLO/X7rsjiv",
	"JAeXOaDXoFdp+lc1Ekx/rbeqsQFrfKZCI3dhp1/hI7S37ffIMDoWRZrO+v4vS+JpA+ompjWaa1AE2kOg",
	"zek2H2dPZdsPdzXn61MRSrjUco4GLvwoXIDg1GUVmlCmdiFXTS1JkhWNXE6xVhb6B9J38BIk5iKRLgyP",
	"gK17SLyUk3pUASm7P4FA88nZ56i0mPNAlpY6Y110QkHCiREEaKYFtVLysdmC/ue//5+Pf5Q5HxSVTlFC",
	"ZczB+h5jllAQd+pLczYF+FWivBimVE5s7jfrjgk+WfyWof2jR0iQMRZJSqQswz8hoYSJCddioTTyXCXC",
	"aeHN5BYHyY0ZDb7szhcwL2z1kIK51gvuPN0/ahbgAPEKz8p+1cjDZFRIgkie3hg1Emb1gQfRXBRfhR6f",
	"XgQIcRhv39cVkKcXLVO0l9RqVsGSSz19rXaIG6tRLWQTioV0sU7rN6kGK3nUF7MkRS8DtZY6mzKqYR4v",
	"bPNer7gBdeDKEhFUXq990CpN9hqHbXrz5UVUzmTXca/jmh2UIWtRGeYA66XFqjyGP2JhH7N9QRWNcRpI",
	"o7jMm1sH1M/S2G6tJg+1egCFmh2Qoba5UbSeR1CHJuTCFHPQDUPITtOF6b6BbrH0rs5LcY1BSPVoq5af",
	"h7HFdEPX8ACW905f0g4HDMEkeUo6/CFSt2+xojeVNcWaEe7toulbjoJZr+qs3nrMA5BW4D4QW2axGV3W",
	"LCckTOxPSQFsrFU9jeU9t7ARbRXaROPCkiypmL8snV8SyKtEwR+sFlnWiFPDKp6cmWpRQdO6QyXoiGxd",
	"qfryW9Z444Pv4CgYVeCu1LMFE0ySdS3jyWI0oneWq5ITkqZ9qaYpQeOUD91kAD/MjseYMumnt0w5ToiZ",
	"AmDK8J3L6bX95GmtDtbPm/3nuP95r//T7tVV/x+DK/i/n6+uPv6vq6v+1dVfr67+9vG7h/+xWL9Hf3t4",
	"dTX42XQMNQerbc13Xjb2g3skLPfive0wZe7YZV7MFR3fq099vXdYuJdehmj7PCD7rZZ1lMA0NW5WsSrA",
	"L9Hmh7nva+JcEPxaAd4zf1/K2PY+DVxv3HbhWM+UDWcZfcoNT45VCb4/zOJJwUo0MHnJwevP+ePoowxm",
	"APJP+KskAvMf9dUfwMppBF69WijdiiOH4gNhcD8sYg2RFdXQpJGbYfUdCZsCQfNulZLr0087YfGCELZI",
	"GJK98yaPEGFl4TnzRqKHJ6eXh7sumM4GilpjqSCqEKyWs3DRwCTr4fmL5KxPx4wLUrp0lkq99Wks18Eh",
	"lQPdLwI/KCVrrubepK5F3gyb4SKEVx21GqQ25MW9ox2aQ9VZu/ADVeOc1vM0GTiSd4yq7kepqCJg78V3",
	"JB2KF+/JqJ1b/TmMwq+jj5I+SSlJOSB/tYgK2fzLtqTiYHXPU4/oTLBIbiE4mbmMAZSNnZN6rXr5+j1S",
	"LQwucdxX80kN7NcaLShLlcEIG/NOIdlOuOLFORlybvMjnfFbIkhyOhrVrH17t5gqyL5kfRJN9rFRSmN1",
	"hgu5pHGltiAPtFabB22gta7GqTX5awo015YZaG+ae2qNoc0IdGvuz5wzrhHyxVI9lDYXe5m85NrkLuey",
	"erWNw/EVO8TxBJIkx1wIInPOEmnV+E7AN7fKht+W3PN0cMXmJ40wi6hdypinqfHhKuOnOuUXDWSny7Dm",
	"avYg5MQaGYJ32A857BjD69Hhnx0cWeNTyIf3BecKHR0sO1TcuVBnkfAH/GSi5Pp9u/ZPdQ83G0NnrVpM",
	"KpymlfOeM8rEPMuMSYmmYSuysU6tzE20kpY4weAwpWPIADcjULC024HdKOZMFhkBa5GxpA0g8aJX5Cmm",
	"fWN5G1KmHyGTCUJvysBkZzR9qbIb06jPjhniaUKEjWMqjYJm2230PkmTcFDiOC9myNivzt7ZxcjSYhhy",
	"r+pQIh21NAbYG3LmiI0bJeJJ+Bbo4fy70pERxjglhYc4g6MBiKq88K/O3oUzOxCsp5mjsS3dNQA+981y",
	"adopS8hdR4Zw3eRB6sC3u2ioaDj8zhhgXkxV1xJwxgtWHr7pjqgWtZRZwQJ5WKCuRPd5QXOZwL+1EXlM",
	"95IEEh92ntewkAibTvNOTJAbCm73M47f9VkAAW4IS0z96PDiTHv36kz7LGDsCPNACakCmzh0fRMoXvTm",
	"/TG6oUIVOHV5K/yHrpv+N4p7MP3EzoiZDs0jnTFD028vRJCFn5qSUIUWy2MKmpblHqCK3HY9QlWP+z9E",
	"pZxgOIrwoZ+WwsSFEyYWfoLXF2pVC+P3uY+SZWgvp1fndZYVBwIC+hJ66rqoIDtZNtAMW4v9HE91K6Sv",
	"UVNA1qUwqcatq06aglkpLZeLueepLB846G27HQH2fVjQVPWpqQti07n5x9UpQNe5uS6RYkVlCiy0od9q",
	"59Yp6203lgYLs2sp/axqMXStrZcLCUh/3GrKY2rfqMB6mujnq4O8c1sdB5uqm2UKHI7HgoyxIk39zmxa",
	"YbQ/XdThvofzlVQrLVPhnPi4HHrCgWeY4bEJ5QcENqo32UOUxWmR6BZ4F+3vXkVuF55PEvOem8oxgaAA",
	"2+/CZA1d7bkyKyyHKBWdax30yyq7nqzk22egX6ujta8qdFF6X1lVWNuBteNzspqrdbW1pZ91fskPMNRF",
	"Oi3U6cj+20uovoqfVw1Ib4pAqz9r8ONGZvd661xXLiqv56Y2Xk824d6fLEdykMhZfwCgbmYAoG9UXpuq",
	"au1bl2M16fKFFQRCcpHu4wEPw9fHnL0WmCNQe6fzVItZRVcyfEezIqvqJuI05bd+Kh7znCleZjodIFiQ",
	"+6Ai5K4CHWSHwQhqIWgpzcr0ttCO8/0Gc2zBqBqgKody+SMUBttFn6RJRyxN5cce+pSZH0yGYf3DxPwA",
	"uZThRCo3n4d/2/15q//849VV8tdHf7u6Sn6W2eTjvy2cdviQxVy/XIuEihPb1yAqJAqAk8UKV34PJf/j",
	"KEqemgrvpujiwgUzzFRn9mP39ws7SPdyfJv8OVFi6pedrwd1K42q1fOOGSL1sF2LGe1LMMTxNR+NDkiK",
	"pyFtHqROQLYXSnS3CpvKDEQS8g0dmIyHoJU3P4ZVyGawrtW8sHNJJbAi42k5C7kzJIziNDBdrbVDJYgT",
	"MNe0jRE3kAYKuR5mEyFNkt5ZGxNeZVza2swCEMCv4WSA+G7PjhHI5WAvNfNSbfmz1qd50tNUAG1vWqc5",
	"/Wm0u70JVTHNH1tB/Ry+sxvbDUF5yq3zDS13O7zahdmpjjDvQJY8VwCRcda3KW9jngNrXx/kzF4BStJE",
	"1rKsunqP3XlWleDpWYoZ2Ys7fKNOatPbpK72yz4EAtlb5uWztJcyBMHqLgHhnTNwh1SCtrjlPXwTX/oj",
	"BFm++hwf74cEdilzTgAQIEDqIEmypXfo8E4LNEQiXKjJxpBgQcQlvyYsxIUHte+ngo4pw6l7XI0m3uag",
	"MefbkfZOX+M1HLBP+/Xp0ozwQoXjk7VY0Lq+O5tAn4NlakWH0l5v4gV6d/4WmAmcpvN5HbN/ZswVEKCz",
	"wHyry4zC8uUl4xYtaqq/1fL9tkGsp3e12X23dpKnO9vJs6c73+/EGJMEP32c4MebT7ZHz598P8L4+8fb",
	"o/j7zSebm9tPv3/8bBh//3zz6ZP42bOt58nWcNNP9RpLEe1Gff1/Lw5fHZ2g/cPzy6OXR/t7l4fo/PCH",
	"d4cXl9B6xY6Pjl68+GX/hfjh6MXewYu3x++ub89vPxy8/+GHg8PNvbvj7R+2jz///fr04MPnk88nv3z4",
	"8WX606vD7ZNX55OTg72tK3acfXhycplkH3483Dk5+Hv24XN8e3K5d3v8y4edk4MJ/fA5fnJ88GHrw+fx",
	"4+PL9Pr4x6Pb45fXt4e3H16/4T8dXbHPv2zu7/3w4Uj/9fmXzYO9H+KDH8Z7h69fHO/vbJ6c//3y7zsn",
	"P56mhD7/8OP1i+ON48/85ODV9Pj8TfH5cHPjisVvrqf/+f7v5O71r5t3R2x7+8P+ycnOTwcnd3e3Pz59",
	"m/4w3qG/vGI3F+qH0+HTvb3jPf5qf//XVxfHj5+/2Dvev2J7m+O948N3+0c/HFyIO/r0WiT7b+K3+5Pk",
	"+MXO7fdHv2YH6U+T88NXw9fH+4cX79lTKc/2jsY/vf3uB/F3dXvFnp1/Jx7nFH+4+elaCXm9M90/Kj7v",
	"TI6+T/mH7D/PdpJn/37FYNsPTw5mHMm3RM3fEjWvSO/98v7309W0x1whfbNd0+rUfM8S5AWouutaVZ8N",
	"a7xKGu+5m/s8QGfOM+zKDM6oC37rJX92D8sESzQkhCE3QNitosoA36Xgn+OBBOUCgbmGivA1+yg60mJB",
	"nuKY2G76MoKnyEObaP5RDxkQIP9vRsSYJLYI7pgw5YoEJK6Xd5VbexecDvLd+XOA3IxdZkGjb0AjanL2",
	"KQR+05rqBOcPGkpqc5pzMkn0u8xOwHxXx9beAC7cQhLNGAE4FoFglV93D5fdMlCpB2eCokDgiJ50GMvr",
	"l9qi+v1vrmeGWV2t2E0X2vq8OZDMIw9ecNJ9CUVXnRTQe2Fls237pAIS0HlUYrEUQO6LF9P5RWts3wXU",
	"qN6oPX9JC1QCn3cEK0SIBTa+uoiLY2XYzhXsZnghr6MBp9X3gZ/jL2SdAWY86LlzeNwHTSJJ0Nmb/Yu/",
	"bG2iuCo+i6SpPusjWoef2sW6ajP0IjAbnM9LYnvpVx8KJ7IF2mZzag5+kVqedGnOu1JA3PMB3DMP38jR",
	"vLKcuAv2uaVaoIMUlYrX/C6tu6T00YzK0IvtOROtx49Go4sXQbXSeGf+CCZHZzsGQ4p7kPP56R1rHZe7",
	"4q1BumiqYQTX93x4sZLVvZt/WfXFJIl/VzuqG84IlGxGPuo9Ce7DVwmD7I7PWRhF2jq9QEoIkySZaAZ4",
	"gm8oF9YB2TcqVL5wzlDyIuXxtQmzUJQVZEFTSQ0iN0btx2rAzlXRlOybAilhPHDVUwBxRzTt0AZ3fg9G",
	"IKTInUIP312+7D97pHlMYxIqEcybxDhjp50Ypvs5m9CKl8Ozey2uftcb1Z1+W7eWCbfbOzQWvMi7ytyl",
	"kBBL9+h5VkZi0zTpR9kwNAKxIiOCxujooGlcEJyrkHlh8cobmaXtnRDmGrVtZnGekAH6wAtQdxiYpzZZ",
	"sSBohDOaUiwQj6FoJMgDKCUYTIifieCuvOrm08ePAR+w4T1imtkPjCd86JvH25uPBuiCqIImG5Kosf6P",
	"ovH1FA2tabVyLgepgnFVbaypfdJYDChD9Tr1A1ntqwYvrKsuJBEzd4vfMiK+6nmuUmBlKWxfg3uET11W",
	"qtZcu3WrlTMfSp4WipxhNYERWu4GJVlZxvEgXG6/VX1rTNU5GXXxk7Xkaq+giqWXegXYOCKWccRw7hde",
	"uU5reDkn4LHAxbQjAsA1zxepqqFKtWhwTCMlnNu4ga49sFEFimtZv1IQzIS3VRqiBL41a6/LpaSr+tSc",
	"qqfzobEX0p78wuzFa5JmXnaLe168QNKnF1iSf6Xy/cAG5TjucqkyMmrZK1R+CyUkT/k0sxVaSnNXlE37",
	"OM/71RShKBWcFrMcv025i5YCzrvfZoRgXTDnNaSfsyFVAguaTl2FKalEEZfhUp6Rrsx76F/niI0pu4Ob",
	"MY52o63B9paJnRq7+KEyTMWAPOFQfe/n3+Bf0a6bYRDzzN4n02zoULRhfzQ8cXQmyIje6SP7aDWUNMb7",
	"vNAM4k4vsrIp0DEuVLT7bLPc3P20kIqIo7MwX2b2Sz8JM+Lx3KbCY64JK4i/VpXpnTeCcWzttxSDLxcs",
	"zffT1dQTm0RZIiECDcmIG62kqDSOZsbaUfxsYdWdksKY1qc4SyO3iD6/IULQhMjBNAPz76JRb8EUj0Ed",
	"1YJ0R6l8kZdsolS+4FPG/ErQ8x4zfVBnwQdN/+qerzLNq+7unNMV91SKToRoJjEBUCS5IcJz5rsVVCnC",
	"7v0UivZT6F4yXJU/RjMeSZMYLLR4UYpD4FUAWVZ5plF2pKzFRUtRunWAjkwKVuOOTtCvBQFnTIEzLZJK",
	"JIt4grDcRVfRhsbyDcU3nEnyb9D736F3l4tS53NbHt/v/8I6jFwY1We+XgEvwTpOV8lstbzikhuDcKPw",
	"OJTmf20ZlN0LkWlR2iY4viDKoXgtubJTOEABFylHRWpHa6VcdkmQy1JURkXTV7xvH0+b43aOg3y1UDln",
	"pWYu+4rBOiRsoKvu7z/NNpGu1WTazpocgx2IS3gve3Aqpnig7fNogCDzAWFKTBGFKgvgx4odS9BIdQz0",
	"3q5U/xMefdCNNk6h/OJ+WipTa1UP/ZqyYEhqR/ri5RFyjv9Rx9Mx6/ZUcC8ZZ2Q3U2OBjTD00cBhAWbN",
	"oo+L36na9lSFjBqXiMraxDMEl1nJn+slhR0h8/FrxsAd8F82RvBpgtHcu4JT4JXN5x+wP11jVf6tXRIF",
	"jjUrZ8poziagpo8R6Spchdh542RaKUf0kzQjjfdqd8yW+oS314TcFyuaG8xIsPDOHNtm9OW2MpiLvyb4",
	"rfdJ+kqE5R7ap9mgBBPOB/TPtU1czXQQqInwT5lLH/DqrEhTP1zA+oRER6MTrs6MnSrqdbzUdVXkA/+b",
	"B7ZquSQK2vbSWzyVD4xKtSxlnheQCECz3FPjvV3/6kS31D7KCv322growJV0l6cyc0a95mJg1AUNJ3p/",
	"ynH0H42x9E92vJn7HKaCzHjl10O0gDh8+aoUbg3Pe23AgHnLpTkHycaIO8an/HT/qA/+ORS7Ghw+8Rig",
	"wzscq3SKOINPHpS34YHu96B+hR8YjPCjrn63W9+L8trtWe1kvBsIx2IXuxDtnbWRhgMWZEylEtMButSc",
	"gSuYUlW29z5k3Djo2QhDTUbcYD0tpKacjfV/rfaZi0w6BqoiOdKPGVzrA9CBjJAnboaoVr2QXQziUrJI",
	"uVJZkemqDjkFaOr6ua8jY3x1yYKFA7qq7Oe+CGa53LWVH6gsQXN0WgbKeyi1DP4sotaavyOlJjEWBHwX",
	"OjN7rWTd6qp78HV1J51b3LGhb4ohEYwoIi8gnmj2pq4L9l5kopcWNaFVUCLz4T+pJb5gakWVaM3L0oZ+",
	"VWpPK3sFd3qxM6u2NTjADHtMZYiZP9Q/r3U9cNV8I1J1tB/npYmxX1cXYOG7egwJ6ebmOvhTpShYT+KF",
	"Tm59YZ3FCc5I4hSKJs1fzYyhlxrg7y2v3eLvv47KYUlVgxd002aJyjYtuTkHJiOH4jRFuRZMgUWqSnoB",
	"bz7BN6RnaY21Okj4wgAjwUZm+5qHM+DjyBhXVQ2LFb1gq84gYdbz3QcdWQEeyllZoHaG27qp5QDhXrdY",
	"2qUs4auekJSsMhdNU0gfpD9fZr5xrS5D21/41wKeSxs8Xwt287QYnq2gdHIGx2br843OeF6k2Mu/ZxNq",
	"onOCkz5n6XTBPJjznaC9SjdPd+amJT7GUG7YhvRdk6mx51qrsK9fgdASxREXY8zoZ8Ojx1iRMRf6z4cy",
	"5rn5VZKUxOqRw+0gUi32fpr+rQI+oXXBGxc6RC8WESv9FEojprjfe5pDuILYtA0991WEzEF0mDvNV52u",
	"73sM8Rz/WhC3qTCtJ/S46waVLst00p6TPGbeuldNf+C5kLep2IXJ0EXAj914J14ZonwVlYVFZVmpUdru",
	"Cbqh2GZU5gKJPOtzqQRxeimbzksPluP4ujkc46Zff4g1LtWhoLJK3unrr5y+2A64oMbKrN6p8s1fZ26E",
	"ri07wyqeeGHipaAy03BTp9G8g2DZNJfGc8tWlfeXiZMkKuPT4F8ZvwGKVS9C6eW0DXK8e+jvF6cn6Mww",
	"WqWhIOyNEwbVxPVqASHx49sGrXeV57Pcxdp1deYFJpi0DDY8IaD50b8bv2pbSIzckbjQRDUXpB/OSNNz",
	"8W6OAAeyzt5RtR/05j0TPCZSIt0DxeD36vztGklv2oSaFyovgstIcGy8khJeqA2pEiKEV6HXZZaAZ44r",
	"nCIJ1DYWXBqWwWUBoZCDJDfGocdv6IsBMtJmWY0NPTw7PEbDlMfXsodeQHYKvVkjekdkD0EsD1L8mjBE",
	"2I2ROR5ZHx8LpnXhcYwN6/LL6NCBnnkelrBnCRlRBrcJfdg7Lh01jCIu8bcAPRxxgayPENogKt4oEyls",
	"6LHkINkw4Jmzp2y8sbXZZ0TdcnENDkSP5vPaFvJehQcLc4qhsJoZeBvCUoPCiyEq7socc0ZE3+6ZgNnA",
	"8l8ObZyx7qd66b6ooRKFxpeiO48zsMrt3ZBlzKqNiq0u3uYCUalu2oXP74cCJylRv48b6X0GO2Q377GQ",
	"9x5Hi+j3HiQgF/6zusmuMvRsXfuXj4trXc+tH2VYd3VeT0JjXS5BeRU2/3cxBO1vG1n90QlXljvGzBoU",
	"NeMK/Z1kxW+I8NwAK99fKeINSM0z+EXeg191Coq9lAh1bpOv5t0VXtrrnBQZZv0yn2kjMhc8hvXYYZ+s",
	"zryILmMiZChwkqfeDE9xiG+IAP5XWpOuqWZYvZ4wMWXjAXoJksXu7HyID+SDeqLDB9mDeqLDB5MHnYkO",
	"r66S77pzG+ZExISpTpeaql3vmlmRCZQVdDwmQgZ30sjHRgN9Q1au6FdDggs7UjgFrJvGO7va4uqC7seV",
	"0LAGQTvlo21tYZfj6YNFwBu5q2cJMZ2wVAN3dvFm7OxjQJm3E64UsV4/1evPKMP2hwznuY0r3D97txyF",
	"zouQTrIXHUA5+mUi1Dsy1faiY1uEfonBupXBlbJyemIycvlaWs3xr/4AdmzGSu/TrBWsEv/fsbv6metU",
	"WS+IUzOziocT7uJaDFWDP3ZPx6zy3dAJCd1rgE6ZdbEwv+ZEIEdYQCFhSPJ6SnpXD1uIY9avKWXjIy21",
	"B/MZle/QkKhbQliZMhg+1Yv5HZ6WMoFu1/syw47R888nsOKFSXRXqgGbWYAafkkVwkYMmYIKOHUZHxLO",
	"Hri4B2S8PTxF5VfMqxYHlQwXxXhsvCog9MLCFbsoWxCITTKEHtpE1IbnGkugrzDe2Q7qIb4lc1trMjcp",
	"g5zTItynn7Jf76PTCHaombEMs7kZjieUkc6pbifTxgQIfHIAhiuX7+AqsvCYPFK6v0EBKhHJcgVWCkFM",
	"vaJ6io5SS4v20DmAieIUC+vRY4OZpEumlBA0LLwaci6QC1E1p3zArNI81eahU/CQ20VX0YWR/68ixIW/",
	"0q+ONjIncR+zpG+3dIHcSe2keHbhlkyUGFAh3eIEMly35Z4ld2wYglW9BuqddD3LKZbqsgyJuaRddp96",
	"Xe52JRl3cVypmQlm42VMfZ2Xt1EIw/azjjYmDFJhmko/O42BoTpv3zz1dHO9ZTHC5zmrMkYvtOn3xJ+w",
	"ELTfLHJTU9DPxBInJr2G76Ze1d3lCmeEwa1GDbe7ucKtc8tjzCq/0ybaZdWgehnomUWDwlsUqFG88m75",
	"gAe3q6PccEePwI6G6gbP2dJkD6r56W9It3fNhI4n/VQTaFMLHUoA4pJa1PDLlAcEippyyI8CDn3lzyNM",
	"U1iXGwQ6JKT2Z4Y1T8Uws9a5kSByYpqKFfbfX+WeA6TddO5B3G49qtbQbnzpVtUxoVtYu/mgvvJ2h+Pa",
	"XoSg9nan3bwoIhxCmP0cRDCx+PU0WYARLieSwwIXtN9z/+qLgtmnIqXsGprMP7wWnFIs4fil6WH+4fXQ",
	"M9NYIwyVbgbKTIWXqPQvgZ9NXKgJmRjixEOdXrQc9nhbc1iuq7PtvAS23eWtW3pX06yP9+zutFuO3X51",
	"Nc0a9sJtabvpoNrkduNRte3txlfeQQQQzDuadusLHP6qKoUe2HvNRM/F8bccJ3MwXFOABfBbqmKoMZhb",
	"Is246o94AazlECd9SZS90MTSaZN+1kfulShZuYQLA0Hz57e89mxUDSdcvbQANpte4OSihLfZWH9nqt+P",
	"3XpaDQ1kLBsWpUTvGPUSHLaNspaw3YO5a716TUet4CPYLXK6GHUoqVQz15zmhF1cvLYeSCjBJDNShsfA",
	"bj5+FuBgSYXc91lpk6x/MUh773HrVwms0MNy0NC1ujUMRA82yXorO4e+iokoN04UjDleoPKwe1zXj+H+",
	"583+8/7H74K2Fz1RGBq40uD4ZrO2XUVSTpKBdcu05TU8o5vXOFfahGnr+FQ/Tf8EejWM9nZxYfFBCxs/",
	"cRck4mIp33JjjWjXFEGfOSOVg5yQVmEJCHy0d7Jn3fHQ3vnh3sbb0/29y6PTkx66BQWF/rFesCOGJI6Q",
	"HlEgHhPMeuCV6L4s3eChLhkWisZFigWSVJEqvQJWCAuCe8h3QtkDD3m8cUJu//GBi+seOiw0Ndg4w4I6",
	"fXLBcDak44IXEu304wkWOIYMJG6tjZx76OFV9Or48irSp/7ucr+rlsoi1SYDMYgjyK8J4obtZST5QnEt",
	"c8RlyU1Qr7MkVKxT0cy1Ol9+ZOvEBHSmq3lw7wvODu/0OTp9qVRYqFcCx8QvW7e8BcN9bIvbONxceqAS",
	"sVvqHBUFoV34yrzP/vw+KKXvSMProBimVE7OuFAzskxNuIREKWNIzK3xHlnbYZVP5f1xLUwQXOE9SmCJ",
	"wBVk2dLT7cJg+l9O49du2cgFVzzm6VVUlit6tvlsc/fZpvvI/rmh4tzevNLW41P2zf7zj9/tmv883Hio",
	"4vy/iiT/Lxmr/NGjvwXJfStorx3H8adymlnEs6WpjX5/jG65uAYm1TkJWxf3l+Cst69S49lmPBrfH/se",
	"gDYSNyEpvYFU4V5ckhfCv1GG85rUp+0A0zL2Er3kwrW7SDlpc5ga/18bY2E8Dm0Q3HsqFNL/U+D02OjX",
	"jXciuMAwE+SSgUdhOEJiXkhKuyZeO1bGKlhNMM2i7j1mnNyLc6uCmsGFzj4zMLih3fXUaxE4VkLOuw0N",
	"ziDZFXzVuqNfIGbWFBsGOGJYOskwTaPdSBGc/YdfDCtycQDABBmEQbbqBrokOLPlvnYjp7avfd2KZvi5",
	"PsTHh6HPHlnDl02VBIU5SZxiYbykPJ90PkKjlBAFumeSjF0QoYmRUBNCRYn9cnDFQIMQEyaJV7drL8fx",
	"hKDtwWZrMbe3twMMzQMuxhv2W7nx9mj/8OTisL892BxMVJaal0vBcTU2ae/sKOpFN2WpMVdd7EsvsngY",
	"7UY7g83BVpWK8Ldow0tNbqsIODucSTQYSuSzb+J5MdqvPr4wH1eF0yr1bmmiOUrKjzu/jAx6Eale8GTa",
	"SJLt3fONX6xVzBCy1RiNTiC+1NHcxpcKInOuz0XPtr259YdCFzqSRJ/2483NrwtYWd+pBcULnKASSA3J",
	"1h8FyTuGCzWBeCS7KTt/FCgvuRjSJCHMwPH8j4LDtOxzNkqpeaweb/9hwFxyjo4xmzp0gdIKT/64Q7ow",
	"b8A7Vhq1DZ+Gx6Dh6qSS0UfdbQYV3fhNU/8vEEFPgkEBODEyWRmS3Xnx28T0FVGzKGmVxzKQE6sZYTef",
	"mCPF0dj4m1A9gk0Cbp83G3ddp5o977iamsSC0V8LcmR4bBMH/rFFZDf/RET29M03qtZB1R7/UXCUuuNv",
	"9GyN9Mxyt5Z4bbgCTp1U7BVRNq2vrfRkqyV1s4GviHK1o0xhqWXJlfnKkqT65LLpN7oeivWlnXWv9FYx",
	"AXSiXg2rnBbyBFfzBitnzZr3dyeL9kg6aeC2ufDNq4i8REV/KjL5R5InVNGnP475+/OyfR5VMkQjTIIq",
	"r6kcqzic4cdl7/EKhh3Mo0PwWa203Wp0yOeRAMJ10ZyPywjEfZj6uzWcYS0EfiFx+A8mSd/E3m8M4nwK",
	"/I1DbHCIqItFLIlxLwqmLzD2xuUJ7rlJIrFmkmtMlX8IzV0jXftGYv8ZSew30rY4V1fleVjczMDa5U7n",
	"2hdaX/yedoX25H8Ge0IHVN/sCN/sCP8iouSfmp9qUb5OijjPZPCKqGWJ4iuiQhRxKa6re7612gX+AG3X",
	"QpTxm/L/m2z3L02LvpgSk44YGAeVDZzTjZstk0HefN0uDmApjUScNWUzcDGyhMAygm0ten2EbjrjD9Ze",
	"wpePX/5/AAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../core/v1beta1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
