// Package v1beta1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1beta1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/core/v1beta1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9i3LctrLgr2B5bpXtk5mRZCdZR1W3chX5EW0sS6tHUvd6tDGG7JlBRAIMAEqepFS1",
	"/7B/uF+yhRcJkuAM5+E4e0rnVMUj4tVoNLobje7Gn1HMspxRoFJEh39GIp5DhvXPmHH49e5gAhIf/Mpy",
	"oDgnvx5NBEsLCedYzlWlBETMSS4Jo9FhdAE5B6H6QpgibOuiKUkB5VjOR9EgyjnLgUsCepA82M/VHKrW",
	"qgqSDGHTD6NIzgGJhZCQjdB7JgHJOZYI0wWCT0RIQmem6j1JUzQBxO6A33MiJVAFAXzCWZ5CdBjt3WG+",
	"l7LZHs7zUcpm0SCSi1yVCMkJnUUPD+UXNvkNYhk9DDoQk+dXumJoLqoLxKYacJznKYmxKtXA0CKLDj+Y",
	"ZRAQDaLfC5ykICM1EJWYUODRIJpDmkU3TfgG0aeh6mF4hznFmcLph8iCclz2aD/8z7LjskbVv/30ox5m",
	"ySQd7KotUKnmi9P0bBodfvgz+jcO0+gw+sdeRVR7lqL2gh2+ISm4nh4GG3RwASmW5M7Qo+qBw+8F4ZAo",
	"RGjiummtYJ/pvaZ3P2NuSLRGsFAV4CQhqi5Oz2tVGiQ0aBDEa3pHOKMZUInuMCd4kgK6hcXwDqeFInfC",
	"xQARqoCFBCWF6gbxgkqSwQgperqFBcI0QaYF4HiOskJIResTkPcAFB3oCs+/eYHiOeY4lsDFKGrhYh36",
	"drg5Z1y26Vx9RRnOcwUtoWjKeIYlGkdzJqQqPCzJWf01jtBTGM1GAzSOXu6/3D98uT+OntW3p/2umAaW",
	"Erga5n+Nx8lXh+o//9berT1g5+yOJMAvc4i3pN0AtSgCrJMLrtjCJgPotg+DSO3tDjZZQYFUrZIQDv7v",
	"//4/9eVHKaOzARISc4nuiZwjjFJQiEWMI1pkE+ADTTZ2pRBl6H5OJIgcxzAKckd/v7nJtrfc4M+IUdgU",
	"0ycZnkHXIm7ENk5oSuhuu1Scs7PDm4ebDTbaBQhW8BjekYwY8dwUt6YcpbqC2nIhEVOnyDgv2j0dn1+b",
	"TtTOVWCJEXpjNjAHtdqaFU2wgEQJYJ/o1Kzq23Z/9N+/Ce3NDDLGF+3BT/V3O76mS5YbvooKSuQWkDz/",
	"5ttsO5neXIplqxAzKiTHhPZdirRc122YT4NKNprepcSyEGEFxpQp9QUjQegsrTMdq48lcEcMj3AazTmH",
	"HFst5VLxHPPzoqDU/HrNOVOqxzW9peyeRoNIqSwpSEj6azr1Gfhjtgo9IFplFVStIgdmq6CCu1XkTaQH",
	"9n9maWH4eyWO6mvwCqaEgkBY8/gE3ekWqFC7YLLQyvYyQguLj2tKfi/ASA2rnPr9qp1IaIiKWzubQ5xi",
	"kp2zlMSLbenZYOOi1mVT0ugJfRYxY0bfXhycsoLKXXWmIevs8eahP5E19Z86nZjlD/C4d0RIzQG8jW8r",
	"K4IgEjKxm3WPKvaFOceLzfhZiIb0pKa4SKVm2krBiQYd+2zO7g3hz5SWPsc0SfXus/vjfg5mY7B7xTVq",
	"aCECccjYHSQ+M7Tj3Wygspq5GL6ynDvvhCu8b7GDji0/BQ40hpBAtEXq1G5kQ56yBSTo7PhkqCgjJZhK",
	"RBRVK9VTseUpjiWa4PhW4XPp2CFW4MOziaYlLossw3zRUw6mqY9Z0S0DfwScyvkiGkSvYMZxAklQ7r1n",
	"PizrC786+NWgnVU8aDrrBORevUJQ/tWrNCfWtRTHiiqnqh5ckpnaUxfwewEicM7srIq4Z31C3H5UipjS",
	"W2YUEhRXbdGUs0yv2vFRe2vgnPwMXOgRmwAcnZ/YMpRYdqHp1XyDBBmGZ/aQ5gYWLKsvTdXGNKQ5QpfA",
	"VUMk5qxI9cHrDriaSsxmlPxR9ibcXkqxVNMiVJ2HcWpMAObUluEF4qD6RQX1etBVxAidMg6I0Ck7RHMp",
	"c3G4tzcjcnT7UowIUxw7U+r2Yk+d/jiZFJJxsZfAHaR7gsyGmMfqLBjLgsMezslQA0v1yo6y5B/cqchB",
	"fnFLaNLG5U+EJopjYmRqWotGiTLHDC5eX14hN4BBq8Ggt+gVMhUiCJ0CNzXLlQaa5IxQqf+IU6J4uygm",
	"+uxk6UXheYSOMaVMn6KLPMESkhE6oegYZ5AeYwGfHZUKe2KoUBZGZgYSJ1jijUTumUbcKUisuhJWEVi7",
	"m859aNWcSJQSa4d9mz7bhodyu1pK83Bk59hbLCyfWIuEf+E4z0EJMVbQBGElfvkw5qDoBh1fXgxQxhJI",
	"zXn1tpgApyBBIMI0veCcjDy+JEZ3B6OlILS5FXzKCTenD4gZTYKHVN3e2BNLRnSHU5IQuSiPqx4gahhj",
	"w4sOI0Lli+cVJSruMwOuUAifJMfLrKGlbtii4rqa1zKTqo4Rlmb/gHA6iUKvMfg7HGsmrvCcs7xI9afJ",
	"Qn89Oj9BQjMFhXtdX81cMUuSZYXEkxQCRlFDXEHpczUHbXz49ush0JglkKDz16fV75+OL/9xsK/AGaFT",
	"LOO5lQ6KBEelTCKQJohQhH16WCbYDOOrLclkISHEG7So4++Dut0JTQyRaZh4SROmjZEimhv/XuCUTAkk",
	"+nQY5EEFCfDz65NXf8E6eUAIPAudV671d411NQ0tYECfYG5hgUwrb/72mEuEKOpaQu1ws5KA1ZRXK9V/",
	"AWIa7NFRc404dsAPO44kFZXhPOfsDqd7CVCC070pJmnBAYlSlS6n7pmdRcdiIDKtLvlEwLJZVQ1vXNtl",
	"WxkcVNhETB1cyoXoteUUzyVGw22rq2WZOTKo5Wb+9huhn5QWjWKvIgd0pFEHyQC9AkrUvwpDbzBJDVCb",
	"H7lLiIJHbZ9uvHn1p5ay9+1uV8p+fsACAhcrctNblbJjc7fSmLIM31/cDLqWtSLaRB3xU2P6ZRQQVtxH",
	"OiKPC861vikVJbuzgdrfFyV3X4lTjYsWiamvFfkoTbrQmiWasjRl90qH/qkSM2pIX91E1wLsbZBaLX3T",
	"nig9xjLP2Nxeq+NnwIKNhbzimAqDUdJ1S6XqIUkyMLgoYZVlW0iMnq4wZ9mDgoQyOQde24VKIR+qvsKa",
	"sVDMvQ3Fj0WGKeKAE73LbT1EDK9SOHLrhyeskBbiEryg9GETzZuTt0DBKFXh2Y+cLjqalTWNBKhj4x4L",
	"LabM7UaRm2F9Jezbr4NKGAcsgkdV9HTCCUyfIVOj0vPcmE9Er5luo8u7oTp0d9v1IERL5cyqhV2fEa22",
	"nNUwMtAkyKboiquD9RucChgga+vwbTuqPBpEuoJnzelnvGlAZ/tqfHVdNz6XI62ceodHivVGqQiP+Idb",
	"b4pOCEWD6Or89GfgWic0Bh9XYMSTRoSSTe2qcQxCkEkKzT8c4zvHXOiqlwsa6x8/q3OJqqEYWCFP6Dln",
	"Mw5Ckcm1OpHbW6UcYlf1tEglyVM4u6fAhYbrjsTwCtRhnAh1NlSN+q3Oa8pZmmZApVV1vPm2yurT7dSW",
	"vC4665S47KxRIrmzRh2cC8iZIJLxRRD1CuOdBa318QvLtXqTAki3CvqP0KqZ1fDWznzwV9B86buOS2h/",
	"SmbNa44tboXeEhnoc6NrnEoKX0LMQe7Kj2FX8P0oZR7qqxvZeeFo4pRRRWZtv5q6wpCZaqtd5SpjH0O2",
	"0eqDjt978HZwA/+y9vSW4IMz+vpTrmg+qAyocgRlBecjpaSygiIpUm3wJBmI0ZgqdNgaRKCP/0T2/x8P",
	"0RCdElpIEIfo4z8/osxaGvaH33w3QkP0Iyt4q+j5C1X0Ci8Uek8ZlfN6jYPhiwNVI1h08Nxr/AvAbbP3",
	"b0djelnkOePq+KqWHEumgBiqioelMUQd4IyR17p/qW4IRXMFctkf3AFf6G/P1Lgfhx8P0QWms6rV/vDl",
	"R424g+fo6FRRyUt0dGpqDz4eIn1j6SofDA6e29pC6oPUwXM5R5nGoWmz9/EQXUrIK7D2XBsDTLPFpXGF",
	"qM/lZYUSpVS89JqM6Wvjl6Iwh/aHLwcH3w6fv7BLOurtzHZcCMkywxVP6JQts701tUFtmjSXFgmKdUfI",
	"7k+7KkE4mrYVrxNCDYVqq4RWnOsXYf10NTObNsTme/1iJ58vBIlx6g3yeHfzeHfzeHezRjeV8rXl4c52",
	"tMGtzM16vKHlYdV2XtmRqy1kE0gSCBD8L3OQc2j59ak94Bo5S/KEMRkbBwePCCaMpYBpt0Nvw0jhe2at",
	"dsHCySKsUhnPXnviMx7YAt3PSTzXlkbdEvX29NLuwwHp8r4cxdVBzj7S5Q3ZNmRsQYphb8aHQbdTU2UA",
	"sFVKzxnNehrA7tDHye2XFebX0rNFrayH+kFlMymJdbDM+brnxqq7boT0B2EqOJqca0eThl9YwBumvk+J",
	"VVqWkr6vVxjDnBMn2lxVc/v9bKar5Q5CHYasNfFvzltdKD/2rMaVrcpgVu3mKZm1EcyBJsAh6dSCLmwF",
	"p/d09rvqWqk+zvozFyzt1Ppssa/8WTud/hwzSiG21quSVtrIEOaodfIqzBttMTp55dtGGyOE6cq0PPXE",
	"eWO7lEp5OYqTfo7bKrjtpeS/16J/Yky1BiPMdRGhRBKckj+M/bwMJwOeEYrTQQmzZK7ZAIGMu9YQJ2c0",
	"XUSHkhfQIOLGrAYeAtdcX99kE3L6t6gwpwbsiC+pG3rKW7LWwkrMZyC30Fp8+K50Z+EbITPOFpP3Om/L",
	"oPKG2mxAoYZtISEDOWdJfZv6dtprCtoqqa2wsWR8cQGiBvQya+cyiL2el1Wrj7ocNSdK3HMiF8dziG+7",
	"OF933SZHqPNG4lqgWDVBOXC1y4z3zYZiaRgUS9VxtzmmgWjX0qgbIzsUR53dr7g+WQPtFdE699FrKpzl",
	"yL9HKM3Y65BxaALVSMvq+DB01yuh665Swd0T1503VFbd6qLwFj/IG9YfPUqiDqdysWOaU3S0tiZXbRmt",
	"xVUzWaHDqdolVttynGRKNc5yh5BG53e6ZaXJ97tJ3t1OtdFHZjHdqUTm2c5XZLccoA12bx7QKai8m6ly",
	"I4X5wEZ7vrH/BuHyri28glm0+cSK/f2OTCFexClspN2nrvUOTlBNy2zV+WeVVQ0E7FBMhXruok4/+UII",
	"t215ZK54LYnU7x3rX9ak0wbUTUprFNegCJSHQFtRbTXNnomwl7NfikzRxCqtRkFGZ5flCapTxcqCrjlX",
	"tU5MVJAxfXF0ffFu9UHU9LsmCZ2Jjbbl2WXvef1cP127uQX3mi55RWadTseJLmv2ZS6ekJjj5998e4j3",
	"R6PRs774qg+6JvZKV4C1cFheM6xSXWyQ+oZ8pw6ck7gJEbc777SKad9ht003zLyIypHsPLZaruW376J2",
	"/W4W0FwMtaPafsHc8p5jTiSJcRqIb1uHRdYB9cPn2qXV4KFSD6BQsQMyVLbSwcq7P+nglA0+iZfcVnrx",
	"cb3ibnPrm7G7yNuG50jLr90YBLuhM+W7AizozRKCSbA0ZNbX/qYOb7Ekd5VJz9qytgSwbr4MBrLUJfNu",
	"bFTa43QbiK1sN7c4XdksjtQkahzAOtXYVbbRQ1uisOFWE0KiSfCVdJhtTaGOjSBKntS9hBo+R1jG83OT",
	"QSh4reGoRVdENtdQfYatmxDj/eHgKCiRWmcZ2AQmXP+rtG5RTKfk0wCZONQ5pOlQyEUKaJayiRtMw69H",
	"xzNMqJDOXzxdoJThBMwQGqYMf3oHdCbn0eHzb76t5Ub6sD/8Dg//OBr+1+F4PPx1NNb/+zAe3/y38Xg4",
	"Hv9zPP7+5qun/9Gv3rPvn47How+mYqg4mIFpdfC+uZffIlmE50xouzGE/bCeUFxuemwbG8MnKuEF4Fsm",
	"j2zbDGvLBknN5WcsC5xWAQDbygSrkPqiwRfW2/K39o17YJPi9g3ZboZs3EX2D7Ip18vkZ9A30O5eUuE8",
	"GIvhL8VnCazxZejm8qa6KNTGN2uX2J2JypnaLgFonzgOS4EmbAGoC1qzTBk9fX929frQXKaXXmZEIMok",
	"4iALTmuBbs962uaU9jhjw98Eo0Myo4yDuchSwLuj7+6MFruQumVHNbm7kwODlpRbb7zWZjNyzbkXbtpr",
	"1ckyee74WU2W7oaTGQiSa0pkNw+zbmJbS6KkwwzrMa4aYuvcMwozU59m/D1fMhRNndUkKmrwd8Oap8XN",
	"/UA8rjDHPLnHHLR7o/EHJnRmVxnVHA537x9iYXCBZJ/NQySArx1aOddKShM2uJ/pAIFw/pkLmDBmwzHO",
	"2T1wSM6m05pF/ugeE6ljS6w3hIlGmqYklue4EGsaQGsT8kBrlXnQBkrrZ/dakT+nQHFtmoHypkm2VhhC",
	"RqBaEz8r1rjGafs5cp+59Ih2M3lJEuBTzkQlVnX+qtGYvsbxXIe+x4xzEDmjiYmvrE51ZldZz+QY53hC",
	"UiIXozFd7RJuJlHblDFLU5PAtnTh7VR3FZCdzkpK7TjSabist1JwD/teuR19eDWUlmgCFSyeWg7rVc+K",
	"nkLeQz8wJtHJq3W6Mh73G0vVlue/Uk0cYzVLEJ76Wcl9Lx337Qlz06PXx3KJmjYUg/qarsn2Wge7FV4z",
	"ua6pbx8yTPHMBPNqAWDEok6nHKdFokp07jb73bnuTwAl7J7ak7YSWDZWP3CpbutdmnidzTRNM8Oyi1IJ",
	"2WmnD5tgPdnoUsRAv9OLSl+Mm+4/uxivYWCHYrzd7xpXlRVqy3vK/Iq9wjoTxVkhz6b2txdbuYnhvQak",
	"N0Sg1B812LgR5FkvXWlbJ+J2ZVDhbuL4Bn+z6MQgk7OmHc3dTAeavxFxa/LYrPOmQkI4aEe98lEFZ9xV",
	"3df7XD6XdVPrvyqWJUjI8CeSFVmVmwqnKbv3AweMp69kKLaZdU0i/LJBxchdzp8EYR0uxhTLuLPeKcBt",
	"UgybIdPYMkyW6Sp6sfyoU7Ecoo/CBAIKk11rgD5m5oOJ7VMf5uaDjmIc1RPWP/3+8MPB8Lub8Tj557Pv",
	"x+Pkg8jmN/2z17+mMVOSq48DKdi6hlC1+7BeWSxxI5bN5yh5anKhmsRWvWPkzVDntrH7+wfbSfd0GvHz",
	"7Tm1qixJ7WgzDCnSMJ6qS+2qj5GBj5GBj5GBS7ppbb0dBAm2+/wLsjh2pPDAaQ9246pWuZ3COmrJfLwr",
	"BMuF9OsunbEL2OUCWZI77d6LNnQcb44FmgBQ5DoIBxemeALpNk/UHLlseaYnbSnI83RRJXTuiO9uPwhi",
	"5rn9slXnki20wG6iaKtfKyBZRRveteC2VHLU4RKm1RQsbSinTyf3WNRIpJ/Hs2vxQ1ccaT0cVdXlvR6F",
	"cb0O/Cn1SLK2agk2uJsNIL5coFF/qgybJYLVjCD0KhpwWnWfCOcEqa8lAz5xgofXJZSA1E+bKEx+IJ/Q",
	"Avu/fiO+ZST4INKnvItVkYhXmmiXRiNqOW8Do0a/CUbRU/c8zLOOYIFdcz+Xqc1dbOp35TyGSER5FToH",
	"ipTi4ZEZESF23cEx1SJvziy7jDcdFdfbQK1OujiWkbG7Y86eD8CqDJ/+Vmin+RytnbyznbQRwnj4u6bj",
	"9B/YC2IsNoVmiackFG4QL2uvz45IwieJnl5fvRm+fIYYb6ZI9gbRYa8k7VwLVc8dJTckI++43N8IqhDV",
	"HcurSsvo3TaGZpwVeRg/aq5PBNI1Bp5xAojW7rB708c+wQacxOjk1Qi9Mk+VaN1rHHHG5DgKnxpYAkuH",
	"zoFbD0KdiHyE/pMV+jBlgDE3AJk6+kxxRlKCOWKxxGn1RBzWJoU/gDOX6Gj/26+/1guNjXCLSWYbmGDe",
	"UJuvn+8/U6c5WZBkT4CcqX8kiW8XaGJNLaiMrRmhk6l2FCkxNjC2/vpktA1AzVNx4AphCrxwgolCAF+K",
	"LXavM2HveqGs04r9eO0SRa9Hnzuwg2794GZtn2zUQ+0J2eCTnSUjWMfCGM7T18oSMyPyQgEc1kS8h2sw",
	"ektk3enVpuJex+Lq7Kw2scCUzFzsf5WZsSPRiiterYxXXdVSxbddM7V+eQF3ZJk2ZkoV0IXwnklZCm8r",
	"M0QJfGvUQZfteNkrl/5sG97mvV8IsivfW3Que9CxRVbaLJrjeHl4U1krlBHHPpOkFIv6K4bZYojzfFgN",
	"EVhaYw3sVnpNpoeW16RH26aHYKoeZxpXPHpCJMecpAtE7dsBLt20qEHtRUX5pBzRGaGfNFXMosPoYPT8",
	"wDgzmkSh+oFdPEnVwhmQ50xIoXmd+hUduhFGMcssLZliswejPfvRWMujcw5T8sm9kcZBT+qYFUqdeTGI",
	"rEav11O/avtyv0TucVoICfzkPMylDb4UO1zio+uQqiVUaUWxT/p66410PzYdk3nRWLMO4V9G6xcjjHs+",
	"T4CjCUyV1NZJ/exuKM3C/lJ8sLCqSklhMposcJZGbhJDdZLnJAExWmSp2iF93zzoLb46Uou29tFcyrwn",
	"f6box6ur854cWq1A+M1y9dXxZHOKe2IWzHnXSOZZWJwm2/Rf1aAIuAPuXUV5b45vxd95m7879oxtDowF",
	"jdESzm+CEEKT56VWfn3xzj5LwTJFi1NprY9KmdeBmOhE6sw0xpkC0O8F6KtEjjPQDwyLIp4jLA7RONpT",
	"5Lsn2Z4zz3+va/+7rh1UZZfJkHL5/nqx4Siyt9xY+lrxzp6c7nhasldgauuBvrPjk8BrfCEZleP4tiuG",
	"VYuI5Q+D7zBmTbHrgDfvdi7WwRd/+4Ybr0chXc95tsOIzauOWhGrFipTzSFB2DsiaZGxJDx5mxdRLzUy",
	"zIGzoJvlXTI96Yl3xiSb3tdD5XmRpqFHPk+m75k8Nxau1lOfzomyfoJ74rd5MkK/zIFqc6AqO0rv8UI8",
	"MSdRswxEoLxIU3VO1FmCzRv9tVbvVUmtkX6iHacm8aJ+zaY7S44ZMxo0J6N77XlVr/BT9qP+aPSlPtn+",
	"luI5TK2USaPl+Z4uehEfPislbpcEoN1hIA7MT3Ng5a656F/xkGnghFgj0c2m75H5Gg+wrobWvETGYUaE",
	"5IsRupoTc9s+AeMgbHKGeg3NqyylN5TiSq6zgVJJUkZn6l97gGY8E21RI3z/pj76wNoPvC5/5f8vFsXG",
	"231J9KkvZq2auTNpWZl8lpuYLZTbyLauFwkO18dIeWwyD6W1meTmuCnNaQEV4vPqk50o7kDo0kcjgnaI",
	"XcCujsZqtL62Mu+BKdPw72YkL6jc8PxXu2E3k/POeFYPC47abzEqfAU7WGJVqsxJq7v6Gxq+A5vDt3FV",
	"a3az6tbUtq5ItvfuOtVZVR4fMfFR0vdg8h5nkLhH5/Vq1Y0xaqoB5dAqai3l8POcK9Y8T3hudO2wq7JM",
	"qf1lLl9tM8FpinLggmibaJXnSKv6c3wHA8tErO1E6BYGGJ13nNu6RtQFrtYpZbJKCbCha0NV2Tw0VwvY",
	"Dr/XYd8cLZMsLvFFMhH32oHzHgv3vGl/B6QEUthkLJKmOoRHNV9nvNmSd/uOkIDfCy3gbP78mvuq9zyi",
	"96Zf6bli0vgaRx503nzV1QiWEboAnAwZTRc9n/nb2rPlFOscmdYr9xYWxr5srdTG+FfPPM34DFPyh4ni",
	"jbGEGePqz6ciZrn5KiCFWD5zxBykon6S0LpPB59aVNIptEqe+zCWSogJ559tvg+UbB9rd9I9NdY4sm8q",
	"dT1voFt1u4lTxHL8ewEOiXpYonOsll74xgj9RHj+3JVrU+UmHpQE/djUOZbx3POfLxXhMGFM9SOGDY7C",
	"OraXDeYzV4A2j69vkcBJEpmrFCOnOWTsTu+veh45zzAYVLyO0P+4PHuPzpnGUmm7Cl9thUE1fuX2xVKm",
	"t6gCatSSAixfdu/YztURFKLmXiasRV7UAxTsFY5WI8NGuS6ctNu6Y4/jGu+ZtNRePoasCFHXd6yQ3QH3",
	"bh+qu0TB4z1CE/g0+k1sQX9OozhKgcsLG7GYd4cst+c5ryfWbvhHarOz6jvsrNgZTOTCjJSAlk5UKGR4",
	"Kjy+A45nYCKdEPGeKbEXanpgQmcj9EZzisPlQURPxJN6dNCT7Ek9OujJ/ElndNB4nHzVHRCUA4+Bys60",
	"mVW5wpqZkXFX5GQ2U0pFCJNGoJlD3h1snEOmRgSXtqdw3KQbxlu72uTqgupmIzKsQdCOk7KlLepybC2Y",
	"ylCHWfczsnbCUnXcWcUbsbOOAWUVJlxCNTV/ouafEYrtB3sHo34en193LXXHm46D6JXOnxlu1BW0OYhO",
	"bYLMcLvu41d1PFjo5+oPa+cipRFs/qRnxxQ3Olstm8EmbtQdiHy4WXJI7EkUS2Ppw2GmuOZQ1DiRON6/",
	"LIugroS4qjVCZzRdmKfR9dccOHKcQXtJG566m8yClWQK5RZU4pDQ2YnSPIIxQaUgmYC8B6BloKxuqibz",
	"F8iGMmy0S0AssRwM/PUJzLg3j13xfDYxCo8suHUh0rOJceoc5xNGnzh/CWTuDbyTwmOA5ucN0IyD3sGX",
	"xWxmvLe034pdnNg51Gr8Gdf/AdpHxHriGsuif0598Tx4Tn2MCt1pVKh5+H4jHdrP1qHw6I52XU8IirCy",
	"nuF4Tih0DnU/XzQGUAttjepj/dRDwdXR2742gE4sQIYE9AOKudTGEQ4mRWA9IOUOk1QNPEJH6EKDieIU",
	"c3Pkdp5gwgXmJYAmheI8YJINOvc2ROSKzCHLkmtVyENnVOnbh2gcXRb69fRxpI6f3kw/O9mIHOIhpsmw",
	"8wGHHtG15TuCmk2UFFARXX8pYTLtHel8ywpv0G0dn5PZfJiqmZpcfzpJc5XAtOb+YBI4a9BSpmMK9BVa",
	"+Xnq3vJwnegKCdT+zLBiThRTa6+YchBzU1SslSqlPcsjB0i76MKDuF16Us2hXVi+UNIxoJtYu/hVfebt",
	"Cqc1XISg9rDTLl6ZvsU2ea29eFcQgnH1rUdXaYpwAUKOCpxP8MD9GvKCWqtuSuitLjI/vBKcEiz08gtT",
	"w/zwaqiRSWxy6rsRCDVZUqLSPqw/m+RDxl9mghOPdAbRetTjoeZ1Oa/OsosS2HaVd27qXUXLGh9Z7LRL",
	"Th2+uoqWdXvpUNouelUhuV14UqG9XfjWW4gAgXlL0y79AYdbVan+ArhX0mgljb9jOFlB4YoD9KBvIYuJ",
	"omBmcx5SJodTVmgePcHJUIC0Gxps6sMM+Myj6U05WTmFSwNB8/M7B1Gz4D2TbyyAzaIfcHJZwtssdKkb",
	"m99P3XxaBQ1iLAv6ciIv+Wv7yeiKsW2TX7Yp9Zr3LkEh2K27Ob9bnZaoZr09y4FeXv5oLxhQgiEz4tpL",
	"Cb//9cuAigMVcW8z0yZbfzBEu3W/9a2kHdYnZaehbXVvFIiBRpL2LhiWF3KVElEijheUOl2gRNW3X9dP",
	"23j4x/7wu+HNV0FTrBooDE2Z/N9FOo4jIebJyF6rjqNnDRu8V7hSbdPD1umpvpr+CgxqFO1hsbced0Uy",
	"+C/m3LKcI+07ZoyT7Xf30B+MQnX/xYU1f2gCPjl6f2Rv29DRxeujvXdnx0dXJ2fvB+hea/rqYz23k9KG",
	"CdWxwhyxGDA1h2zXsvRP0bm9MJckLlLMkSASdPypPnRgiTAHPNBbySIeHWnXFbz3Hu5//U/GbwfodaG4",
	"wd455sRZpwqKswmZFawQ6MUwnmOOYx0H4ebaiFNFT8fR29OrcaRW/frq2C52v8xe162kj00H1MrOIWwt",
	"k/WqkEwdjeIybaU21tEklPBSksyVusQJejqsCEXwb+aBccwZff1JraN7qUS/Vf6W4xj81G/r20Nd44dB",
	"JD3aXLujkrBb5yIZBaHtvWV875P2M8dttxizgtZvpu/FoOkn93zVKr9cHadtKVJ3bpa5HgQW7YGM93T0",
	"nTpyTkfJIWebpvl78B7/1HDEeuqQYZJGh5EEnP3HNCWzuYxlOiIsch4Aml++0SXoWB18WYquAGdKf+Gq",
	"qTsq11q3/Bg+1Lu4eRpq9swam2zSDp0HD+IUc3O/qlPFQmbTEkxTAKmP+pDMnCOg8Y6QcyAc3TN+qzaa",
	"MAmRUxIDFVC5XEZHOY7ngJ6P9luTub+/H2FdPGJ8tmfbir13J8ev31++Hj4f7Y/mMksNkUu9XA0kHZ2f",
	"RIPozhlHI0uENgWwosPoMHox2h8dVEGRf0Z7XvILmwXG2b5MyGMo+96xcbbF6LhqfGkaV+n4qkuB0ixy",
	"kpSNO1tGhrxAyB9Ysmgkl/AcoPd+s5Yos6c340mdQDzUydw+HmHyYguzC5/vH3xR6EJLkqjV/np///MC",
	"ViZna0HxA05QCaSC5OBLQXJNcSHn2hPJIuXFlwLlDeMTkiRADRzffSk46rnnNTDPvxgwV4yhU0wXjlx0",
	"8p5vvtwiXRoZcE1LQ7LxdcEzfRju5JLRjaq2hIvu/am4/4N2bwcZcgvCiVHfSrfqzo3fZqZvQS7jpFXg",
	"rb4GX+5bt5qZI8nQzNzxENWDTcVhxZt1sa5zzYG3XE2jQ0HJ7wWcmItczWLNHXaNye7/jZjs2U+PXK2D",
	"q339peAozUyP/GyH/Mxqt5Z57bkEfJ1c7C1Im4fAZuqz2e661cC3IF3uP5MYcF12ZVpZllQfXDQdVnbD",
	"sR7aKUDLF8+0pbGE4OfqHRI9rE5sUI0bzHy4bNy/nC3aJenkgc/Nhm9uReRFEf6t2OSXZE+o4k9fTvn7",
	"+6p9HlcyTCPMgqob+BzLOByl5yLwvJSUr1bxId2slpp0Mz7k60gawl3xnJt1DsRDPfRXO1jDWvxAr+Pw",
	"F2ZJj8feRwVxNQd+1BAbGiLqUhFLZjyI8iKg8l3bJ5fWZbgXJgJnxyy3egTpL+e5O+Rrjyz2/0cW+8ja",
	"+mt1Vdbz/tcMFIWe+1l+v9B+Q+gv3NLtwf8O9wkdUD3eIzzeI/yLHCX/1vpUi/N1csRVVwZvQa7LFN+C",
	"DHHEtbSu7vF2ei/wBaxdvTjjo/H/8Wz3L82LHkyya8cMjIPKHs7J3t2BSe9mWrffGrecRiBGm2cz7WJk",
	"GYFVBNtW9HoP3XzG76w9hYebh/8XAAD//1zsCQSs1gAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../core/v1beta1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
