// Package v1beta1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1beta1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/core/v1beta1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9iXLbOLbor+BxblWSaUneEsdx1dRcxXYSdUe24yV90628CURCEmISYADQstLlqvcP",
	"7w/fl7zCRoIkqM1Kp2cqPVUTmdgODg4ODs6GP4KQJikliAgeHP4R8HCCEqh+hpShf93uDJGAO/+iKSIw",
	"xf/qDjmNM4HOoZjIShHiIcOpwJQEh8EFShnisi8ACYCmLhjhGIEUikknaAUpoyliAiM1SOrt52qCitay",
	"ChAUQN0PJUBMEOAzLlDSAadUICAmUABIZgDdYS4wGeuqUxzHYIgAvUVsyrAQiEgI0B1M0hgFh8HWLWRb",
	"MR1vwTTtxHQctAIxS2UJFwyTcXB/n3+hw88oFMF9qwExKX6PGFfwV6fTPe+ZMhChESaIqync6m8oAhrr",
	"gI6AmGAOmEUjlB3Iz5AAPX4HXCImGwI+oVkcgZCSW8QEYCikY4K/5r1xiTM5TAwF4gJgIhAjMAa3MM5Q",
	"C0ASgQTOAEOyX5ARpwdVhXdAnzIEMBnRQzARIuWHW1tjLDo3B7yD6VZIkyQjWMy2QkoEw8NMUMa3InSL",
	"4i2Ox23IwgkWKBQZQ1swxW0FLJGT4p0k+htDnGYsRFytCsmS4PD3wCA2aAWjGI8nIhSxHKz4HHysrlIr",
	"uGvL5u1byAhMJGX9HhQL8j5vWnx7ZfvuUV/xSZKKmRzorj2m7QpNNFJAeqUq+qhZdqHXFwGYpjEO1dq6",
	"E1cbkaOgFXzJYBQjEciBiICYIBa0ggmKk6XnrkA5yns0H97lHec1iv7NpzdqmDmTtLDLtogIOV8Yx2ej",
	"4PD3P4L/YmgUHAZ/2yrYypahxy1vh69wjGxP9601OrhAMRT4VnMk2QNDXzLMUCQRodjLx9oeXmZ6J+T2",
	"PWSaSZVYFioKYBRhWRfG56UqNYIpE8QJucWMkgQRAW4hw3AYI3CDZm2170AKMeMtgIkEFkUgymQ3gGVE",
	"4AR1gKSnGzRTO1i3QDCcgCTjQnK7IRJThAjYURV2n+2BcAIZDAViaqNVcLECh8txc06ZqNO5/AoSmKYS",
	"WkzAiLIECjAIJpQLWXiYk7P8axCAx6gz7rTAIDjYPtg+PNgeBE/KDNp8l8cGFJJ/BYfB/x4Mop8O5f/9",
	"V51fLwE7o7c4Quwl5J69ekSThBJQrLicBYBx7O5atZt5/TCDBQdYmYwt97hvBXIbN5yJDgyyVr7mO//v",
	"//zf8kqDmJJxC3ABmQBTLCYAghhJHALKAMmSIWL6EDCLAggFU8mueQpD1PEehe7WspP9uA79mDW4TFGo",
	"ZorlTBNMoKBMfjBUpMUQzcQakGl4nNN5iW02tjIVyu0Ui21oIvliubZl0w0NDLN129znFDM7VYucY/G+",
	"FVCC1mWiHiSsxUu9IK8Fjwe9a/VUxfpSrPvCyBVvcYK1WFsVU3U5iFUFtcU9B3N5c4dp5mEX59e6E8nv",
	"JFi8A15ptseQ3DiKgQ8hR5EUXKs8pMzstjvPn/k4WoISymb1wfvquxlfbXGa6tMISLHsAZDsPttPHiQL",
	"15Zi3iqElHDBICbLLkWcr+s6bLaBStaa3qWAIuN+sU+XKekdcEzGcZl/m3tMhG6xZrdWDjxnKIVGtruU",
	"7Fv/vMgI0b9OGKNSYLsmN4ROJSeS+z9GAkXLy4flGbhj1godIGplBVS1IgtmraCAu1bkTGQJ7F9zxOry",
	"GctIl/vPz4wjhQQrietLpPqsb17uApkL1hBJyQtkJEJMyl6YA8wBoUL3IHuD+j6nupH7EBN1Gc1PIe6R",
	"/MFjPLJ/D2P0pAOO0QhmscjvbQYqqAeCYyktsoxwOdzjMSKIwTieAUapeALwSIHEUxTiEUZR/fwu32Wu",
	"DSbcz21+g9O25SHtlKorY3AoWIbW2h3vaZxpUaa4IJQX5dhch6ESZyJwq1rIqUdgOFNKhHmMwC8pXRP8",
	"JUPAXWi3X7NCHi5T47wMhTHEyTmNcTh7KL/R2LgodVkVqtSEPBLVHw+RDnoJHCM9eknwWutA7tOMiE11",
	"piBr7PHjUoe9p2WNJejl9zCFt5gLxaGdjWkqS4LAAiV8M+seFBsIMgZnwQN21EWVLCPNOtShKllO0GrY",
	"ZxM6dbjJBJIoVrvP7I/pBOmNQaeSq5fQovRSCb3VvMUeVma8j2tcxPRcNN+ff3puhCuc1thBw5YfIYZI",
	"iHwCiymyHDpCaUxnKAJnR722pIwYQyIAllQtb1ny2BzBUIAhDG8kPueO7WMFLjzrXLT4ZZYkkM2WlFPK",
	"11zeLKO8QTAWk1nQCo7RmMEIRV655JS6sKwunJTBLwZtrOJA01jHI5eUK3jlk3KV6sSaluJIUuVI1kOX",
	"eCz31AX6kiHu0Z40Vi3UwXKnMvNRqSUAx2OCIhAWbcGI0USt2lHXp6FwtdRrcLW8+X0ruMEkqs/jF0wi",
	"ySwg0ItsVFT5JOw+uDi5vAJWA6ylL03XznwLbXcCZwCTkZXT8kkiEik5Rf0RxliyNZ4N1bXOoEoKVB1w",
	"BIkUkIYIZGkEBYo6oEfAEUxQfAQ5+ua6bqUyakuU8Y7/kidgBAVca13OFOL6SEDZFTdn4OrX9iYSNCd8",
	"wHNmvcG+dZ919VJOaobSHByZOS7NEedPrEbCvzKYpkjyb5qRCEAlirdDhiTdgKPLixZIaIRifZW+yYaI",
	"ESQQB5gqeoEp7jhbkndudzpzQahvVHSXYqYvRiikJPLen1V7rSDOLUW3MMYRFrP8Ju0AIofRStngMMBE",
	"7O0WlChl/TFiEoXoTjA4T72di0U1Ki5LODW9t+wYQKH3D8qvRcVNx+JY8S+J55SmWaw+DWfqa/e8B7hi",
	"ChL3qr6cOZRMJ0kyIS9THi23Ji4v45UXwyHkaP9pG5GQRigC5yf94vcvR5d/29mW4HRAH4pwYsx3kgQ7",
	"OTvGKI6AvPi59DCPp2vGV1qS4UwgH29QXJ6desWaHok0kSmYWE4Tuo3W8Cpu/CWDsboaqouRHDfB5C0i",
	"YzEJDnc8o2bYw92ve8d/wqo5QHA49gnu1+p7ft9Vxw1SovwNmgHdysGGue9hzrPycVmS8heSs9UfzJcu",
	"/wTEVJilpe0SqWyAOzbI5gXNwTRl9BbGWxEiGMZbI4jjjCHAc5kyn7pjauANiwHwqLDie+wrTlX/NjZd",
	"1qWiVoFNQKUEny/EUhtQcmCsRT2PxciWadlZLjd1N2MH/CLFSRA6FRkCXYU6FLXAMSJY/isx9AriWAO1",
	"/t0zh8h753TpxpnX8tRStzU8zALcZJtbS6PgMeA+tJ8GZcdDFTJN5rD1FCkkxqS5y4/3KyyvJZ6HrWre",
	"T76WqcdE/pCOtd2sQtHCb5L82GratQVPipCAONYmCEoQgPJwEZaHhRlj6nIhJKOynjqSfV/kR/lCnPpt",
	"zvJrwR3ktSlT1wgwonFMp/LC9EshU8gh3bsFuObIGHjlailPqUgKreZsDLXvibxmeywpkIsrBgnXGMVN",
	"hmdZDwicII2LHFaRt0WRvpRJzBnuLyEhVEwQKzFZeftqy7781yAuz+46FG+yBBLAEIwUEzf1ANZHkcSR",
	"XT84pJkwEOfgeYULOlRHb/RaKdOF13dLzr5jLx6dcV6z0MwX2JhCrqQQbWXLUj2sK3HvP/VK3AxB7nUc",
	"A4+HDKPRE6BrFEK9HfMRX2qmD7m42aEaLmqm65aPlvKZFQu7OiNarCEsYaSlSJCOwBXLUAu8gjFHLWB0",
	"Oq4OS5YHrUBVcLRWyympKtCZvipfbdeVz/lIC6fe4E9mfMkKwsOuJsOZopUxglZwdd5/j5i6AGjFli3Q",
	"0odChBQ96lXDEHGOhzGq/mEZ3zlkXFW9nJFQ/XgvL6GyhmRgmejJ42jMEJdkcp1G0FgT5eFkq/azWOA0",
	"RmdTghhXcN3iEB2jkCYJ5hxTZWdcbnVOCKNxnCAijCTrzLdWVp5uozDsdNFYJ8dlY40cyY01yuBcoJRy",
	"LCibeVEvMd5YUFsftzBfq1cxQsKugvrDt2p6NZy10x/cFdRfll3HObQ/wuOqOecBwtZrLDx9riVlFafw",
	"JQoZEpuS2zYF3xshUl9f85Bd99P5z5bmlc/AN7oSlGUrZQZawoqkzUX6ZMe88BrwHuQpZT6PJtf1cnOW",
	"S+Xm6VGDMNepZxMuOHWpQiPPK8gvKT6kme29T4nkoJaXFMRdXq9EV1vsw10YLSgwjRaraNzevQb+NRyf",
	"69Obs9UZJSd3qWTnXjlXlgOUV7DOu5IsJRRRFivDDU4Q7wyIRIepgTn49Hdg/vfpELRBH5NMIH4IPv39",
	"E0iMxnS7/exFB7TBG5qxWtHuniw6hjOJ3j4lYlKusdPe25E1vEU7u07jXxG6qfa+3xmQyyyVWwdFQC45",
	"FFQC0ZYVD3OlLiQzY6wyfsmyG0zARIKc94duEZupb0/kuJ/anw7BBSTjotV2++CTQtzOLuj2JZUcgG5f",
	"1259OgTK6cBW3mnt7JraXCgV0M6umIBE4VC32fp0CC4FSguwtmwbDUy1xaX2NivP5aBAieQ6B06TATnR",
	"rn8Sc2C7fdDa2W/v7pkl7SztZX2UcUETfeD3yIjOsyFULzrKxKKjYyIQqo6sF7ZZFS8cVa2w0wkmmkKV",
	"PlXdCcu27OX4yDFKEYkQCTHiUmbyKgBHeGxNMMoumwmaKC1vZFvPAJ+RcMIowV8b3BYQkTfbqOTPIeQd",
	"pmqdmiB5p15qFLk7Tb/OlIeUxghqd2Qaxz0iELuF8Vrc/NhMfAV/Fk0gzcQxUle2mgeLbFS2haeTGcch",
	"jF0HBevDWrZ1N8USaRO26TwoW2FjOESxWpmRlIqDw3xZch/9YLS/G42GT0fPot0wGg5f7O292NvfHT4b",
	"7RyMdkO0u38QPX+2//TFMAoPtre390bbaPvp7otd+ByNDsI9hbQfFvofFvqld1t+63qgVsd0tIbt/eNq",
	"27zm4lv3zttQ2AxKhiiKkIfgLcesuuBK5mgaWQvhkFIRapHczzD95r+KdtJ1PV3sYwqjmV/g1FE6RtVj",
	"XYmnExxOlAVJtQRLu7KqUCDP2Xuaj2LrAKsYbXLH92gwN+R0jTlgmfI9NA7XvREYxpDctHyrxzJina+V",
	"I7bq03zQLo5VR+mN+0U/aBf6IwnuW80Oq4XS01TJvSKrqNyw/6plFQssirnXoiRqh+pahZ4436et1WPI",
	"ajyl7JbnEyy5rmCpb6KcCCs+vx5Px8pd3kizc3e9K3BqY4Q9SZWKvhRy883U9fOdPxuU9yviX0u8TSg/",
	"cixlhX5eY1YyshEe1xHMpADLUNQYQ39hKtio+cZ+F3lKlMdZfeacxp4DoFTsSqnGNqE+h5QQFBqNfU4r",
	"dWRwfQfvHfsZqikGvWPXHlQZwU9XumXfkWQq2yUXyPNR7MFvDxoJt/Gz+UcpXjmERAlvXHtAYIIFhjH+",
	"qm2GeQA8YgkmMG7lMAtqm7UAEmHTGsLojMQzeyUqEXFlVi0HgSuur6um9gXcGVTo6yS0xBeVldu540dt",
	"YQVkYyQeILC58F2pzvxWcD3OAybvdF4/g3KnK70BuRy2hoQEiQmNytvUtU1dE6QsMcryFArKZheIl4Ce",
	"Z+GZB7HT87xq5VHno0ZekccMi9nRBIU3TZyvuW6VI5R5I7YtQCibgBQxucu0e+max1LbeywVepDqmBqi",
	"TZ9GzRjZ4HHU2P0Ck/EKaC+I1oYGXBNuVYqu7TQ33a1Cxr4JFCPNq+PC0Fwvh665SgH3krhutMobcauJ",
	"wmv8IK2oBdUokbyXi9mGaU7S0cqSXLFllBRXzGSBDCdr51itn+M4kaJxklqEVDq/VS0LSX4575nN7VQT",
	"+asX095KRJpsfEU2ywHqYC/NAxoPKscan28kPx9Ya89X9l/LX960hRcwizqfWLC/3+IRCmdhjNaS7mPb",
	"egM3qKrKvuj8m55VFQRs8Jjy9dxEnW66KB9u6+eRdmsxJFL2tSh/WZFOK1BXKa1SXILCU+4DbUG1xTR7",
	"xv1hPG4p0EVDI7RqARmcXeY3qEYRy2/Fvyp1ok34WsnFwPXF28UX0SYD96KZrrMtzy6Xntf78u3azs27",
	"11TJMR43RtVEqqzal7ZIAj6Bu8/2D+F2p9N5siy+yoOuiL3c/WklHObODotEF5MgZk2+UwbOnrgR5jcb",
	"77TIJ7PBbquRBWkW5COZeTxouea7ZfCSX4ZewHJawSJ4+FfIDO85YljgEMae2OVVWGQZUDc0ul5aDO4r",
	"dQDyFVsgfWULnUod01EDp6zwSdhI6a7mdLmcCqlxldqgb1LZ+armo6QVgs3Q6fJNAeb14PPBxGmMGuwk",
	"scVbKPBtodIzuqwHAlhWX3ojNcsn82Z0VLrnugfFGl1XOrlvBfQhqDBCQ9WbraIOldgpsRbjxmXIx/g+",
	"PHBtKo5cvtXRNrNoRZ+Jq9zaFqkgQyxPsbLTWsUFDopwcq4zLXqNKZZGVUVgcjKWp1+zv2hnJAtHRrBQ",
	"klLLpCzTKZOkrM+z0QjftYDObDBBcdzmYhYjMI7p0A6m4FejwzHEhAsbmRPPQExhhPQQCqYE3tkA191n",
	"+6Uckr9vt1/A9tdu+7fDwaD9r85A/ff7YPDxfw0G7cHg74PBPz/+9Pi/l6v35J+PB4PO77qir9ibqXJx",
	"OhjtCPGA9EOO27bpRlP9ir46hcS0ssdOXf/pv+RxJ9+LOXeAaZtApWzBsbbrhiKDcRGH9dBjysjIpcxf",
	"jvzwUJZb93/wbG9YN9ptZsiKeXT5UNZ8vXQ6IOUPYE2lEufekDh3Kb5J+Kp7rK9/BBa2S6UPNKqSzWnN",
	"rPbvEiGyTDidoUAdPYaIDQ03HBs8Pj27OjnU9v3cI9KkoGNIZIyUwsmfLKkuNA4OnzklbTwmlKHcoyFX",
	"NWxOj7KJ8zrv6GH+597LoDxjH7zxaptNH3rWFXbdXotOypKAn5+VDtrNcDINQXRNsGjmYcZp78HHVNSg",
	"GXYYVwmxZe4Z+JmpSzPuns8ZiqLOYhIFNbi7YcUL7PquKQ5XmEAWTSFDyjVc+65jMrZOVKUM+pt3WTEw",
	"2Hjeb+a04sHXBhWvK+VA89sAzlSclj/d2QUaUmqi4s7pFDEUnY1GJSNBdwqxUCF+xkFDB4WOYhyKc5jx",
	"FXWypQk5oNXKHGg9pWV1QqnInZOnuDRNT3lVS1wq9CHDU62KnwVrXOK0ywUdnNlsyWYzOYmJ0F1KeXGs",
	"Kl/CzoCcwHCiEsyElDHEU0oiHeZe3Af1rjJPbYQwhUMcYzHrDMji8AU9idKmDGkc61cAcofqRnFXAtno",
	"PyXFjq5yiTQOVN497PpIN/Th1JBSog6qMXiqBVcUPUt68jk0vaRUgN7xKl3p6JC1T9ValIoUTSxj1Uvg",
	"n/pZzn0vLfddEuaqf7WL5Rw1dSha5TVdke3Vbn0LHHlSVVMZRBJI4FjnVFAHgD4W1ZsUYZxFskSlCjXf",
	"nVTJEZ0Scw2XB5bJiOOx85t6lzq2bD1JU88w7yIXQjba6f06WI/WstNo6DdqO3WPcd39Nz/GSxjY4DFe",
	"73cF62mB2tx0ml7RY6jyPZ1l4mxkfjsh7uvYAkpAOkN4St1RvY0rsfbl0oXqfsxvFgbAbibmtPUXi6T1",
	"MrmwCM8zHSj+hvmNzha3ytNkEWZI+Q7mb5NZtbDsvtzn/Lms+j5RHm3nhSuBdzjJkiIfJIxjOnXDOLTz",
	"saAgNIn29WtCeYOCkeeZ5AFUoXZUsoxb4zCDmMlNZBIya12GfnSiiLTNP6qEZ4fgE9dBq1xntGyBT4n+",
	"oONQ5YeJ/qAibjvlV38e//Pw9532i4+DQfT3J/8cDKLfeTL5uPwTQCckpPLkWsanFZm6mlCVR7NaWShg",
	"5XE2l6OksU69rZNJLp2qRA91bhrbv1+aTpqnU0ljUp9TrcqcTMImj58kDe08W1LmrRdVWQexHERnYih3",
	"9qL9vd3oYH/v+V4IIYrg/tMIPt1+tjt68ez5CMLnT3dH4fPtZ9vbu/vPnx4Mw+cvtvefhQcHOy+ineG2",
	"G1AXchYcBm3538uT171TcHRycdV71TvqXp2Ai5N31yeXV6p0QPq93suXn49esne9l93jl2/71zfTi+mH",
	"4/fv3h2fbHfv+rvvdvtff745O/7w9fTr6ecPv76Kf3t9snv6+mJyetzdGZB+8uHZ6VWUfPj1ZO/0+Ofk",
	"w9dwenrVnfY/f9g7PZ7gD1/DZ/3jDzsfvo6f9q/im/6vvWn/1c30ZPrhzS/0t96AfP28fdR996En//r6",
	"efu4+y48fjfunrx52T/a2z69+Pnq573TX89ihF98+PXmZX+r/5WeHr+e9S9+yb6ebG8NSPjLzex/3v+M",
	"7t582b7rkd3dD0enp3u/HZ/e3U1/3X8bvxvv4c+vye2leHc23O92+136+ujoy+vL/tMXL7v9owHpbo+7",
	"/ZPro96740t2h/dvWHT0S/j2aBL1X+5Nn/e+JMfxb5OLk9fDN/2jk8v3ZJ/z825v/Nvbn96xn8V0QA4u",
	"fmJPUww/3P52Ixi/2Zsd9bKve5Pe85h+SP7nfC86+MeAKLSfnB7PWZIf4bA/wmFX6qbGYTYQGVvv809I",
	"UN2QsErH5C/g6rZqkcnQfxXIebxjqTHMXr1E2Bi1Am3mqzmJYKdOiK09WCaQgyFCBNgO/BG1RZz9ms8p",
	"dm3qX92TUsikaTwrnmloSPlQf9FOz/Phy+YYTNcXtpuJoi7lLoBkEW041teHUkm3wRlQSYNQmPhll06m",
	"kJdIZDlfd9viZVPwdDkGW9ZlS71qaHttuVNaIqXooiVYwwTuQXy+QJ3lqdKv/fFW0wehU1GDU6v7iFv3",
	"V2X99XhDcuZfF19udTcHNNfZ8FxC8+z/slfCA9MftAJ1mb5YFIN6pYh2bhyqOudNSFznM6cEPLaB408a",
	"wkQ2zf1sXlJrP1avYDsMEfPc4jxBBEjBwyEzzH3suoFjykVen1k26cgaKq62gWqdNHGsNfPeLGL9EguL",
	"0pW7W6Ges7yzcibyeopi5MfDXzW3uPsYtBdjoS7USzzCvkCTcF57dUUHAt0J8Pj66lX74AmgrPr6gzOI",
	"CnjGceNayHr2xr4mGTlaieV1zRJRzVHcsjSP265jaMxolvrxI+f6iANVo+XogBDWKafsS33mDWHEcAh6",
	"x+W3CwcBo1QMgrmpNhbk1EhohOZCmCJmXEzVUywd8IFm6s6lYdb2mETekEYwwTGGDNBQwLh4ChkqBc9X",
	"xKhNkba9//Spogeoz8AQJ6aBjvb2tXm6u/1EXvpEhqMtjsRY/iNweDMDQ6P4AnnwlcpmUnqmUWc1qUxG",
	"aWTkPCWjLvAqwfMnX8nMO5iN2KJT9RbIN1zPb/qkpKTnDSivH/zUfGnXrZdDdMhpnIk5j9XnbGUVtbA/",
	"x20t0dIYiwsJsF+ucdKSQvAai7KPs3mlZBU1uVWOmwQVIzy2OSSKrMYNuYps8WLRvuiq9KZO3dlWSasX",
	"6BbPk+10qQQ6485TanPhrWUYyYGvjdpqUvjPe/TdnW0lamHpVwTNyi99EFef3f52OYHXy5kbTiATRc7c",
	"CYqThRmwlMo9heH8aL68li/3lXnxUUpT5Qezk1kbpmm7GMIzvlIrzpH0fbkey7kldQ/epFzW7CJPnCEW",
	"DDIczwAxb0HZFyV4RZmfo9vdcQEZY3KniHccHAY7nd0d7Sirc4G7mSo1yBPKBVeUIX8Fh3aETkgTQ/K6",
	"WLOKYMt81JaY4JyhEb6zz70ypCZ1RDMpw+21AnONUayGMhEcHmznyD2KMy4Q6537RSeNL8m15/h/W6Sq",
	"8zZXHUWZtg8W6w1UPybxWgyVMUxNzXV0UC+A6aARFiEGhmgkZRCV3NRs2siMWFqK3w2sslKU6QQ+M5jE",
	"gZ1Em94ixnCEeGeWxHIjL/tq1aYTKzckGa8dNhMh0iVPGwLeXF2dL3neyIU695458qs9YfQN95FeV+vg",
	"JaijfbJSftWFWoHC0S1ijjV0yrAQiDz4tGL108oeNjaP3YyEYM45poNkfJNn+Y3l+uKteX+MJpJkR8Jo",
	"ZuVFR4Ung55Q+Zq0Pw8CXzKkrNkMJkggxgHPwgmA/BAMgi1J5VuCblnTxT9V7X+o2j6xcO6JmC/fn38I",
	"WopcmtTnvtM0J5P4sqfY2VHP81iw79xJYXizlEPBg7f33Ce56+Hi+mVmJSgVs0lkcxQB6Nx0FK+cE4b+",
	"kFfNL9V2UUYpfWys0Z3uSU28MfZc974aKs+zOPY91N0bnVJxrvVZtee6rWdq+SL2yG3zqAN+nSCilH+y",
	"rBtP4Yw/ajlPCmAO0iyO5XVPpQkXOEGVVqeypNQoybgAMNa5RdVDfM3ZkPSYQas6GdXrkv4PEj95P/KP",
	"Sl/yk+lvLp791Eqo0OKN6z6kFvH+m1Liw5I91Dv0RGy76SzMSUJH8ixd8Bi55wZXItH1pu+Q+QqPqC+G",
	"Vj+pytAYc8FmHXAlxf0EzuShDIu0uE5D/eJY7mImuZLtrCUP2ZiSsfzXXHApS3idH3PXaWyZE27lR9rn",
	"v9g373DR/v5zgnPdg8NIORsLuy/0JwvETA3lQw6ipqdxDlfHSC7c6wdZ6xxtfdzkuilPSNS3FWcaUdyA",
	"0LmvF9WQuinY5QVOjras4sl56VA3/DfVX2dErHlLKdnINQ6cm4iRrRo1HIvXrEDrqiqSQjeyuKt/X520",
	"Z6u5ep1iaT8uMo+a1sUGWHqv9lXinB8PGLkoWfZOcgoTFJn06Hq7lDULcqoeudDIaDW58NtcKVa8Sjj+",
	"cvUwtrxMSvx5umalAIBxDFLEOFZ6wCKVlZLyJ/AWtQyvMYoArlpoYFRqeWbq6oPTY0MnhIoixcKaPgxF",
	"Zf1+aikA3v9Wj3kpPc+jOcfpSGcwUJ6aU8jto+zLexpFKEbrjIXjWIVEyearjDee8xxtF3D0JVPHpXkd",
	"ouSn6rz66zxVm7uo6EzN2mMHnFffotfnTwdcIBi1KYlnS75eu9iFxUnEsr+3MAyyD1VWVOONe4NmWsVq",
	"FLVasVXONU7ZGBL8VQdJh1CgMWXyz8c8pKn+ylGMQvHE0raXqJY7P3X9Wn4Z37zUGedbRMeNGAp5FHJt",
	"yLDfW1JCGCi30i059iAwz601ve2hWjU6LnUJoCn8kiGLVDUsVll286AHrXB9xIvwVcfFCRJn3vWDYjku",
	"dg5FOHHCFXKpe25WmTLDoQ27z8ROauOdyeTs6ipgFAXauqCPcYYSequ2XzmToPPUold864KfL89OwbmW",
	"GnKtlt/a4wdV+5ebd7qp2sESqE7tkKDpPIthPTWKB+XvMhjFSPx43/PHk/+NNHJhzFn++8pFOWbIWL7U",
	"hcWv0m3aN/W29h5uD55TKgxHhMQoHyWzUvXtaUpvEXOsMYUJlrNwC5MI3XU+8wfwKCuUdmPExIUJIk6b",
	"swjU5zkpp9+v+NIqzb7s2+/Y2hjfZyP/pIwnrLQhkeFcFuEtYnCMdPAhwM47TsYOqQbGZNwBr9Rpcjg/",
	"ru8Rf1QO2HuUPCoH7D2aPGoM2BsMop+aY/RSxEJERGNy3aJcYk3PSLu2MjweS7nUh0ktE2mtwy1aO61T",
	"iQguTU/+UGY7jLN2pcmVhZuPa5FhCYJ66KIprVGXPfq8CU9V5oPlVPSNsBQdN1ZxRmyso0FZhAmbHVHO",
	"H8v5J5hA88G8fCx/Hp1fNy11w5PAreBYZdn1N2qKo24FfZNG19+u+QZf3DBnpzoC0r1aS6lx/WOmYYpr",
	"HTDzZrCOy30DIuU51ahnWJIo5qa38Ed+w5K7WOVSa3n/vJSgqhJgslYHnJF4Bigxm08yL2A5g/Ko1zx1",
	"M2lCi5PJlyhUHoeYjN03XRsOkiESU4RIHruumsrJ/AlnQx7J3XRAzFE+tdz18cx4aR7b+ISJDiPAWuAR",
	"GTOeV2o2IYxtkEVEySPrPwK01cm5XX7DONbQ6x19mY3H2t9LubAYuELrUKzulzpCogW2ATaeyFp9697y",
	"93a9t/wfwbMbDZ7l3Cv6LCM+urljJB7tzbfpeVHul1MTGE4wQY1DTSezygByoY3lYqDeQskYGgT2OQ7Q",
	"MwBpElCPq6ZCqZYY0gkry3E7txDHcuAO6IILBSYIY8i0RsI6hXEbvxghMMzkpkM69aV1iANYLMhjMy/V",
	"W4E8cEakqHkIBsFlFoaI80Egb+fOTL852fAUhW1IonbjCydLBCHnD20qNpFTQEF0yzNInfexqxKSS7yh",
	"ZtvCBI8n7VjOVGeeVFnMi3S6Jb8RneFcgRZTFVOhzJn555F97MZ2oipEqPRnAiVzIpAYdc6IIT7RRdlK",
	"iXvqs+xaQOpFFw7E9dJeMYd6Yf6ET8OAdmL14uPyzOsV+iVc+KB2sFMvXphMyDQ5UX6/CwhBOweXg9AU",
	"Rdg4KksF1ou4ZX+1WUaMTjzG5EYV6R9OCYwx5Gr5ua6hfzg15Mg41I9O2BEw0Tl7gly7rj7rVFja0WgI",
	"I4d0WsFq1OOg5iSfV2PZRQ5svcpbO/WmonmNuwY79ZK+xVdT0bxuLy1K60XHBZLrhb0C7fXC185CeAjM",
	"WZp66Uvob1UknvTgXp5GC2n8LYXRAgqXHGAJ+uYiG0oKpiYDJ6GiPaKZ4tFDGLU5EmZDI5OIM0Fs7ND0",
	"upwsn8KlhqD6+a2FqFpwSsUrA2C16CWMLnN4q4U2kWj1e9/Op1ZQIca8YFlO5KQirj8nXzC2h2Q7rp56",
	"VTOV9xBslt2sV69KklVSXJ6liFxevjH2FxBBlOjj2rEubT898Ig4qCDuh8y0ytbvNdE+uN/yVlK+68O8",
	"U9+2mmoBoqWQZHw1rDmzECJyxLGMECsLFPbFp+WLJmx/3W6/aH/8yauFlAM1vFpv36mwkZ6DgPNJ1DFG",
	"6UHwpKJ+dgoXim1q2DI9lVfTXYFWiaIdLC4tx13hBP1GrYuc9UB+S7Verv4wJfhKCSrMg4ybm78i4F73",
	"tGuMkaB7cdLdent21L3qnZ22wFRJ+vJjOdOYlIYxUSHVDNAQQdJSNlnbMncCUpnmIBM4zGLIAMcCqfhb",
	"demAAkCGYEttJYN40FX+QXDrFE3/9YGymxY4ySQ32DqHDFvFTEZgMsTjjGYc7LXDCWQwVCERdq6VOF3w",
	"eBC87l8NArnq11dHZrGXyzN3XUtBWvXcHWFiTa6mls7Blgkqr0ZhnkRV6alI5Eu/KnBiS60nk5oOzXyJ",
	"DtbzXzlilJzcyXW0igf1mP9rBkPkJiJcXRVoG9+3AuHQ5sod5YRduxeJwAvt0lvG9d2pvwNedyrSK2i8",
	"jpa1iel+UschsHBoVnHqhiJV53qZy2FjwRYS4ZaK15NXzlEnOmR03aST987ruAqOUE0dJRDHwWEgEEz+",
	"2034F1iHCcUvX6kScCQvvjQGVwgmUn5hsqm9Kpda19w+fi938fGxr9kTo2wyuU1UVkYUxpBp06JKXIwS",
	"k71hFCMk1FUfRWPrbamdScQEYQamlN3IjcZ1eu4Yh4hw5OQm7KYwnCCw29muTWY6nXagKu5QNt4ybfnW",
	"297RyenlSXu3s92ZiCTWRC7UclWQ1D3vBa3gNk+naDMo6oTUkg6Dw2Cvs93ZKcIo/wi2nBwhJlmO1X3p",
	"IElfLsgj7fgMwVHR+FI3LpJDFvrwXC3Si/LGjS0DTV6Ii5c0mlVycDjO6FufjSZK7+n1eFIjEPdlMjeO",
	"uDpLO9e7cHd757tC51uSSK720+3tbwtYnsOuBsVLGIEcSAnJzveC5JrATEyU45ZByt73AuUVZUMcRYho",
	"OF58LzjKLyEoYHa/GzBXlII+JDNLLirH0bPvt0iX+gy4JrkiWbt5wLG6DDdyyeCjrDaHi279Ibn/vQo1",
	"QMLnEQMjLb7lvuuNG7/OTF8jMY+TFjG4ygI83xVxMTMHgoKxtvFg2YPJMWKON+OgXuaaLWe5qkqHjOAv",
	"GeppG6Z2mP9YY7LbfyEme/bLD67WwNWefi84cjXTD362QX5mpFvDvLZsnsJGLvYaCZOSwCQ0NEkBm8XA",
	"10jYFIk6f+Kq7Eq3MiypPDiv+mpshmPd1zOl5u/vKU1jDsH74lUcNazKcVCM600QOW/cP50tmiVp5IG7",
	"esNXtyJwIjr/Umzye7InUPCn7yf8/XXFPocraabhZ0GFBT6FIvSHQtowRydz5/EiPqSalTK4rseHXBlJ",
	"QbgpnvNxlQtxWw390wbWsBResdR1+DuzpB/X3h8C4mIO/ENCrEiIoElEzJlxK0gzj8h3bR4AW5XhXugA",
	"pQ2z3OJJrj+d526Qr/1gsf+OLPYHa1teqiuSwy9vZiDA9/jUfPuC77moP21L1wf/K9gTGqD6YUf4YUf4",
	"D7lK/qXlqRrna+SIi0wGr5FYlSm+RsLHEVeSuprH26hd4Dtou5bijD+U/z/udv/RvOhep8e2zEA7qGzB",
	"FG/d7uhUe7p1/eV7w2k4oKR6N1MuRoYRGEGwrkUv99DMZ9zO6lO4/3j//wMAAP//B6U7vYHkAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../core/v1beta1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
